#include "pm_std.h"
#include "pm_std.h"
#include "mc_std.h"
#include "mc_std.h"
#include "mc_std.h"
const McLinearAlgebraFactory*mc_VstO7CZHJVG7WD56o3ixZG(void);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);typedef struct pm_V1heuUPdFYSBhXSTZrzev1
{size_t mNumRow;size_t mNumCol;real_T*mX;}pm_FMSUHHOOKD8acuFWLEq4lL;
pm_FMSUHHOOKD8acuFWLEq4lL*pm__IzxUodah3x2_u_ENKAuGk(size_t
pm__6bYkkT4Shd0e1DZPlpqqb,size_t pm__g5DiU2QzFtUiL4XoU6SMs,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);pm_FMSUHHOOKD8acuFWLEq4lL*pm__vffvPR7IsS2XyyCPqmNPs
(const pm_FMSUHHOOKD8acuFWLEq4lL*pm__sjTRWOMR4WzZisVeB2fYm,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);void pm__uc9LGWqLf03gLt6Sr9mtw(
pm_FMSUHHOOKD8acuFWLEq4lL*pm_k5aqR5haGY_ZXuGDU2ua60,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VuZ05R76dw4R_5mH59xUl3(const
pm_FMSUHHOOKD8acuFWLEq4lL*pm_k5aqR5haGY_ZXuGDU2ua60);size_t
pm_kXhhlZLW3c8yiTFYZWcurB(const pm_FMSUHHOOKD8acuFWLEq4lL*
pm_k5aqR5haGY_ZXuGDU2ua60);PMF_DEPLOY_STATIC real_T pm_VWoHHtf6OqO6YXA_khGhQm(
const pm_FMSUHHOOKD8acuFWLEq4lL*pm_k5aqR5haGY_ZXuGDU2ua60,size_t
pm_kplAJmOlA30feiNcOzi7oj,size_t pm_Fr_bHKkQKFWbfi50VWd5Pw){return
pm_k5aqR5haGY_ZXuGDU2ua60->mX[pm_kplAJmOlA30feiNcOzi7oj+
pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60->mNumRow];}
PMF_DEPLOY_STATIC void pm_kzEZvMeJLvOmgX1qMXsT0P(const
pm_FMSUHHOOKD8acuFWLEq4lL*pm_k5aqR5haGY_ZXuGDU2ua60,size_t
pm_kplAJmOlA30feiNcOzi7oj,size_t pm_Fr_bHKkQKFWbfi50VWd5Pw,real_T
pm_kpzAtHMD4_WnheH0UiioSE){pm_k5aqR5haGY_ZXuGDU2ua60->mX[
pm_kplAJmOlA30feiNcOzi7oj+pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60
->mNumRow]=pm_kpzAtHMD4_WnheH0UiioSE;}void pm_kqNP_VNVXgWGcLsAqt8n_A(const
pm_FMSUHHOOKD8acuFWLEq4lL*pm_kUO9H2UqXf8k_y6THPribZ,const PmRealVector*
pm_V9BoL4F3KMGcYqNc2RhxW_,const PmSparsityPattern*pm_FbpiqbN30g8sY9B6YI6RUP);
void pm__wb6CwGt0ZOk_HdP7QVbUp(const pm_FMSUHHOOKD8acuFWLEq4lL*
pm_kUO9H2UqXf8k_y6THPribZ,const PmBoolVector*pm_VCVhWy_VaDhraHrlfFWxBa);void
pm_kRraI4tqfotp_aUXOIifb6(const pm_FMSUHHOOKD8acuFWLEq4lL*dst,const
pm_FMSUHHOOKD8acuFWLEq4lL*src);boolean_T pm__DD6QRkN3jGod5UZotcfi8(const
pm_FMSUHHOOKD8acuFWLEq4lL*dst,const pm_FMSUHHOOKD8acuFWLEq4lL*src);boolean_T
pm__Wj7kGLfa8_wfmNCNFVchb(const pm_FMSUHHOOKD8acuFWLEq4lL*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,const pm_FMSUHHOOKD8acuFWLEq4lL*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);void
pm_VL4rp2NEaF8Tcu2gE6TeeU(const pm_FMSUHHOOKD8acuFWLEq4lL*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,const pm_FMSUHHOOKD8acuFWLEq4lL*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);int_T
pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,size_t
pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(const PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_rv_equals_rv(const PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
pm_VeeoZXnlJQ4u_112lGs8YD(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_kpDvbw1GUlp4c5YdnW7V_w(const
PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(const PmCharVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmCharVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_FltUsml2sTlHZuCkbw_pdM(const PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(const PmIntVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmRealVector*pm_V_q_QnwoVVl6fHS_0pLvYo(const PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_VeffaD_A8DxagH31Usec1H(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_real_vector(PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_int_vector_fields(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm_create_int_vector(size_t
pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*
pm__fSS_VMqhWlobeqe6mQF_x(const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_V_eFnKjg5I4Uc1DwG4yU27(
PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_int_vector(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_bool_vector_fields(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmBoolVector*pm__jbisDMumXdocXANx5LhhY(size_t pm__c6Ltywqrrtqii4hsDTKgz,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_kia_QXK77_xDg9M1NzHr3r(
PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm_kpRdzyG9L_8MV5lRovACCg(
const PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(PmCharVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t pm__c6Ltywqrrtqii4hsDTKgz,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VH4is_vKxDpFiupATTqV_4(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_FaBQ30lWObWMi1zpzQ_EZG(
PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSizeVector*pm_FZch3YyGWrOM_PQNdo7b2c(size_t
pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FJsPJplguVOI_1EYyUUvfK(const PmSizeVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmSizeVector*pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(
const PmSizeVector*pm__hARyx1bZBxVj1boVQqdtV,const PmSizeVector*
pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(const PmBoolVector*mc_VgJW5ZqpwPpuY1inYtaofQ)
;void mc_F4xMxEJX_DlUYXuaiDuSWS(const PmIntVector*mc_kyVj_uOQd__gg9_ljlZ_IY,
const PmRealVector*x,const PmRealVector*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF,const PmIntVector*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(const PmIntVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF,const
PmIntVector*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV);void mc__pmVtsSuXZls_1NfvVprZ7(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF,const PmBoolVector*mc_kd_kJxzsgTx9W19pl4H_AH);void
mc_FR5FdJeEvDGGcyEVkxeE_x(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF,boolean_T mc_FL_3a__K44dYi9fe74WHqt);
void mc_FK6EqkTbVFGMZ5QwXcurHx(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,
const PmIntVector*mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(
const PmIntVector*mc_F6RwpxHXSXp7gDlfFRloPz,int32_T mc_kg4CyRgbu6OdeewZOel7Qx)
;void mc_kB1aHs1BVHG5YHNpmLLvkW(const PmBoolVector*mc_FrF2gTbWxox8geiSROFaFn,
const PmBoolVector*mc_VwOeyeOYCKdcVTySJQVoLE,const PmIntVector*
mc__vpsWwfj3fx1YDJlP_lHTd);void mc_V2P87Xoe0TGNeXNcn27vUJ(const PmBoolVector*
mc_VRbT1WwZjwW6f5YGBCFuaD,size_t mc_FnrjFNs9eQp9V5vCxPaoKw,const PmBoolVector*
mc__d7LC10lP38OY1VXN_tFqb,size_t mc_FRuIUemzxbdhfqkjXhoyK7,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VqP4HesDIf47bDn5teE2H2(const PmRealVector*
mc_VRbT1WwZjwW6f5YGBCFuaD,size_t mc_FnrjFNs9eQp9V5vCxPaoKw,const PmRealVector*
mc__d7LC10lP38OY1VXN_tFqb,size_t mc_FRuIUemzxbdhfqkjXhoyK7,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);size_t
mc_FLTxr_Wc1PKSeTxwfrcl5B(const PmBoolVector*mc__MqKyOds56_XeH9Iv3CTIL);void
mc_FX5UXdAa2flS_1wrwznTLh(const PmIntVector*mc__vpsWwfj3fx1YDJlP_lHTd,const
PmBoolVector*mc_VwOeyeOYCKdcVTySJQVoLE);size_t mc__RsEbvPhcXp6iqwYpH_OQY(const
PmIntVector*mc_F6sy5cXK8JOKeiFBw6znSV);size_t mc__fQVSVSgEBG6fuximVFlkw(const
PmRealVector*mc_FawmFe5oOEC_cmkvZc1Kaa);size_t mc_FyLahU0kjICfba8O7mWi8Z(const
PmBoolVector*mc_FawmFe5oOEC_cmkvZc1Kaa);boolean_T mc___gjB_jZtTxReaWZSEiFdh(
const PmIntVector*mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T
mc_kNrn2e3NmaGNbmzmXpvCR0(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,int32_T
mc_kg4CyRgbu6OdeewZOel7Qx);boolean_T mc_kk65_VI6zC0mWHqRziXpjX(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,real_T mc_kg4CyRgbu6OdeewZOel7Qx);void
mc_FGkd8Riw6p4eaDCAbwBVPv(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FzkrLuS4xMOvaTv5dUw3j7(const
PmRealVector*x,real_T mc_VgJW5ZqpwPpuY1inYtaofQ);void mc_ks_PW4I7dwWbhXAWhHTUCI
(const PmRealVector*x,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL);void
mc__w_RD4J1MZlqcL7as8FLdk(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,real_T a,const PmRealVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(const PmRealVector*x
,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL,const PmRealVector*
mc_FBDi_PCg670TjHgJTNPcHr);void mc_VWnvos7Q548uVH7p0208jN(const PmRealVector*x
,const real_T a,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL);void
mc_V7hiVZfxKK0Uj9rPai4LYw(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
real_T mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const real_T mc_kcda_aHAM4WIXuM_xBDdLt)
;void mc_k4v_yYmXHgO1cqVdr5a500(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,
const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(const PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(const PmRealVector*mc_VcZASgthsTt6dul8DlRWaw,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(const PmBoolVector*
mc_VcZASgthsTt6dul8DlRWaw);void mc__aNO1s5qwzt6fXwft5YgCz(const PmRealVector*
mc_VcZASgthsTt6dul8DlRWaw);void mc_VTlukZ0iimdzge7aTGg7rl(const PmIntVector*
mc_VcZASgthsTt6dul8DlRWaw,int32_T mc_kg4CyRgbu6OdeewZOel7Qx);void
mc_VDWYuA0FfQClgukbQcp3js(const PmIntVector*mc_VcZASgthsTt6dul8DlRWaw);void
mc_k9wkPuvMCi4DY1yebDQPHf(const PmIntVector*mc_VcZASgthsTt6dul8DlRWaw);void
mc__Nb_EyyxYi4ddPcS0H7Bot(const PmBoolVector*mc_kd_kJxzsgTx9W19pl4H_AH,const
PmIntVector*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt);
void mc_k1sxUtEClkOZVuHMQ91JqD(const PmBoolVector*mc_VcZASgthsTt6dul8DlRWaw,
boolean_T mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(const
PmBoolVector*mc_VcZASgthsTt6dul8DlRWaw);void mc_VQ1YWbKmkVC6YajZAyvmNH(const
PmBoolVector*x,size_t mc_kwrB3ZoKf7OufTHWaHJV7a,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(const PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(const
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx(
const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,const PmIntVector*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,const PmRealVector*mc_V_rxJBbuhqtwViRHFKhdGC,const
PmSparsityPattern*mc__Df1hQFzAY4fiLCvP0PV12);void mc_VMRKMuNLnDxXjaBiy1RcMD(
const PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const
PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const
PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const real_T*x);void mc_kXj99iXjC1CoZLWwPRH879(const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const PmRealVector*
mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*mc_VknkCg_msB8Ga9ymQtGggf,
const PmRealVector*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,
const PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const PmRealVector*
mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*mc_VknkCg_msB8Ga9ymQtGggf,
const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL,const PmRealVector*
mc_V8ujEMKrDU8Q_mvu4yja1b,const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t mc_kyp6uAyJE40UVuAQNEYzS1,real_T mc_kcda_aHAM4WIXuM_xBDdLt);void
mc__WqQP6u7DtdYVDzUK5y971(const PmRealVector*mc_FBDi_PCg670TjHgJTNPcHr,const
PmRealVector*x,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL);void
mc_kc89O49Oe18lWqn1Nr_t61(const PmRealVector*mc_FrF2gTbWxox8geiSROFaFn,const
PmRealVector*mc_VwOeyeOYCKdcVTySJQVoLE,const PmIntVector*
mc__sdtG1OgJQtqcikFA20Doo);void mc_F4wnJSMmz0WHaHs2tnfI5y(const PmRealVector*
mc_FrF2gTbWxox8geiSROFaFn,const PmIntVector*mc__sdtG1OgJQtqcikFA20Doo,const
PmRealVector*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(const
PmRealVector*a,const PmIntVector*mc_kwrB3ZoKf7OufTHWaHJV7a,const PmRealVector*
b);void mc_V_Fp06wJOBhXZyLbA5xU0r(const PmRealVector*a,const PmRealVector*b,
const PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a);void mc_FuY0t5xEb5_QhDQFQ_TXtc(
const PmRealVector*a,const PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,const
PmRealVector*b);void mc_kkPot0UJiN_EX94QlR_mCs(const PmRealVector*a,const
PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,real_T x);void mc__0IkRn0eQ9Wc_u8mCNbQDh
(const PmIntVector*mc_VUELvXWGXPlKf1brR9MRC3,const PmSparsityPattern*
mc_FBOWjCOBM8SyhqFe64oqrx);void mc__pbFNjwg_bCPdPFSjC2Wdv(const PmBoolVector*
mc_VUELvXWGXPlKf1brR9MRC3,const PmSparsityPattern*mc_FBOWjCOBM8SyhqFe64oqrx);
void mc_VpjBXBa8TTCl_uBXYMLfxC(const PmBoolVector*mc_VUELvXWGXPlKf1brR9MRC3,
const PmSparsityPattern*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(const PmBoolVector*mc_VUELvXWGXPlKf1brR9MRC3,const
PmSparsityPattern*mc_FBOWjCOBM8SyhqFe64oqrx);void mc_kMScbNM1RKOTaD4QwTME8Y(
const PmBoolVector*mc__1Zf2IciMRCub1vvbEr1C4,const PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,const PmRealVector*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF,const
PmSparsityPattern*mc_VknkCg_msB8Ga9ymQtGggf,const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(const PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K,const PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,
const PmBoolVector*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
const PmRealVector*mc_kVkvrfpzuVduaPTr5FLF8K,const PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,const PmBoolVector*pm_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(const PmRealVector*
mc_VgJW5ZqpwPpuY1inYtaofQ,size_t mc_Fyss_XM3F_C4dm6IKoDw4G,size_t
mc_Vs6xonQX17Krc5vXv8T_zq);PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(const
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_klSR73f0rO4LhXVlV6gmb7(real_T*
mc_FkvBQdfnWOCY_uJC_r4riI,const PmSparsityPattern*mc__z_znac6SDtIeyvo_HaL8F,
const real_T*mc_F2l4p_g4sn02huHNflQjMH,const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI);void mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*
mc_VO4ezo9C6qdUWq1Fln4EVt,PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);
PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const
PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__qAqv2Z2m7K0VPPGKiCpwD(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const
PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(const PmSparsityPattern*b,const
PmBoolVector*mc_F8fT7naL9bOcimTADCVzTC,const PmBoolVector*
pm_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(const PmRealVector*mc_k5z61obNZCWCbyygZn_fdK,const
real_T*mc__uV9GcaXWFlx_5jfPip5Mo,const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const
PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(const PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(const
PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,size_t mc_Fxvltms7Im4baT5ZPxj7f2,
size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_Fzylow9cnZxIhyL1O9nM0I(const PmRealVector*mc_VIutEr_JmfWNeDyKonnHVk,const
PmRealVector*mc_VW_HqYZElHCjWHwd6Iv4ON,const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t
mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1);void mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,size_t n);void mc_kNxwVTI76g4kj9P52yKhA5(
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n);PmSparsityPattern*
mc_kNYMmfXA1XtHcmiWCr7l_C(const PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc_VJlBwQnSeLpciXVTLb_llB(const PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__5C6m_ZyP9_NYekcJCEULM(const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(const PmRealVector*
mc_kuYGZlr6GiOSeqresCsPcM,const PmSparsityPattern*mc__ILFYYSbi7hW_uYs_eHsRR,
const PmRealVector*mc_FmeGGSq6P2_Kg9j7twxwci,const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,const PmRealVector*mc_FQSQWg_QFOKIWm9DWdLQR6,const
PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,const PmRealVector*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kyCwDjPxmBGRiTH73vrjJL(const
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,const PmSparsityPattern*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__tyTSVoY7fpafmg4sUl1P3(const PmRealVector*mc_kuYGZlr6GiOSeqresCsPcM,const
PmSparsityPattern*mc__ILFYYSbi7hW_uYs_eHsRR,const PmRealVector*
mc_FmeGGSq6P2_Kg9j7twxwci,const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmRealVector*mc_FQSQWg_QFOKIWm9DWdLQR6,const PmSparsityPattern*
mc_VLr_Ia18P_8icXM9WFOfYI,const PmRealVector*mc_krOJvR5Qa1KQZu3eEsQtEU);
PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(const PmSparsityPattern*a,const
PmSparsityPattern*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);typedef struct
mc_VSpV1kj40D8RY9HkUsdI9A mc__mPsQ8V6SzW4c97L9cFyiT;typedef struct
mc__w_PiAX5XUGFda1QEKun0R mc_FoiVRy68eNKXdXlR9clkj9;struct
mc_VSpV1kj40D8RY9HkUsdI9A{const pm_FMSUHHOOKD8acuFWLEq4lL*
mc_kXZtSGM_7S0HWXqFxFKO9Q;const PmIntVector*mc_VjeXnPMgpGOk_PncvX2i2h;void(*
mc_F8jYh1XJ10K_emvBxS7m6z)(const mc__mPsQ8V6SzW4c97L9cFyiT*
mc_FleGJLV78MSFf5qx1JOm0Z,size_t mc_Fyss_XM3F_C4dm6IKoDw4G,size_t
mc_Vs6xonQX17Krc5vXv8T_zq);size_t(*mc__h_bTuBtpZhZZuHwef1rNn)(const
mc__mPsQ8V6SzW4c97L9cFyiT*mc_FleGJLV78MSFf5qx1JOm0Z);real_T(*
mc_kuJm9J2opvOrWLNs_OadzE)(const mc__mPsQ8V6SzW4c97L9cFyiT*
mc_FleGJLV78MSFf5qx1JOm0Z);boolean_T(*mc_V2eI1QgtIrCYeLJdteQbAG)(const
mc__mPsQ8V6SzW4c97L9cFyiT*mc_FleGJLV78MSFf5qx1JOm0Z,const PmRealVector*
mc_VgJW5ZqpwPpuY1inYtaofQ);void(*mc__m5kzglAA8GbhqzJEU9tFQ)(const
mc__mPsQ8V6SzW4c97L9cFyiT*mc_FleGJLV78MSFf5qx1JOm0Z,const PmBoolVector*
mc_V2mBNcV1EqCifyH9UdCbkF,const PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,
const PmRealVector*mc_kVkvrfpzuVduaPTr5FLF8K);void(*mc__uwMrSGWCVlEW1HO2TxQle)
(const mc__mPsQ8V6SzW4c97L9cFyiT*mc_FleGJLV78MSFf5qx1JOm0Z);void(*
mc_kj_oOGqml_xqaXiiWNvUfG)(const mc__mPsQ8V6SzW4c97L9cFyiT*
mc_FleGJLV78MSFf5qx1JOm0Z,const PmRealVector*x,const PmRealVector*
mc_FzyLWRgau0pMYq2XSI3ETL);void(*mSolve)(const mc__mPsQ8V6SzW4c97L9cFyiT*
mc_FleGJLV78MSFf5qx1JOm0Z,const PmRealVector*x,const PmRealVector*
mc_FzyLWRgau0pMYq2XSI3ETL);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(
mc__mPsQ8V6SzW4c97L9cFyiT*mc_FleGJLV78MSFf5qx1JOm0Z);mc_FoiVRy68eNKXdXlR9clkj9
*mc_VFNhKLCqbHpDYXjdjCOMmT;};mc__mPsQ8V6SzW4c97L9cFyiT*
mc_Vf73j5Fnw7ltjets1WrRk_(size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);struct
McLinearAlgebraDataTag{const PmSparsityPattern*mc_VbQ99XU_TKpEgX06wWPmmb;
PmSparsityPattern*mc_F6c6SMT_OVSNguJ7dckA7H;PmRealVector*
mc_F6FawrfE1_W8ce8AliQNuE;mc__mPsQ8V6SzW4c97L9cFyiT*mc_FobFX43y9iOubDC_5c4pla;
};static McLinearAlgebraData*mc__ulKzZm5hA4T_iKGnjQqKP(PmAllocator*a,const
PmSparsityPattern*pm__lqjegyKuwStj56WZLiC_e){McLinearAlgebraData*
mc_F32Ql82vv6pW_PYIdpkFQ0=(McLinearAlgebraData*)((a)->mCallocFcn((a),(sizeof(
McLinearAlgebraData)),(1)));mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_VbQ99XU_TKpEgX06wWPmmb=pm__lqjegyKuwStj56WZLiC_e;mc_F32Ql82vv6pW_PYIdpkFQ0
->mc_F6c6SMT_OVSNguJ7dckA7H=mc_kAZzxJsz9tloc11S9uThaF(
pm__lqjegyKuwStj56WZLiC_e,a);mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_F6FawrfE1_W8ce8AliQNuE=pm_create_real_vector(((size_t)(
pm__lqjegyKuwStj56WZLiC_e)->mJc[(pm__lqjegyKuwStj56WZLiC_e)->mNumCol]),a);
mc_F32Ql82vv6pW_PYIdpkFQ0->mc_FobFX43y9iOubDC_5c4pla=mc_Vf73j5Fnw7ltjets1WrRk_
(pm__lqjegyKuwStj56WZLiC_e->mNumCol,pm__lqjegyKuwStj56WZLiC_e->mNumRow,a);
return mc_F32Ql82vv6pW_PYIdpkFQ0;}static McLinearAlgebraStatus
mc_FEFvzQu07uh9emxE6Ymze_(McLinearAlgebra*mc_F32Ql82vv6pW_PYIdpkFQ0){return
MC_LA_OK;}static McLinearAlgebraStatus mc_V1Vtk_gaIwh3jaiP_3PXR1(
McLinearAlgebra*mc__0xU0_E8oSpudDd_rCbZZJ,const real_T*
mc_VgJW5ZqpwPpuY1inYtaofQ){McLinearAlgebraData*mc_F32Ql82vv6pW_PYIdpkFQ0=
mc__0xU0_E8oSpudDd_rCbZZJ->mPrivateData;mc_klSR73f0rO4LhXVlV6gmb7(
mc_F32Ql82vv6pW_PYIdpkFQ0->mc_F6FawrfE1_W8ce8AliQNuE->mX,
mc_F32Ql82vv6pW_PYIdpkFQ0->mc_F6c6SMT_OVSNguJ7dckA7H,mc_VgJW5ZqpwPpuY1inYtaofQ
,mc_F32Ql82vv6pW_PYIdpkFQ0->mc_VbQ99XU_TKpEgX06wWPmmb);
pm_kqNP_VNVXgWGcLsAqt8n_A(mc_F32Ql82vv6pW_PYIdpkFQ0->mc_FobFX43y9iOubDC_5c4pla
->mc_kXZtSGM_7S0HWXqFxFKO9Q,mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_F6FawrfE1_W8ce8AliQNuE,mc_F32Ql82vv6pW_PYIdpkFQ0->mc_F6c6SMT_OVSNguJ7dckA7H
);(mc_F32Ql82vv6pW_PYIdpkFQ0->mc_FobFX43y9iOubDC_5c4pla)->
mc_F8jYh1XJ10K_emvBxS7m6z((mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_FobFX43y9iOubDC_5c4pla),(0),(mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_F6c6SMT_OVSNguJ7dckA7H->mNumCol));return MC_LA_OK;}static real_T*
mc_FaQn66Qi_V0iYuGMmd5xjd(const real_T*mc_Fjrq38q0w9WrgLyXNhsx1c){union{const
real_T*mc_Fjrq38q0w9WrgLyXNhsx1c;real_T*mc_kIm3LiXDCKxeWDpwRJ2Oes;}
mc_kEbBObcYFIxUZ5_77V3CO_;mc_kEbBObcYFIxUZ5_77V3CO_.mc_Fjrq38q0w9WrgLyXNhsx1c=
mc_Fjrq38q0w9WrgLyXNhsx1c;return mc_kEbBObcYFIxUZ5_77V3CO_.
mc_kIm3LiXDCKxeWDpwRJ2Oes;}static McLinearAlgebraStatus
mc_Fx9aOJ297s81beemiWtnqk(McLinearAlgebra*mc__0xU0_E8oSpudDd_rCbZZJ,const
real_T*mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*x,const real_T*
mc_FzyLWRgau0pMYq2XSI3ETL){McLinearAlgebraData*mc_F32Ql82vv6pW_PYIdpkFQ0=
mc__0xU0_E8oSpudDd_rCbZZJ->mPrivateData;PmRealVector mc_VnIU3pm_im4PdeIcvHeFon
;PmRealVector mc_k2mR0INwQSCheHKCBKnq6o;mc_VnIU3pm_im4PdeIcvHeFon.mN=
mc_F32Ql82vv6pW_PYIdpkFQ0->mc_VbQ99XU_TKpEgX06wWPmmb->mNumCol;
mc_VnIU3pm_im4PdeIcvHeFon.mX=x;mc_k2mR0INwQSCheHKCBKnq6o.mN=
mc_F32Ql82vv6pW_PYIdpkFQ0->mc_VbQ99XU_TKpEgX06wWPmmb->mNumRow;
mc_k2mR0INwQSCheHKCBKnq6o.mX=mc_FaQn66Qi_V0iYuGMmd5xjd(
mc_FzyLWRgau0pMYq2XSI3ETL);(mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_FobFX43y9iOubDC_5c4pla)->mSolve((mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_FobFX43y9iOubDC_5c4pla),(&mc_VnIU3pm_im4PdeIcvHeFon),(&
mc_k2mR0INwQSCheHKCBKnq6o));return MC_LA_OK;}static real_T
mc__7lK9ae7wh4FaqcvPXOkmP(const McLinearAlgebra*mc__0xU0_E8oSpudDd_rCbZZJ){
McLinearAlgebraData*mc_F32Ql82vv6pW_PYIdpkFQ0=mc__0xU0_E8oSpudDd_rCbZZJ->
mPrivateData;return(mc_F32Ql82vv6pW_PYIdpkFQ0->mc_FobFX43y9iOubDC_5c4pla)->
mc_kuJm9J2opvOrWLNs_OadzE((mc_F32Ql82vv6pW_PYIdpkFQ0->
mc_FobFX43y9iOubDC_5c4pla));}static size_t mc_VGmBkzO1j_dIZeqsL_k1be(const
McLinearAlgebra*mc__0xU0_E8oSpudDd_rCbZZJ){;return 0;}static void
mc_kYE5jsdAhpd__Pr7fDRhoj(McLinearAlgebra*mc_F32Ql82vv6pW_PYIdpkFQ0){}static
void mc_k6o6JP_J9XplV9_1iX7wE_(McLinearAlgebra*mc__0xU0_E8oSpudDd_rCbZZJ){
McLinearAlgebraData*mc_F32Ql82vv6pW_PYIdpkFQ0=mc__0xU0_E8oSpudDd_rCbZZJ->
mPrivateData;PmAllocator*a=pm_default_allocator();pm_VYooJBURCwKrVu6RXzQZ_5(
mc_F32Ql82vv6pW_PYIdpkFQ0->mc_F6c6SMT_OVSNguJ7dckA7H,a);pm_destroy_real_vector
(mc_F32Ql82vv6pW_PYIdpkFQ0->mc_F6FawrfE1_W8ce8AliQNuE,a);
mc_F32Ql82vv6pW_PYIdpkFQ0->mc_FobFX43y9iOubDC_5c4pla->
mc_VYGWBho6N1K_eyHOMGjDiW(mc_F32Ql82vv6pW_PYIdpkFQ0->mc_FobFX43y9iOubDC_5c4pla
);{void*mc_kk06poLCQlh5i5Yv6GSh7e=(mc_F32Ql82vv6pW_PYIdpkFQ0);if(
mc_kk06poLCQlh5i5Yv6GSh7e!=0){(a)->mFreeFcn(a,mc_kk06poLCQlh5i5Yv6GSh7e);}};{
void*mc_kk06poLCQlh5i5Yv6GSh7e=(mc__0xU0_E8oSpudDd_rCbZZJ);if(
mc_kk06poLCQlh5i5Yv6GSh7e!=0){(a)->mFreeFcn(a,mc_kk06poLCQlh5i5Yv6GSh7e);}};}
static McLinearAlgebraStatus mc__Z08wvCXftWEXahxEMZd8Z(const
McLinearAlgebraFactory*mc__RtkHrrPEelBbDRCt5cBnV,McLinearAlgebra**
mc_kUiN9yDkl4dshyxp7WLjGd,const PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,
size_t mc_VLfhtrJkZcWwhmTdEnSnSd){PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z=
pm_default_allocator();McLinearAlgebra*mc__0xU0_E8oSpudDd_rCbZZJ=(
McLinearAlgebra*)((mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((
mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(McLinearAlgebra)),(1)));
McLinearAlgebraStatus mc__1Zf2IciMRCub1vvbEr1C4;mc__0xU0_E8oSpudDd_rCbZZJ->
mPrivateData=mc__ulKzZm5hA4T_iKGnjQqKP(mc_FOGg0ZWot2WdYenO8zaD4Z,
mc__srK5LmyWw42ZyPnbOWDWJ);mc__0xU0_E8oSpudDd_rCbZZJ->mFactor= &
mc_V1Vtk_gaIwh3jaiP_3PXR1;mc__0xU0_E8oSpudDd_rCbZZJ->mSolve= &
mc_Fx9aOJ297s81beemiWtnqk;mc__0xU0_E8oSpudDd_rCbZZJ->mCondest= &
mc__7lK9ae7wh4FaqcvPXOkmP;mc__0xU0_E8oSpudDd_rCbZZJ->mMemusage= &
mc_VGmBkzO1j_dIZeqsL_k1be;mc__0xU0_E8oSpudDd_rCbZZJ->mDestructor= &
mc_k6o6JP_J9XplV9_1iX7wE_;(void)mc_VLfhtrJkZcWwhmTdEnSnSd;
mc__1Zf2IciMRCub1vvbEr1C4=mc_FEFvzQu07uh9emxE6Ymze_(mc__0xU0_E8oSpudDd_rCbZZJ)
;if(mc__1Zf2IciMRCub1vvbEr1C4!=MC_LA_OK){return mc__1Zf2IciMRCub1vvbEr1C4;}*
mc_kUiN9yDkl4dshyxp7WLjGd=mc__0xU0_E8oSpudDd_rCbZZJ;return MC_LA_OK;}static
McLinearAlgebraStatus mc_Vo48j9RNy3W8ZHORaUE7tD(const McLinearAlgebraFactory*
mc__RtkHrrPEelBbDRCt5cBnV,McLinearAlgebra**mc_kUiN9yDkl4dshyxp7WLjGd,const
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ){return mc__Z08wvCXftWEXahxEMZd8Z(
mc__RtkHrrPEelBbDRCt5cBnV,mc_kUiN9yDkl4dshyxp7WLjGd,mc__srK5LmyWw42ZyPnbOWDWJ,
mc__srK5LmyWw42ZyPnbOWDWJ->mNumCol);}const McLinearAlgebraFactory*
mc_VstO7CZHJVG7WD56o3ixZG(void){static McLinearAlgebraFactory
mc__RtkHrrPEelBbDRCt5cBnV;mc__RtkHrrPEelBbDRCt5cBnV.mCreateLinearAlgebra= &
mc_Vo48j9RNy3W8ZHORaUE7tD;mc__RtkHrrPEelBbDRCt5cBnV.
mCreateLinearAlgebraComplete= &mc__Z08wvCXftWEXahxEMZd8Z;return&
mc__RtkHrrPEelBbDRCt5cBnV;}
