#include "pm_std.h"
#include "pm_std.h"
#include "mc_std.h"
#include "mc_std.h"
#include "pm_std.h"
#include "mc_std.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(const void*mc_kDRphcAfRHSbf1ZLKEDW9k,const PmRealVector*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;const void*(*mc_FXz9GdGvpOKnh5e2dYstBe)(const McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(const void*
mc_kDRphcAfRHSbf1ZLKEDW9k,const PmIntVector*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);const void*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(const McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mc_VYGWBho6N1K_eyHOMGjDiW)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};
typedef struct mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct
McMatrixFunctionTag{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;const
PmSparsityPattern*mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(
const void*mc_kDRphcAfRHSbf1ZLKEDW9k,const PmRealVector*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK)
;const void*(*mc_FXz9GdGvpOKnh5e2dYstBe)(const McMatrixFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(McMatrixFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction*mc_VFkC9AaEVrlmYP4lekulJc(
McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,size_t mc_koTnVQPoiHKUVqSlx02XCo,
size_t mc__qpLUih7nC_7ZiVYAXGxkt,size_t mc__PoeG4dlGIh2XmzNaw4T3V,size_t
mc_krpd8KjzFc0aVPkyYXb1ry,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,size_t
pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(const PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(const
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_klSR73f0rO4LhXVlV6gmb7(real_T*
mc_FkvBQdfnWOCY_uJC_r4riI,const PmSparsityPattern*mc__z_znac6SDtIeyvo_HaL8F,
const real_T*mc_F2l4p_g4sn02huHNflQjMH,const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI);void mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*
mc_VO4ezo9C6qdUWq1Fln4EVt,PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);
PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const
PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__qAqv2Z2m7K0VPPGKiCpwD(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const
PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(const PmSparsityPattern*b,const
PmBoolVector*mc_F8fT7naL9bOcimTADCVzTC,const PmBoolVector*
pm_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(const PmRealVector*mc_k5z61obNZCWCbyygZn_fdK,const
real_T*mc__uV9GcaXWFlx_5jfPip5Mo,const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const
PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(const PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(const
PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,size_t mc_Fxvltms7Im4baT5ZPxj7f2,
size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_Fzylow9cnZxIhyL1O9nM0I(const PmRealVector*mc_VIutEr_JmfWNeDyKonnHVk,const
PmRealVector*mc_VW_HqYZElHCjWHwd6Iv4ON,const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t
mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1);void mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,size_t n);void mc_kNxwVTI76g4kj9P52yKhA5(
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n);PmSparsityPattern*
mc_kNYMmfXA1XtHcmiWCr7l_C(const PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc_VJlBwQnSeLpciXVTLb_llB(const PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__5C6m_ZyP9_NYekcJCEULM(const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(const PmRealVector*
mc_kuYGZlr6GiOSeqresCsPcM,const PmSparsityPattern*mc__ILFYYSbi7hW_uYs_eHsRR,
const PmRealVector*mc_FmeGGSq6P2_Kg9j7twxwci,const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,const PmRealVector*mc_FQSQWg_QFOKIWm9DWdLQR6,const
PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,const PmRealVector*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kyCwDjPxmBGRiTH73vrjJL(const
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,const PmSparsityPattern*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__tyTSVoY7fpafmg4sUl1P3(const PmRealVector*mc_kuYGZlr6GiOSeqresCsPcM,const
PmSparsityPattern*mc__ILFYYSbi7hW_uYs_eHsRR,const PmRealVector*
mc_FmeGGSq6P2_Kg9j7twxwci,const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmRealVector*mc_FQSQWg_QFOKIWm9DWdLQR6,const PmSparsityPattern*
mc_VLr_Ia18P_8icXM9WFOfYI,const PmRealVector*mc_krOJvR5Qa1KQZu3eEsQtEU);
PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(const PmSparsityPattern*a,const
PmSparsityPattern*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);struct
mc_kIf5GUUnTAOChauG3_6hhe{McMatrixFunction*mc__USnqp0SAEKYjeS1ao3_Rv;
PmSparsityPattern*mc_VxEE_OIb7JOHYqKMUI_xtV;PmAllocator*
mc_Ff9S1xA4Ip4ZXeljM4_eEa;};static void mc_knCLjJsW4L0lc1yUTzcqYO(const void*
mc_kDRphcAfRHSbf1ZLKEDW9k,const PmRealVector*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK){(*((
mc__d1alWYexptL_X5HTFhbNK->mc__USnqp0SAEKYjeS1ao3_Rv)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc_kDRphcAfRHSbf1ZLKEDW9k),(
mc_VgqbsB_3R4GTjLQeEYi1Qc),((mc__d1alWYexptL_X5HTFhbNK->
mc__USnqp0SAEKYjeS1ao3_Rv)->mc_ko6_hiERTRldgDROOJBQCH));}static const void*
mc_Fg4kZBgZ5rx0i91NQfnyze(const McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ){
return(mc_k0CXwzVaibdnZiGUCx6PMZ->mc_ko6_hiERTRldgDROOJBQCH->
mc__USnqp0SAEKYjeS1ao3_Rv)->mc_FXz9GdGvpOKnh5e2dYstBe((
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_ko6_hiERTRldgDROOJBQCH->
mc__USnqp0SAEKYjeS1ao3_Rv));}static void mc_VMJhsT78kRC5jiUos6haTa(
McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ){mc_k3jb_ssG91tZa9bwLjlWEj*
mc__d1alWYexptL_X5HTFhbNK=mc_k0CXwzVaibdnZiGUCx6PMZ->mc_ko6_hiERTRldgDROOJBQCH
;PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=mc__d1alWYexptL_X5HTFhbNK->
mc_Ff9S1xA4Ip4ZXeljM4_eEa;(mc__d1alWYexptL_X5HTFhbNK->
mc__USnqp0SAEKYjeS1ao3_Rv)->mc_VYGWBho6N1K_eyHOMGjDiW(
mc__d1alWYexptL_X5HTFhbNK->mc__USnqp0SAEKYjeS1ao3_Rv);
pm_VYooJBURCwKrVu6RXzQZ_5(mc__d1alWYexptL_X5HTFhbNK->mc_VxEE_OIb7JOHYqKMUI_xtV
,pm_FbYb_iLqY2hwZTVlVaiqJY);{void*mc_kk06poLCQlh5i5Yv6GSh7e=(
mc__d1alWYexptL_X5HTFhbNK);if(mc_kk06poLCQlh5i5Yv6GSh7e!=0){(
pm_FbYb_iLqY2hwZTVlVaiqJY)->mFreeFcn(pm_FbYb_iLqY2hwZTVlVaiqJY,
mc_kk06poLCQlh5i5Yv6GSh7e);}};{void*mc_kk06poLCQlh5i5Yv6GSh7e=(
mc_k0CXwzVaibdnZiGUCx6PMZ);if(mc_kk06poLCQlh5i5Yv6GSh7e!=0){(
pm_FbYb_iLqY2hwZTVlVaiqJY)->mFreeFcn(pm_FbYb_iLqY2hwZTVlVaiqJY,
mc_kk06poLCQlh5i5Yv6GSh7e);}};}McMatrixFunction*mc_VFkC9AaEVrlmYP4lekulJc(
McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,size_t mc_koTnVQPoiHKUVqSlx02XCo,
size_t mc__qpLUih7nC_7ZiVYAXGxkt,size_t mc__PoeG4dlGIh2XmzNaw4T3V,size_t
mc_krpd8KjzFc0aVPkyYXb1ry,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){
McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ=(McMatrixFunction*)((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
McMatrixFunction)),(1)));mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK=(
mc_k3jb_ssG91tZa9bwLjlWEj*)((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc_k3jb_ssG91tZa9bwLjlWEj)),(1)));
PmSparsityPattern*mc_Fk2O4u6vQUpibmbv8Kjgnn=NULL;mc__d1alWYexptL_X5HTFhbNK->
mc__USnqp0SAEKYjeS1ao3_Rv=mc_kXwHswK956KEimdoHimdrb;mc_Fk2O4u6vQUpibmbv8Kjgnn=
mc_kNYMmfXA1XtHcmiWCr7l_C(mc_kXwHswK956KEimdoHimdrb->mc_kjWUPQN_Ui4d_enzFJIsF_
,mc__PoeG4dlGIh2XmzNaw4T3V,pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__d1alWYexptL_X5HTFhbNK->mc_VxEE_OIb7JOHYqKMUI_xtV=mc_VJlBwQnSeLpciXVTLb_llB
(mc_Fk2O4u6vQUpibmbv8Kjgnn,mc_krpd8KjzFc0aVPkyYXb1ry,pm_FbYb_iLqY2hwZTVlVaiqJY
);pm_VYooJBURCwKrVu6RXzQZ_5(mc_Fk2O4u6vQUpibmbv8Kjgnn,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc_FY8ifnDZsXphdqo3UGrtOk(mc__d1alWYexptL_X5HTFhbNK
->mc_VxEE_OIb7JOHYqKMUI_xtV,mc_koTnVQPoiHKUVqSlx02XCo);
mc_kNxwVTI76g4kj9P52yKhA5(mc__d1alWYexptL_X5HTFhbNK->mc_VxEE_OIb7JOHYqKMUI_xtV
,mc__qpLUih7nC_7ZiVYAXGxkt);mc__d1alWYexptL_X5HTFhbNK->
mc_Ff9S1xA4Ip4ZXeljM4_eEa=pm_FbYb_iLqY2hwZTVlVaiqJY;mc_k0CXwzVaibdnZiGUCx6PMZ
->mc_ko6_hiERTRldgDROOJBQCH=mc__d1alWYexptL_X5HTFhbNK;
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_kjWUPQN_Ui4d_enzFJIsF_=mc__d1alWYexptL_X5HTFhbNK
->mc_VxEE_OIb7JOHYqKMUI_xtV;mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_VAvAkWmhpT_WWme_3E1U91= &mc_knCLjJsW4L0lc1yUTzcqYO;
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_FXz9GdGvpOKnh5e2dYstBe= &
mc_Fg4kZBgZ5rx0i91NQfnyze;mc_k0CXwzVaibdnZiGUCx6PMZ->mc_VYGWBho6N1K_eyHOMGjDiW
= &mc_VMJhsT78kRC5jiUos6haTa;return mc_k0CXwzVaibdnZiGUCx6PMZ;}
