#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
void ssc_core__iidYZ4BYP_PjX5JZknJVI(real_T ssc_core_Va6pQIuhOYhUWuCezCFrRy,
real_T ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,
real_T*mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*ssc_core_kxXUtLdQo2hYZaSu_qhot3);void
ssc_core_FrSEQFBq28SaWiGfpVZwav(real_T ssc_core__J04yncaH90DXHzyG0hSm2,real_T
ssc_core_V1YgAr3atRObWulPGeoQrC,real_T ssc_core_Va6pQIuhOYhUWuCezCFrRy,real_T
ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*
mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*ssc_core_kxXUtLdQo2hYZaSu_qhot3);void
ssc_core__6TSrGdfXtxLbXc3mviqDL(real_T ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T
ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T
ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*
mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*ssc_core_kxXUtLdQo2hYZaSu_qhot3);void
ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(real_T ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T
ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T ssc_core_kxEENIdWfPSaZDyic0CcaO,real_T
ssc_core__Hi10z5HjzpmfeY11NOEhD,real_T ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T
ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*
mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*ssc_core_kxXUtLdQo2hYZaSu_qhot3);
#include "pm_std.h"
#include "pm_std.h"
void ssc_core__iidYZ4BYP_PjX5JZknJVI(real_T ssc_core_Va6pQIuhOYhUWuCezCFrRy,
real_T ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,
real_T*mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*ssc_core_FvV_QvokIEhz_D_P3Ewwdl){(void
)ssc_core_Va6pQIuhOYhUWuCezCFrRy;(void)ssc_core__1eAP9V6_J_NYm_1gTIm7A;*
mc_VgJW5ZqpwPpuY1inYtaofQ=ssc_core_FxxpkhdCrI0Vc5cOy7vUAj;*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl=0.0;}void ssc_core_FrSEQFBq28SaWiGfpVZwav(
real_T ssc_core__J04yncaH90DXHzyG0hSm2,real_T ssc_core_V1YgAr3atRObWulPGeoQrC,
real_T ssc_core_Va6pQIuhOYhUWuCezCFrRy,real_T ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,
real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*mc_VgJW5ZqpwPpuY1inYtaofQ,real_T
*ssc_core_FvV_QvokIEhz_D_P3Ewwdl){;if(ssc_core__J04yncaH90DXHzyG0hSm2==
ssc_core_Va6pQIuhOYhUWuCezCFrRy){*mc_VgJW5ZqpwPpuY1inYtaofQ=
ssc_core_FxxpkhdCrI0Vc5cOy7vUAj;*ssc_core_FvV_QvokIEhz_D_P3Ewwdl=(*
mc_VgJW5ZqpwPpuY1inYtaofQ-ssc_core_V1YgAr3atRObWulPGeoQrC)/(
ssc_core__1eAP9V6_J_NYm_1gTIm7A-ssc_core__J04yncaH90DXHzyG0hSm2);}else{*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl=(ssc_core_FxxpkhdCrI0Vc5cOy7vUAj-
ssc_core_V1YgAr3atRObWulPGeoQrC)/(ssc_core_Va6pQIuhOYhUWuCezCFrRy-
ssc_core__J04yncaH90DXHzyG0hSm2);*mc_VgJW5ZqpwPpuY1inYtaofQ=
ssc_core_FxxpkhdCrI0Vc5cOy7vUAj+(ssc_core__1eAP9V6_J_NYm_1gTIm7A-
ssc_core_Va6pQIuhOYhUWuCezCFrRy)*(*ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}}void
ssc_core__6TSrGdfXtxLbXc3mviqDL(real_T ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T
ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T
ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*
mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*ssc_core_FvV_QvokIEhz_D_P3Ewwdl){;*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl=(ssc_core_k_QudKxoYxxwbHSi_v2Byq-
ssc_core_VdcD6u7f_kdPVe9Fz7gaKU)/(ssc_core_VWkG9DXg_ahbc1nka0X4Y9-
ssc_core_VyvvmXk1hAC_byXba4Mz7O);*mc_VgJW5ZqpwPpuY1inYtaofQ=
ssc_core_VdcD6u7f_kdPVe9Fz7gaKU+(ssc_core__1eAP9V6_J_NYm_1gTIm7A-
ssc_core_VyvvmXk1hAC_byXba4Mz7O)*(*ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}void
ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(real_T ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T
ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T ssc_core_kxEENIdWfPSaZDyic0CcaO,real_T
ssc_core__Hi10z5HjzpmfeY11NOEhD,real_T ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T
ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*
mc_VgJW5ZqpwPpuY1inYtaofQ,real_T*ssc_core_FvV_QvokIEhz_D_P3Ewwdl){;;*
mc_VgJW5ZqpwPpuY1inYtaofQ=ssc_core__Hi10z5HjzpmfeY11NOEhD;;*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl=(ssc_core_k_QudKxoYxxwbHSi_v2Byq-
ssc_core_VdcD6u7f_kdPVe9Fz7gaKU)/(ssc_core_VWkG9DXg_ahbc1nka0X4Y9-
ssc_core_VyvvmXk1hAC_byXba4Mz7O);}
