#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_FKc4tYGyO_p9beWwzb0Juo ssc_core_VDysZoxgYghwhXU1UYlmqx
;typedef struct ssc_core_Vfl7BS81ZAhV_5X2IQkzLW ssc_core_FNHwFizq1kxdVitsK9pEgv
;typedef enum{ssc_core_kMjk_uBRCutvWLcqcDYpL9= -1,
ssc_core_F7EYiSWVXlWmiu8kF9ezb_,ssc_core_k_4kEXoVHrtgcq_OGAKG2o,
ssc_core_F_OzpLs2M_pd_yHKAnv0fa}ssc_core__f_yrOvY5jpMci6b_XXvT0;typedef struct
ssc_core_kemRd3LD2_pPVaAsNA5YDG ssc_core_VVipzh2oIBtKZ5hNqD2z_1;typedef struct
ssc_core_VAZekvvzo5CUcm0GE7lD8S ssc_core_FdhjQ_x6uEtWf5NrhiXPkC;struct
ssc_core_kemRd3LD2_pPVaAsNA5YDG{ssc_core_FdhjQ_x6uEtWf5NrhiXPkC*mPrivateData;
void(*mc_kt9hW2swhpxchivzz5BlCP)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv,ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ);ssc_core_VDysZoxgYghwhXU1UYlmqx*(*
ssc_core__ncbpuIDzMOrgqwrOKx4qs)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv);ssc_core_VDysZoxgYghwhXU1UYlmqx*(*
ssc_core_kQPAw1xwSVSbhTWPocMRHj)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv);ssc_core_VDysZoxgYghwhXU1UYlmqx*(*
ssc_core_FWUr7cMI27_XXuAo82pt8h)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv,size_t n);size_t(*
ssc_core_FRrT3ZKfnZCQ_TCtuEK5hH)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*ssc_core__pLwoU6jmvWSV9dXhEIoIv);};
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*ssc_core_F__qZQpW_J4sVP_0nua696(PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z);
#include "pm_std.h"
#include "string.h"
struct ssc_core_VAZekvvzo5CUcm0GE7lD8S{PmAllocator*
ssc_core_FyUeLiATLG4zWes0mMKZnu;size_t ssc_core_kJKIiuWImf8dg9pI3f8pc5;size_t
ssc_core__VyGPUhHOUGr_9l0UciNgg;ssc_core_VDysZoxgYghwhXU1UYlmqx**
ssc_core__3742BpjxzxJjmXriotnZ8;};static void ssc_core_F4H5qzX7P1tfjHMzM48Nuh(
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*mc_FawmFe5oOEC_cmkvZc1Kaa,
ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core_kBj0wT0jErl0hDNP9N5QnJ){if(
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__VyGPUhHOUGr_9l0UciNgg>=
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core_kJKIiuWImf8dg9pI3f8pc5){
ssc_core_VDysZoxgYghwhXU1UYlmqx**ssc_core__0Gxic3Bpu_HjDevqjQi0l=
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__3742BpjxzxJjmXriotnZ8;;
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core_kJKIiuWImf8dg9pI3f8pc5*=2;
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__3742BpjxzxJjmXriotnZ8=(
ssc_core_VDysZoxgYghwhXU1UYlmqx**)((mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core_FyUeLiATLG4zWes0mMKZnu)->mCallocFcn((mc_FawmFe5oOEC_cmkvZc1Kaa->
mPrivateData->ssc_core_FyUeLiATLG4zWes0mMKZnu),(sizeof(
ssc_core_VDysZoxgYghwhXU1UYlmqx*)),(mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core_kJKIiuWImf8dg9pI3f8pc5)));memcpy(mc_FawmFe5oOEC_cmkvZc1Kaa->
mPrivateData->ssc_core__3742BpjxzxJjmXriotnZ8,ssc_core__0Gxic3Bpu_HjDevqjQi0l,
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__VyGPUhHOUGr_9l0UciNgg*
sizeof(ssc_core_VDysZoxgYghwhXU1UYlmqx*));{void*
ssc_core_kk06poLCQlh5i5Yv6GSh7e=(ssc_core__0Gxic3Bpu_HjDevqjQi0l);if(
ssc_core_kk06poLCQlh5i5Yv6GSh7e!=0){(mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core_FyUeLiATLG4zWes0mMKZnu)->mFreeFcn(mc_FawmFe5oOEC_cmkvZc1Kaa->
mPrivateData->ssc_core_FyUeLiATLG4zWes0mMKZnu,ssc_core_kk06poLCQlh5i5Yv6GSh7e)
;}};};mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__3742BpjxzxJjmXriotnZ8
[(mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__VyGPUhHOUGr_9l0UciNgg)++]
=ssc_core_kBj0wT0jErl0hDNP9N5QnJ;}static ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_FEzS7XssJml9ViYnKxc76R(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
mc_FawmFe5oOEC_cmkvZc1Kaa){;;return mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core__3742BpjxzxJjmXriotnZ8[--(mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core__VyGPUhHOUGr_9l0UciNgg)];}static ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kJcxrUYoNIC5am6xkTcdUO(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
mc_FawmFe5oOEC_cmkvZc1Kaa,size_t ssc_core_V2__YrimeI4E_yWnhKofpy){;;return
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__3742BpjxzxJjmXriotnZ8[
ssc_core_V2__YrimeI4E_yWnhKofpy];}static ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core__rZ5DLvGFchqiLdMql401t(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
mc_FawmFe5oOEC_cmkvZc1Kaa){size_t n=mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core__VyGPUhHOUGr_9l0UciNgg;if(n>0){return ssc_core_kJcxrUYoNIC5am6xkTcdUO
(mc_FawmFe5oOEC_cmkvZc1Kaa,n-1);}else{return NULL;}}static size_t
ssc_core_VgMqsX7mTCCv_atfRHMVFp(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
mc_FawmFe5oOEC_cmkvZc1Kaa){return mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core__VyGPUhHOUGr_9l0UciNgg;}static void ssc_core_FfoRLAEATm0bZ53YlcsbRa(
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*mc_FawmFe5oOEC_cmkvZc1Kaa){PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z=mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->
ssc_core_FyUeLiATLG4zWes0mMKZnu;{void*ssc_core_kk06poLCQlh5i5Yv6GSh7e=(
mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData->ssc_core__3742BpjxzxJjmXriotnZ8);if(
ssc_core_kk06poLCQlh5i5Yv6GSh7e!=0){(mc_FOGg0ZWot2WdYenO8zaD4Z)->mFreeFcn(
mc_FOGg0ZWot2WdYenO8zaD4Z,ssc_core_kk06poLCQlh5i5Yv6GSh7e);}};{void*
ssc_core_kk06poLCQlh5i5Yv6GSh7e=(mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData);if(
ssc_core_kk06poLCQlh5i5Yv6GSh7e!=0){(mc_FOGg0ZWot2WdYenO8zaD4Z)->mFreeFcn(
mc_FOGg0ZWot2WdYenO8zaD4Z,ssc_core_kk06poLCQlh5i5Yv6GSh7e);}};{void*
ssc_core_kk06poLCQlh5i5Yv6GSh7e=(mc_FawmFe5oOEC_cmkvZc1Kaa);if(
ssc_core_kk06poLCQlh5i5Yv6GSh7e!=0){(mc_FOGg0ZWot2WdYenO8zaD4Z)->mFreeFcn(
mc_FOGg0ZWot2WdYenO8zaD4Z,ssc_core_kk06poLCQlh5i5Yv6GSh7e);}};}
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*ssc_core_F__qZQpW_J4sVP_0nua696(PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z){ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
mc_FawmFe5oOEC_cmkvZc1Kaa=(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*)((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core_VVipzh2oIBtKZ5hNqD2z_1)),(1)));ssc_core_FdhjQ_x6uEtWf5NrhiXPkC*
mc__d1alWYexptL_X5HTFhbNK=(ssc_core_FdhjQ_x6uEtWf5NrhiXPkC*)((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core_FdhjQ_x6uEtWf5NrhiXPkC)),(1)));const size_t
ssc_core_k_XtCql81Q4tVa9W_jwdyw=5;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FyUeLiATLG4zWes0mMKZnu=mc_FOGg0ZWot2WdYenO8zaD4Z;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kJKIiuWImf8dg9pI3f8pc5=
ssc_core_k_XtCql81Q4tVa9W_jwdyw;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__VyGPUhHOUGr_9l0UciNgg=0;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__3742BpjxzxJjmXriotnZ8=(ssc_core_VDysZoxgYghwhXU1UYlmqx**)((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core_VDysZoxgYghwhXU1UYlmqx*)),(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kJKIiuWImf8dg9pI3f8pc5)));mc_FawmFe5oOEC_cmkvZc1Kaa->mPrivateData=
mc__d1alWYexptL_X5HTFhbNK;mc_FawmFe5oOEC_cmkvZc1Kaa->mc_kt9hW2swhpxchivzz5BlCP
= &ssc_core_F4H5qzX7P1tfjHMzM48Nuh;mc_FawmFe5oOEC_cmkvZc1Kaa->
ssc_core__ncbpuIDzMOrgqwrOKx4qs= &ssc_core_FEzS7XssJml9ViYnKxc76R;
mc_FawmFe5oOEC_cmkvZc1Kaa->ssc_core_kQPAw1xwSVSbhTWPocMRHj= &
ssc_core__rZ5DLvGFchqiLdMql401t;mc_FawmFe5oOEC_cmkvZc1Kaa->
ssc_core_FWUr7cMI27_XXuAo82pt8h= &ssc_core_kJcxrUYoNIC5am6xkTcdUO;
mc_FawmFe5oOEC_cmkvZc1Kaa->ssc_core_FRrT3ZKfnZCQ_TCtuEK5hH= &
ssc_core_VgMqsX7mTCCv_atfRHMVFp;mc_FawmFe5oOEC_cmkvZc1Kaa->
mc_VYGWBho6N1K_eyHOMGjDiW= &ssc_core_FfoRLAEATm0bZ53YlcsbRa;return
mc_FawmFe5oOEC_cmkvZc1Kaa;}
