#include "pm_std.h"
#include "pm_std.h"
#include "mc_std.h"
#include "mc_std.h"
typedef struct mc_kJQpD6ZhgVtiVmhXkjr8JY{PmSparsityPattern*
mc_krPFDE3HuNG9jP3UefXVXY;PmRealVector*mc_kDnTh4B6n6xuca3dKua_H9;
PmSparsityPattern*mc_kP9WB_4RortueyfaDBlnXM;PmRealVector*
mc__kn7XECBqbdPimCJ8iD1Kp;PmIntVector*mc_FjDIs2zMLtx5We_IND4g6I;}
mc_FBFzHfrmEc41ji0CQOA38T;mc_FBFzHfrmEc41ji0CQOA38T*mc_FRabik2L6bCWXXz1LyK_Ze(
const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,const PmRealVector*
mc_V8ujEMKrDU8Q_mvu4yja1b);void mc__Qbr2NKiXB0XdqkBcqyU6q(
mc_FBFzHfrmEc41ji0CQOA38T*mc_k97GnLAArQWibunVaBx_Ol);void
mc_FHLECAsrw4SbaauHCK0H0z(const PmSparsityPattern*mc_FNLG4N0Qc3OxdmBVwutDsy,
const PmRealVector*mc_VlnhKi82gfCLgumIqeduOq,const PmRealVector*b,const
PmRealVector*x);void mc_FQDXPJI_fEdac1lJmv32Pw(const PmSparsityPattern*
mc_FNLG4N0Qc3OxdmBVwutDsy,const PmRealVector*mc_VlnhKi82gfCLgumIqeduOq,const
PmRealVector*b,const PmRealVector*x);
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(const PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_rv_equals_rv(const PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
pm_VeeoZXnlJQ4u_112lGs8YD(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_kpDvbw1GUlp4c5YdnW7V_w(const
PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(const PmCharVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmCharVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_FltUsml2sTlHZuCkbw_pdM(const PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(const PmIntVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmRealVector*pm_V_q_QnwoVVl6fHS_0pLvYo(const PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_VeffaD_A8DxagH31Usec1H(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_real_vector(PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_int_vector_fields(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm_create_int_vector(size_t
pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*
pm__fSS_VMqhWlobeqe6mQF_x(const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_V_eFnKjg5I4Uc1DwG4yU27(
PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_int_vector(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_bool_vector_fields(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmBoolVector*pm__jbisDMumXdocXANx5LhhY(size_t pm__c6Ltywqrrtqii4hsDTKgz,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_kia_QXK77_xDg9M1NzHr3r(
PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm_kpRdzyG9L_8MV5lRovACCg(
const PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(PmCharVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t pm__c6Ltywqrrtqii4hsDTKgz,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VH4is_vKxDpFiupATTqV_4(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_FaBQ30lWObWMi1zpzQ_EZG(
PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSizeVector*pm_FZch3YyGWrOM_PQNdo7b2c(size_t
pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FJsPJplguVOI_1EYyUUvfK(const PmSizeVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmSizeVector*pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(
const PmSizeVector*pm__hARyx1bZBxVj1boVQqdtV,const PmSizeVector*
pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_VgM3Lx3pYgtLW13T1_txvP(const PmBoolVector
*mc_VgJW5ZqpwPpuY1inYtaofQ);void mc_F4xMxEJX_DlUYXuaiDuSWS(const PmIntVector*
mc_kyVj_uOQd__gg9_ljlZ_IY,const PmRealVector*x,const PmRealVector*
mc_FfDTppU8N_tOWuLK37x_08);void mc_kQso3OAQDyxZaX0RF40IyE(const PmIntVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF,const
PmIntVector*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF,const PmIntVector*mc_F2Ry_cv60wK5bmHWC_sU4g);void
mc_V5jydIk5QzCRZTOycShqTL(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV);void
mc_FvLmE29WKCKJfaZMHwg3g9(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const
int32_T mc_kh0AzKGHcX8tfeDoNul_TU,const int32_T mc__Oliq0seKPWShTNRpvAarb);
void mc__pmVtsSuXZls_1NfvVprZ7(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,
const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF,const PmBoolVector*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(const PmIntVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(const PmIntVector*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T mc_kg4CyRgbu6OdeewZOel7Qx);void
mc_kB1aHs1BVHG5YHNpmLLvkW(const PmBoolVector*mc_FrF2gTbWxox8geiSROFaFn,const
PmBoolVector*mc_VwOeyeOYCKdcVTySJQVoLE,const PmIntVector*
mc__vpsWwfj3fx1YDJlP_lHTd);void mc_V2P87Xoe0TGNeXNcn27vUJ(const PmBoolVector*
mc_VRbT1WwZjwW6f5YGBCFuaD,size_t mc_FnrjFNs9eQp9V5vCxPaoKw,const PmBoolVector*
mc__d7LC10lP38OY1VXN_tFqb,size_t mc_FRuIUemzxbdhfqkjXhoyK7,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VqP4HesDIf47bDn5teE2H2(const PmRealVector*
mc_VRbT1WwZjwW6f5YGBCFuaD,size_t mc_FnrjFNs9eQp9V5vCxPaoKw,const PmRealVector*
mc__d7LC10lP38OY1VXN_tFqb,size_t mc_FRuIUemzxbdhfqkjXhoyK7,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);size_t
mc_FLTxr_Wc1PKSeTxwfrcl5B(const PmBoolVector*mc__MqKyOds56_XeH9Iv3CTIL);void
mc_FX5UXdAa2flS_1wrwznTLh(const PmIntVector*mc__vpsWwfj3fx1YDJlP_lHTd,const
PmBoolVector*mc_VwOeyeOYCKdcVTySJQVoLE);size_t mc__RsEbvPhcXp6iqwYpH_OQY(const
PmIntVector*mc_F6sy5cXK8JOKeiFBw6znSV);size_t mc__fQVSVSgEBG6fuximVFlkw(const
PmRealVector*mc_FawmFe5oOEC_cmkvZc1Kaa);size_t mc_FyLahU0kjICfba8O7mWi8Z(const
PmBoolVector*mc_FawmFe5oOEC_cmkvZc1Kaa);boolean_T mc___gjB_jZtTxReaWZSEiFdh(
const PmIntVector*mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T
mc_kNrn2e3NmaGNbmzmXpvCR0(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,int32_T
mc_kg4CyRgbu6OdeewZOel7Qx);boolean_T mc_kk65_VI6zC0mWHqRziXpjX(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,real_T mc_kg4CyRgbu6OdeewZOel7Qx);void
mc_FGkd8Riw6p4eaDCAbwBVPv(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FzkrLuS4xMOvaTv5dUw3j7(const
PmRealVector*x,real_T mc_VgJW5ZqpwPpuY1inYtaofQ);void mc_ks_PW4I7dwWbhXAWhHTUCI
(const PmRealVector*x,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL);void
mc__w_RD4J1MZlqcL7as8FLdk(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,real_T a,const PmRealVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(const PmRealVector*x
,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL,const PmRealVector*
mc_FBDi_PCg670TjHgJTNPcHr);void mc_VWnvos7Q548uVH7p0208jN(const PmRealVector*x
,const real_T a,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL);void
mc_V7hiVZfxKK0Uj9rPai4LYw(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
real_T mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const real_T mc_kcda_aHAM4WIXuM_xBDdLt)
;void mc_k4v_yYmXHgO1cqVdr5a500(const PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,
const PmIntVector*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(const PmRealVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(const PmRealVector*mc_VcZASgthsTt6dul8DlRWaw,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(const PmBoolVector*
mc_VcZASgthsTt6dul8DlRWaw);void mc__aNO1s5qwzt6fXwft5YgCz(const PmRealVector*
mc_VcZASgthsTt6dul8DlRWaw);void mc_VTlukZ0iimdzge7aTGg7rl(const PmIntVector*
mc_VcZASgthsTt6dul8DlRWaw,int32_T mc_kg4CyRgbu6OdeewZOel7Qx);void
mc_VDWYuA0FfQClgukbQcp3js(const PmIntVector*mc_VcZASgthsTt6dul8DlRWaw);void
mc_k9wkPuvMCi4DY1yebDQPHf(const PmIntVector*mc_VcZASgthsTt6dul8DlRWaw);void
mc__Nb_EyyxYi4ddPcS0H7Bot(const PmBoolVector*mc_kd_kJxzsgTx9W19pl4H_AH,const
PmIntVector*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt);
void mc_k1sxUtEClkOZVuHMQ91JqD(const PmBoolVector*mc_VcZASgthsTt6dul8DlRWaw,
boolean_T mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(const
PmBoolVector*mc_VcZASgthsTt6dul8DlRWaw);void mc_VQ1YWbKmkVC6YajZAyvmNH(const
PmBoolVector*x,size_t mc_kwrB3ZoKf7OufTHWaHJV7a,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(const PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(const
PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(const
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx(
const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,const PmIntVector*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,const PmRealVector*mc_V_rxJBbuhqtwViRHFKhdGC,const
PmSparsityPattern*mc__Df1hQFzAY4fiLCvP0PV12);void mc_VMRKMuNLnDxXjaBiy1RcMD(
const PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const
PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const
PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const real_T*x);void mc_kXj99iXjC1CoZLWwPRH879(const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const PmRealVector*
mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*mc_VknkCg_msB8Ga9ymQtGggf,
const PmRealVector*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(const PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,
const PmRealVector*mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF,const PmRealVector*
mc_FCZxG6Iux_GKX1lkqasXdQ,const PmSparsityPattern*mc_VknkCg_msB8Ga9ymQtGggf,
const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL,const PmRealVector*
mc_V8ujEMKrDU8Q_mvu4yja1b,const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t mc_kyp6uAyJE40UVuAQNEYzS1,real_T mc_kcda_aHAM4WIXuM_xBDdLt);void
mc__WqQP6u7DtdYVDzUK5y971(const PmRealVector*mc_FBDi_PCg670TjHgJTNPcHr,const
PmRealVector*x,const PmRealVector*mc_FzyLWRgau0pMYq2XSI3ETL);void
mc_kc89O49Oe18lWqn1Nr_t61(const PmRealVector*mc_FrF2gTbWxox8geiSROFaFn,const
PmRealVector*mc_VwOeyeOYCKdcVTySJQVoLE,const PmIntVector*
mc__sdtG1OgJQtqcikFA20Doo);void mc_F4wnJSMmz0WHaHs2tnfI5y(const PmRealVector*
mc_FrF2gTbWxox8geiSROFaFn,const PmIntVector*mc__sdtG1OgJQtqcikFA20Doo,const
PmRealVector*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(const
PmRealVector*a,const PmIntVector*mc_kwrB3ZoKf7OufTHWaHJV7a,const PmRealVector*
b);void mc_V_Fp06wJOBhXZyLbA5xU0r(const PmRealVector*a,const PmRealVector*b,
const PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a);void mc_FuY0t5xEb5_QhDQFQ_TXtc(
const PmRealVector*a,const PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,const
PmRealVector*b);void mc_kkPot0UJiN_EX94QlR_mCs(const PmRealVector*a,const
PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,real_T x);void mc_kMo1w3ReRZGIdH5_MNwumc
(const PmRealVector*a,const PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,const
PmRealVector*b);void mc_VYxtXnMKT6hpb1FMldBDLs(const PmRealVector*a,const
PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,const PmRealVector*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(const PmIntVector*a,const PmBoolVector*
mc_kwrB3ZoKf7OufTHWaHJV7a,const PmIntVector*b);void mc_FBaB5196Xx0ohX_IWM5ypL(
const PmIntVector*a,const PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,int32_T x);
void mc_F1CG0fHJYfd_ealLMx7Z7U(const PmIntVector*a,const PmBoolVector*
mc_kwrB3ZoKf7OufTHWaHJV7a,const PmIntVector*b);void mc_krXbD205SBpghif1h1n_ei(
const PmIntVector*a,const PmBoolVector*mc_kwrB3ZoKf7OufTHWaHJV7a,const
PmIntVector*b);void mc__0IkRn0eQ9Wc_u8mCNbQDh(const PmIntVector*
mc_VUELvXWGXPlKf1brR9MRC3,const PmSparsityPattern*mc_FBOWjCOBM8SyhqFe64oqrx);
void mc__pbFNjwg_bCPdPFSjC2Wdv(const PmBoolVector*mc_VUELvXWGXPlKf1brR9MRC3,
const PmSparsityPattern*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(const PmBoolVector*mc_VUELvXWGXPlKf1brR9MRC3,const
PmSparsityPattern*mc_FBOWjCOBM8SyhqFe64oqrx);void mc__pFtu1g17h8ZaaZK4PpTkb(
const PmBoolVector*mc_VUELvXWGXPlKf1brR9MRC3,const PmSparsityPattern*
mc_FBOWjCOBM8SyhqFe64oqrx);void mc_kMScbNM1RKOTaD4QwTME8Y(const PmBoolVector*
mc__1Zf2IciMRCub1vvbEr1C4,const PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,
const PmRealVector*mc_VlnhKi82gfCLgumIqeduOq);void mc_Fbsqat6MlL0bjPHlNxax8t(
const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF,const PmSparsityPattern*
mc_VknkCg_msB8Ga9ymQtGggf,const PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV);void
mc_FSAdXYnRP9pkfmWBYlMkJJ(const PmRealVector*mc_kVkvrfpzuVduaPTr5FLF8K,const
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,const PmBoolVector*
mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(const PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K,const PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,
const PmBoolVector*pm_VCVhWy_VaDhraHrlfFWxBa);PmRealVector
mc_VPFwoVShg1G3XTwou1_jbC(const PmRealVector*mc_VgJW5ZqpwPpuY1inYtaofQ,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);
#include "limits.h"
#include "math.h"
#include "stdio.h"
typedef struct mc_kJu3kbp1UqpibDtb06hKK_{int32_T mc_FIxFweA3fcKFfuFXAKfA47;
int32_T mc_VLHhnPUiNQpve5VIL9P3O9;int32_T n;int32_T*pm__lqjegyKuwStj56WZLiC_e;
int32_T*mc_kwrB3ZoKf7OufTHWaHJV7a;double*x;int32_T mc___ECRgjqShlp_PytRplerL;}
mc_F5Olyc6xUoG7ZyDq78exBD;mc_F5Olyc6xUoG7ZyDq78exBD*mc_F_KsXRscHI0GbqNNEbk0p9(
const mc_F5Olyc6xUoG7ZyDq78exBD*A,const mc_F5Olyc6xUoG7ZyDq78exBD*
mc_Vqiy96WqvuhCaXm5e_vvT0,double mc_kcda_aHAM4WIXuM_xBDdLt,double
mc_kCPCzQ_4FF88XTgtMjWqKy);int32_T mc_FRcDfQc8skGuVLZfeGfRsQ(int32_T
mc_FruBC65sPgSaZ5e_Y8cbTC,const mc_F5Olyc6xUoG7ZyDq78exBD*A,double*b);
mc_F5Olyc6xUoG7ZyDq78exBD*mc_kPZtfcLRq8hvd17AwbGSfy(const
mc_F5Olyc6xUoG7ZyDq78exBD*mc_V91rYIvDBkGRba7MvGcPUK);int32_T
mc_VufLWRyy__x0aHcAK11u_9(mc_F5Olyc6xUoG7ZyDq78exBD*A);int32_T
mc_VMB1wjlajc42dihJmzkfVL(mc_F5Olyc6xUoG7ZyDq78exBD*mc_V91rYIvDBkGRba7MvGcPUK,
int32_T mc_kwrB3ZoKf7OufTHWaHJV7a,int32_T mc_kyp6uAyJE40UVuAQNEYzS1,double x);
int32_T mc_kyNdNb1Od1pmc5h9_bRwz3(const mc_F5Olyc6xUoG7ZyDq78exBD*A,const
double*x,double*mc_FzyLWRgau0pMYq2XSI3ETL);mc_F5Olyc6xUoG7ZyDq78exBD*
mc_kKDpTzN8jw8R_La01FPHqo(FILE*mc_Fe6copTTRcKEayCm87ABO_);int32_T
mc_FBcYs04mnxCNjei3Py1gDA(int32_T mc_FruBC65sPgSaZ5e_Y8cbTC,const
mc_F5Olyc6xUoG7ZyDq78exBD*A,double*b,double mc_FfDTppU8N_tOWuLK37x_08);
mc_F5Olyc6xUoG7ZyDq78exBD*mc_F1T9nfE5YBd9_eUgmYQiFQ(const
mc_F5Olyc6xUoG7ZyDq78exBD*A,const mc_F5Olyc6xUoG7ZyDq78exBD*
mc_Vqiy96WqvuhCaXm5e_vvT0);double mc__mMjuh4GBSd2gPZyGSIEB7(const
mc_F5Olyc6xUoG7ZyDq78exBD*A);int32_T mc__Wuhz03is3hpg54E4_8dDo(const
mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T mc_kPdbGJs0Eb_x_Hxa5hZJEc);int32_T
mc_kjcu6drPCUOjbP4z73xob_(int32_T mc_FruBC65sPgSaZ5e_Y8cbTC,const
mc_F5Olyc6xUoG7ZyDq78exBD*A,double*b);mc_F5Olyc6xUoG7ZyDq78exBD*
mc_kzs_RE98zypjVHi58lxG6O(const mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T
mc_kVkvrfpzuVduaPTr5FLF8K);void*mc_VInfIQCul4ShdLlbU4F0WB(int32_T n,size_t size
);void*mc__Mim_3QMMSxfi9M5sbbxcM(void*pm__lqjegyKuwStj56WZLiC_e);void*
mc_k0mbD5QrRepqjLd_9sSyDz(void*pm__lqjegyKuwStj56WZLiC_e,int32_T n,size_t size
,int32_T*mc__suOgr_4PeCIZi_uhoSVwf);mc_F5Olyc6xUoG7ZyDq78exBD*
mc_VFJZ9bgvffCPg9PZXPkAVk(int32_T mc_VLHhnPUiNQpve5VIL9P3O9,int32_T n,int32_T
mc_FIxFweA3fcKFfuFXAKfA47,int32_T mc_kVkvrfpzuVduaPTr5FLF8K,int32_T
mc_Vk3BcXZzVaxpfi0XcV5sHr);mc_F5Olyc6xUoG7ZyDq78exBD*mc__BJ1NEDJTgOMhaJKDrM6pN
(mc_F5Olyc6xUoG7ZyDq78exBD*A);int32_T mc_VptvBjskDA83heaLThR8oY(
mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T mc_FIxFweA3fcKFfuFXAKfA47);void*
mc_ktrY1jmEuvhTfeGflVz93o(int32_T n,size_t size);int32_T
mc_Vw_wVSv6gGKFY1Dalcu6zm(const mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T
mc_kPdbGJs0Eb_x_Hxa5hZJEc);typedef struct mc__adJqrskeJhDYmBVMGWunh{int32_T*
mc_FjDIs2zMLtx5We_IND4g6I;int32_T*mc__AExROh1PVWNeP7hmMWuJv;int32_T*
mc_k6HeriBJpGdZiPlDO4UZXp;int32_T*mc_FXT4jPWj6stSWaiL5dan3b;int32_T*
mc_F_jeaQAcXwGbVXb0t9dFxz;int32_T mc_k3zUxpU0ydGajPq7EF4qn3;double
mc_ViTJrDHWLs8OjimuuiIsPe;double mc__GPciDcZ6Z0EViGxgxdf9y;}
mc_VWUvciwDK_dziLpafRxush;typedef struct mc_kp2eGzAtU2WUXP2RD6EKGO{
mc_F5Olyc6xUoG7ZyDq78exBD*mc__ut5UfJwzNlZ_XZC_yEgKo;mc_F5Olyc6xUoG7ZyDq78exBD*
mc_Vi4Cp0qK964NYTFMGr9Ttn;int32_T*mc_FjDIs2zMLtx5We_IND4g6I;double*
mc_Vqiy96WqvuhCaXm5e_vvT0;}mc_kPBB5xuFz74_aaM4N6U4Jv;typedef struct
mc__goErATdCI0HWaZaNs9Xzt{int32_T*pm__lqjegyKuwStj56WZLiC_e;int32_T*
mc__AExROh1PVWNeP7hmMWuJv;int32_T*mc_kUQBO1dSP8_IVqRAUx4R8G;int32_T*
mc_FQferGZUKft3_i5GvYy4Oy;int32_T mc_kLMRRiSdJr4aaLEtYiWmgE;int32_T
mc__ys6fNnaK541fDBqN87Aa_[5];int32_T mc_Fet2g81LNVG6_mJHNhUAfo[5];}
mc_koBw_auTeOpFWTLu_1_hd3;int32_T*mc_FAnXK3hkeY_FimobZpSWy4(int32_T
mc_FruBC65sPgSaZ5e_Y8cbTC,const mc_F5Olyc6xUoG7ZyDq78exBD*A);
mc_kPBB5xuFz74_aaM4N6U4Jv*mc_kF0bdRSgaVCZhHmbCIFdvh(const
mc_F5Olyc6xUoG7ZyDq78exBD*A,const mc_VWUvciwDK_dziLpafRxush*
mc__Q_i1Z0_CMGpfPqpuLrnMT);mc_koBw_auTeOpFWTLu_1_hd3*mc__JYcNbbJ8GxnaT0gipcMUY
(const mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T mc_k6QxQSbjWyGhcXikh7jTLf);int32_T
mc_FEBJlPSzZh_ZiqgXtpZSYe(mc_F5Olyc6xUoG7ZyDq78exBD*A,double
mc_FfDTppU8N_tOWuLK37x_08);int32_T mc_VywKLPGT27tscy1s60Ehlb(
mc_F5Olyc6xUoG7ZyDq78exBD*A);int32_T mc_ViJBWCuvxwlcXP5hTDAmft(const
mc_F5Olyc6xUoG7ZyDq78exBD*mc_kJeUz19e49pVaDwcttsZep,int32_T
mc_kwrB3ZoKf7OufTHWaHJV7a,double mc_kCPCzQ_4FF88XTgtMjWqKy,double*x);int32_T
mc_Vux1rLMHdIOwYHo_GgP0nf(const int32_T*pm__lqjegyKuwStj56WZLiC_e,const double
*b,double*x,int32_T n);int32_T mc_V3SIv4FNXnS__9UCAN4nes(const
mc_F5Olyc6xUoG7ZyDq78exBD*mc__ut5UfJwzNlZ_XZC_yEgKo,double*x);int32_T
mc__U2f_z8iKPWQZTkLMApmoB(const mc_F5Olyc6xUoG7ZyDq78exBD*
mc__ut5UfJwzNlZ_XZC_yEgKo,double*x);mc_kPBB5xuFz74_aaM4N6U4Jv*
mc__OANyqXuH__Wi5n3l9hrJe(const mc_F5Olyc6xUoG7ZyDq78exBD*A,const
mc_VWUvciwDK_dziLpafRxush*mc__Q_i1Z0_CMGpfPqpuLrnMT,double
mc_FfDTppU8N_tOWuLK37x_08);mc_kPBB5xuFz74_aaM4N6U4Jv*mc_VD2E_WGEctCGXH2bprw8Sw
(const mc_F5Olyc6xUoG7ZyDq78exBD*A,const mc_VWUvciwDK_dziLpafRxush*
mc__Q_i1Z0_CMGpfPqpuLrnMT,int32_T*mc__q70gXw8N_xsWy9UoFEkTZ);
mc_F5Olyc6xUoG7ZyDq78exBD*mc_k9MmNIu2n4W9jaO59BYYYQ(const
mc_F5Olyc6xUoG7ZyDq78exBD*A,const int32_T*pm__lqjegyKuwStj56WZLiC_e,const
int32_T*mc__AExROh1PVWNeP7hmMWuJv,int32_T mc_kVkvrfpzuVduaPTr5FLF8K);int32_T*
mc__wD389_14ZOPfyx5EQ5Eez(const int32_T*pm__lqjegyKuwStj56WZLiC_e,int32_T n);
int32_T mc_VQ7L8M0ejvGI_H70X2UUEW(const int32_T*pm__lqjegyKuwStj56WZLiC_e,
const double*b,double*x,int32_T n);mc_kPBB5xuFz74_aaM4N6U4Jv*
mc_FnFQE__lyw88fDjvIJlbiy(const mc_F5Olyc6xUoG7ZyDq78exBD*A,const
mc_VWUvciwDK_dziLpafRxush*mc__Q_i1Z0_CMGpfPqpuLrnMT);mc_VWUvciwDK_dziLpafRxush
*mc_VHjWZG2MGPlHg9FEzWcJP5(int32_T mc_FruBC65sPgSaZ5e_Y8cbTC,const
mc_F5Olyc6xUoG7ZyDq78exBD*A);mc_VWUvciwDK_dziLpafRxush*
mc__HBpzStane0GaaQtDu_y9F(int32_T mc_FruBC65sPgSaZ5e_Y8cbTC,const
mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T mc_VWCrbzOuAe4hay4E_Unnfg);
mc_F5Olyc6xUoG7ZyDq78exBD*mc_V0SSOL16_J8_aXLgyS19I7(const
mc_F5Olyc6xUoG7ZyDq78exBD*A,const int32_T*mc_FjDIs2zMLtx5We_IND4g6I,int32_T
mc_kVkvrfpzuVduaPTr5FLF8K);int32_T mc_VLrR9_1UGwSOj5Fn6W7Qqm(
mc_F5Olyc6xUoG7ZyDq78exBD*mc__ut5UfJwzNlZ_XZC_yEgKo,int32_T
mc__Gce0mZquR4HgLX8bLfI0G,const mc_F5Olyc6xUoG7ZyDq78exBD*
mc_FStFcQlyAJ_dVy4kGZXBPQ,const int32_T*mc_k6HeriBJpGdZiPlDO4UZXp);int32_T
mc_kX6eNI2bFZ__cyLxZQzP6Z(const mc_F5Olyc6xUoG7ZyDq78exBD*
mc_Vi4Cp0qK964NYTFMGr9Ttn,double*x);int32_T mc_FRCJeuT32S4AW5Dz6aeK7v(const
mc_F5Olyc6xUoG7ZyDq78exBD*mc_Vi4Cp0qK964NYTFMGr9Ttn,double*x);
mc_VWUvciwDK_dziLpafRxush*mc_Fe3WdhVNm1lm_TputcgM_w(mc_VWUvciwDK_dziLpafRxush*
mc__Q_i1Z0_CMGpfPqpuLrnMT);mc_kPBB5xuFz74_aaM4N6U4Jv*mc_VZ5qqYWDqx_NaqOx3T8EeD
(mc_kPBB5xuFz74_aaM4N6U4Jv*mc_F3nVSXkoDK8VeeL5OmY0_B);
mc_koBw_auTeOpFWTLu_1_hd3*mc_kqyKn15o9uW8cumoBbxjEC(mc_koBw_auTeOpFWTLu_1_hd3*
mc_kyfq6L_eQbdYcPuOovpRDW);int32_T*mc_Vq30ZRWDg0Ope1BH5Wlxn6(const
mc_F5Olyc6xUoG7ZyDq78exBD*A,const int32_T*mc_k6HeriBJpGdZiPlDO4UZXp,const
int32_T*mc_VlzlbuXTjytugLyuufocD_,int32_T mc_F4FqMtzrIr0Ih9YO_bpGqr);double
mc_FVvAdrNPbiK3ciVovphJqC(int32_T*pm__lqjegyKuwStj56WZLiC_e,int32_T*
mc_FFZbGh27ya8eem_J_hUtAZ,int32_T n);int32_T mc_VqGwhdpnmyGkc5egfuzI9R(int32_T
mc_kyp6uAyJE40UVuAQNEYzS1,mc_F5Olyc6xUoG7ZyDq78exBD*mc_k0u3N7AKLBdaj5KgM8mztL,
int32_T mc_V_3pIMGNi1pQiyeoIJloym,int32_T*mc__01SK3u3lG0GaLCTTSoVGO,int32_T*
mc__nUrXnK_PlSWXDXfav4gTu,const int32_T*mc_FjDIs2zMLtx5We_IND4g6I);int32_T
mc__PAs7jPQB3p6jamHMS77BU(const mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T
mc_V2__YrimeI4E_yWnhKofpy,const int32_T*mc_k6HeriBJpGdZiPlDO4UZXp,int32_T*
mc_FQferGZUKft3_i5GvYy4Oy,int32_T*mc_V1pxxydYEnWVVi3QKesjvf);int32_T*
mc_kvTl6JgGLlpghLCj7SJ8Zb(const mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T
mc_F4FqMtzrIr0Ih9YO_bpGqr);int32_T mc__78cLFJw_ySFbTb4k127zA(
mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T(*mc__afZS_O3BMKpbuqov2Sqn2)(int32_T,
int32_T,double,void*),void*pm__sjTRWOMR4WzZisVeB2fYm);double
mc_FCxXZX7qax4Cf1qhlQMJ_K(double*x,double*mc_kCPCzQ_4FF88XTgtMjWqKy,int32_T n)
;int32_T mc_VjKkbv4A0k47XifnshEiFz(int32_T mc_kwrB3ZoKf7OufTHWaHJV7a,int32_T
mc_kyp6uAyJE40UVuAQNEYzS1,const int32_T*mc__gfup5UQrKdtaLq0JwxBv8,int32_T*
mc_F_OdG3IuH0OSgXl2PAC3Wt,int32_T*mc_FYLTf08Tnt0_hXkhRr2i3V,int32_T*
mc_FaaXUqBjXi_Cc58Cr7D5Pw,int32_T*mc_kCfp_4sWHvtwdmGWqI8AP3);int32_T*
mc__KcZrPHSqmd_Winpkn_zbn(const mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T
mc_k6QxQSbjWyGhcXikh7jTLf);int32_T*mc_VSXwwVMHmJpqfu39VY7afd(const int32_T*
mc_k6HeriBJpGdZiPlDO4UZXp,int32_T n);int32_T*mc_kkUWSotb_oO3YDxqYUxvcp(int32_T
n,int32_T mc_k6QxQSbjWyGhcXikh7jTLf);int32_T mc_VJp2YHG9mB_gfHKfpAYT7q(
mc_F5Olyc6xUoG7ZyDq78exBD*mc_k0u3N7AKLBdaj5KgM8mztL,const
mc_F5Olyc6xUoG7ZyDq78exBD*mc_Vqiy96WqvuhCaXm5e_vvT0,int32_T
mc_V2__YrimeI4E_yWnhKofpy,int32_T*mc__01SK3u3lG0GaLCTTSoVGO,const int32_T*
mc_FjDIs2zMLtx5We_IND4g6I);int32_T mc__bZ1EHlIu8t8WL63CWhZ5j(const
mc_F5Olyc6xUoG7ZyDq78exBD*A,int32_T mc_kyp6uAyJE40UVuAQNEYzS1,double
mc_kCPCzQ_4FF88XTgtMjWqKy,int32_T*mc_V1pxxydYEnWVVi3QKesjvf,double*x,int32_T
mc__CLRBwg4eOSEiqHPYKDedF,mc_F5Olyc6xUoG7ZyDq78exBD*mc_FStFcQlyAJ_dVy4kGZXBPQ,
int32_T mc___ECRgjqShlp_PytRplerL);mc_koBw_auTeOpFWTLu_1_hd3*
mc__17ror7eCZl9eiXoZ3px_g(mc_F5Olyc6xUoG7ZyDq78exBD*A);int32_T
mc_VI_gkAfbWYGleX3FfR8roq(mc_F5Olyc6xUoG7ZyDq78exBD*mc_k0u3N7AKLBdaj5KgM8mztL,
const mc_F5Olyc6xUoG7ZyDq78exBD*mc_Vqiy96WqvuhCaXm5e_vvT0,int32_T
mc_V2__YrimeI4E_yWnhKofpy,int32_T*mc__01SK3u3lG0GaLCTTSoVGO,double*x,const
int32_T*mc_FjDIs2zMLtx5We_IND4g6I,int32_T mc___aedK39Pax6Ziebprhh0i);int32_T
mc_Fx2UoNYY4W0WY5iaMITghy(int32_T mc_kyp6uAyJE40UVuAQNEYzS1,int32_T
mc_V2__YrimeI4E_yWnhKofpy,int32_T*mc_FcKez189ghKAYyDjWA9v5n,const int32_T*
mc_FTf2iFFdsgK3hewKsMgEx4,int32_T*mc_VlzlbuXTjytugLyuufocD_,int32_T*
mc_F65aUsM8ggpTgiucZs1fmm);mc_koBw_auTeOpFWTLu_1_hd3*mc_VfRC_16CnDtIYTHey4Izis
(int32_T mc_VLHhnPUiNQpve5VIL9P3O9,int32_T n);mc_koBw_auTeOpFWTLu_1_hd3*
mc_Fm6BWhHX7o4Vai4IMTAE87(mc_koBw_auTeOpFWTLu_1_hd3*mc_kyfq6L_eQbdYcPuOovpRDW,
mc_F5Olyc6xUoG7ZyDq78exBD*mc_FStFcQlyAJ_dVy4kGZXBPQ,void*
mc_V1pxxydYEnWVVi3QKesjvf,int32_T mc__suOgr_4PeCIZi_uhoSVwf);
mc_F5Olyc6xUoG7ZyDq78exBD*mc_kYUYSnR_wtpicaLJHkpwi_(mc_F5Olyc6xUoG7ZyDq78exBD*
mc_FStFcQlyAJ_dVy4kGZXBPQ,void*mc_V1pxxydYEnWVVi3QKesjvf,void*x,int32_T
mc__suOgr_4PeCIZi_uhoSVwf);int32_T*mc_Ff7NuTFKk3OCYDKMqomZ1z(int32_T*
pm__lqjegyKuwStj56WZLiC_e,mc_F5Olyc6xUoG7ZyDq78exBD*mc_FStFcQlyAJ_dVy4kGZXBPQ,
void*mc_V1pxxydYEnWVVi3QKesjvf,int32_T mc__suOgr_4PeCIZi_uhoSVwf);
mc_kPBB5xuFz74_aaM4N6U4Jv*mc___7vbyf5jjtDZHYPmA3rvK(mc_kPBB5xuFz74_aaM4N6U4Jv*
mc_F3nVSXkoDK8VeeL5OmY0_B,mc_F5Olyc6xUoG7ZyDq78exBD*mc_FStFcQlyAJ_dVy4kGZXBPQ,
void*mc_V1pxxydYEnWVVi3QKesjvf,void*x,int32_T mc__suOgr_4PeCIZi_uhoSVwf);
mc_F5Olyc6xUoG7ZyDq78exBD mc_Vw3pppsHg0GUgyX4TCj_Tm(const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,const PmRealVector*mc_V8ujEMKrDU8Q_mvu4yja1b);
PmfMessageId mc__d9fSk48MK4Id19pMIFckt(PmSparsityPattern**
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector**mc_V8ujEMKrDU8Q_mvu4yja1b,
mc_F5Olyc6xUoG7ZyDq78exBD*mc__fkjyn5jTndYhPkqyC8dcd,PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z);mc_F5Olyc6xUoG7ZyDq78exBD*mc_V4ZW0NcYptWdbiWXm2r7w0
(mc_F5Olyc6xUoG7ZyDq78exBD*mc__fkjyn5jTndYhPkqyC8dcd,const int32_T*
mc__AExROh1PVWNeP7hmMWuJv);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
void mc_kI1QS_uFgalidTU1DcIW4u(PmSparsityPattern**mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector**mc_V8ujEMKrDU8Q_mvu4yja1b,mc_F5Olyc6xUoG7ZyDq78exBD*
mc__fkjyn5jTndYhPkqyC8dcd){if(*mc_V_ku0ZO8TOxhc9438tlsBI!=NULL&&*
mc_V8ujEMKrDU8Q_mvu4yja1b!=NULL){PmIntVector mc__45ixy_yrElV_mwARBxpWM,
mc_k5rAWavtmx4MgqW6cqhcua,mc_kAzvx_iHgDpWZXEdxA_WG_,mc_FX8BAtbL_uGGZeE2WJiOPF;
PmRealVector mc_VBe01o8_ZESFgiTFtr7O1w;mc__45ixy_yrElV_mwARBxpWM.mN=
mc__fkjyn5jTndYhPkqyC8dcd->n+1;mc__45ixy_yrElV_mwARBxpWM.mX=
mc__fkjyn5jTndYhPkqyC8dcd->pm__lqjegyKuwStj56WZLiC_e;mc_kAzvx_iHgDpWZXEdxA_WG_
.mN=(*mc_V_ku0ZO8TOxhc9438tlsBI)->mNumCol+1;mc_kAzvx_iHgDpWZXEdxA_WG_.mX=(*
mc_V_ku0ZO8TOxhc9438tlsBI)->mJc;pm_VeeoZXnlJQ4u_112lGs8YD(&
mc_kAzvx_iHgDpWZXEdxA_WG_,&mc__45ixy_yrElV_mwARBxpWM);
mc_k5rAWavtmx4MgqW6cqhcua.mN=mc__fkjyn5jTndYhPkqyC8dcd->
pm__lqjegyKuwStj56WZLiC_e[mc__fkjyn5jTndYhPkqyC8dcd->n];
mc_k5rAWavtmx4MgqW6cqhcua.mX=mc__fkjyn5jTndYhPkqyC8dcd->
mc_kwrB3ZoKf7OufTHWaHJV7a;mc_FX8BAtbL_uGGZeE2WJiOPF.mN=((size_t)(*
mc_V_ku0ZO8TOxhc9438tlsBI)->mJc[(*mc_V_ku0ZO8TOxhc9438tlsBI)->mNumCol]);
mc_FX8BAtbL_uGGZeE2WJiOPF.mX=(*mc_V_ku0ZO8TOxhc9438tlsBI)->mIr;
pm_VeeoZXnlJQ4u_112lGs8YD(&mc_FX8BAtbL_uGGZeE2WJiOPF,&
mc_k5rAWavtmx4MgqW6cqhcua);mc_VBe01o8_ZESFgiTFtr7O1w.mN=
mc__fkjyn5jTndYhPkqyC8dcd->pm__lqjegyKuwStj56WZLiC_e[mc__fkjyn5jTndYhPkqyC8dcd
->n];mc_VBe01o8_ZESFgiTFtr7O1w.mX=mc__fkjyn5jTndYhPkqyC8dcd->x;pm_rv_equals_rv
(*mc_V8ujEMKrDU8Q_mvu4yja1b,&mc_VBe01o8_ZESFgiTFtr7O1w);}
mc__BJ1NEDJTgOMhaJKDrM6pN(mc__fkjyn5jTndYhPkqyC8dcd);}
mc_FBFzHfrmEc41ji0CQOA38T*mc_FRabik2L6bCWXXz1LyK_Ze(const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,const PmRealVector*mc_V8ujEMKrDU8Q_mvu4yja1b){
PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z=pm_default_allocator();
mc_F5Olyc6xUoG7ZyDq78exBD A=mc_Vw3pppsHg0GUgyX4TCj_Tm(
mc_V_ku0ZO8TOxhc9438tlsBI,mc_V8ujEMKrDU8Q_mvu4yja1b);mc_F5Olyc6xUoG7ZyDq78exBD
*mc__fkjyn5jTndYhPkqyC8dcd= &A;size_t mc_kwrB3ZoKf7OufTHWaHJV7a=0;
mc_VWUvciwDK_dziLpafRxush*mc__O8NaU0V4k0nfTqW63OXkb=NULL;
mc_kPBB5xuFz74_aaM4N6U4Jv*mc_FT1ypZEaF8CMby75xRi7rS=NULL;
mc_FBFzHfrmEc41ji0CQOA38T*mc_k97GnLAArQWibunVaBx_Ol=NULL;if(!
mc_V8ujEMKrDU8Q_mvu4yja1b||mc_V8ujEMKrDU8Q_mvu4yja1b->mN==0){return NULL;}
mc__O8NaU0V4k0nfTqW63OXkb=mc__HBpzStane0GaaQtDu_y9F(0,
mc__fkjyn5jTndYhPkqyC8dcd,0);if(!mc__O8NaU0V4k0nfTqW63OXkb){return NULL;}
mc_FT1ypZEaF8CMby75xRi7rS=mc__OANyqXuH__Wi5n3l9hrJe(mc__fkjyn5jTndYhPkqyC8dcd,
mc__O8NaU0V4k0nfTqW63OXkb,1.0);mc_Fe3WdhVNm1lm_TputcgM_w(
mc__O8NaU0V4k0nfTqW63OXkb);mc__O8NaU0V4k0nfTqW63OXkb=NULL;if(!
mc_FT1ypZEaF8CMby75xRi7rS){return NULL;}mc_k97GnLAArQWibunVaBx_Ol=
mc_VInfIQCul4ShdLlbU4F0WB(1,sizeof(mc_FBFzHfrmEc41ji0CQOA38T));if(!
mc_k97GnLAArQWibunVaBx_Ol){mc_VZ5qqYWDqx_NaqOx3T8EeD(mc_FT1ypZEaF8CMby75xRi7rS
);mc_FT1ypZEaF8CMby75xRi7rS=NULL;return NULL;}mc_k97GnLAArQWibunVaBx_Ol->
mc_krPFDE3HuNG9jP3UefXVXY=pm_create_sparsity_pattern(mc_FT1ypZEaF8CMby75xRi7rS
->mc__ut5UfJwzNlZ_XZC_yEgKo->pm__lqjegyKuwStj56WZLiC_e[
mc_FT1ypZEaF8CMby75xRi7rS->mc__ut5UfJwzNlZ_XZC_yEgKo->n],
mc_FT1ypZEaF8CMby75xRi7rS->mc__ut5UfJwzNlZ_XZC_yEgKo->
mc_VLHhnPUiNQpve5VIL9P3O9,mc_FT1ypZEaF8CMby75xRi7rS->mc__ut5UfJwzNlZ_XZC_yEgKo
->n,mc_FOGg0ZWot2WdYenO8zaD4Z);mc_k97GnLAArQWibunVaBx_Ol->
mc_kDnTh4B6n6xuca3dKua_H9=pm_create_real_vector(mc_FT1ypZEaF8CMby75xRi7rS->
mc__ut5UfJwzNlZ_XZC_yEgKo->pm__lqjegyKuwStj56WZLiC_e[mc_FT1ypZEaF8CMby75xRi7rS
->mc__ut5UfJwzNlZ_XZC_yEgKo->n],mc_FOGg0ZWot2WdYenO8zaD4Z);
mc_k97GnLAArQWibunVaBx_Ol->mc_kP9WB_4RortueyfaDBlnXM=
pm_create_sparsity_pattern(mc_FT1ypZEaF8CMby75xRi7rS->
mc_Vi4Cp0qK964NYTFMGr9Ttn->pm__lqjegyKuwStj56WZLiC_e[mc_FT1ypZEaF8CMby75xRi7rS
->mc_Vi4Cp0qK964NYTFMGr9Ttn->n],mc_FT1ypZEaF8CMby75xRi7rS->
mc_Vi4Cp0qK964NYTFMGr9Ttn->mc_VLHhnPUiNQpve5VIL9P3O9,mc_FT1ypZEaF8CMby75xRi7rS
->mc_Vi4Cp0qK964NYTFMGr9Ttn->n,mc_FOGg0ZWot2WdYenO8zaD4Z);
mc_k97GnLAArQWibunVaBx_Ol->mc__kn7XECBqbdPimCJ8iD1Kp=pm_create_real_vector(
mc_FT1ypZEaF8CMby75xRi7rS->mc_Vi4Cp0qK964NYTFMGr9Ttn->
pm__lqjegyKuwStj56WZLiC_e[mc_FT1ypZEaF8CMby75xRi7rS->mc_Vi4Cp0qK964NYTFMGr9Ttn
->n],mc_FOGg0ZWot2WdYenO8zaD4Z);mc_k97GnLAArQWibunVaBx_Ol->
mc_FjDIs2zMLtx5We_IND4g6I=pm_create_int_vector(mc_V_ku0ZO8TOxhc9438tlsBI->
mNumRow,mc_FOGg0ZWot2WdYenO8zaD4Z);for(mc_kwrB3ZoKf7OufTHWaHJV7a=0;
mc_kwrB3ZoKf7OufTHWaHJV7a<mc_V_ku0ZO8TOxhc9438tlsBI->mNumRow;
mc_kwrB3ZoKf7OufTHWaHJV7a++){mc_k97GnLAArQWibunVaBx_Ol->
mc_FjDIs2zMLtx5We_IND4g6I->mX[mc_kwrB3ZoKf7OufTHWaHJV7a]=
mc_FT1ypZEaF8CMby75xRi7rS->mc_FjDIs2zMLtx5We_IND4g6I[mc_kwrB3ZoKf7OufTHWaHJV7a
];}mc_kI1QS_uFgalidTU1DcIW4u(&(mc_k97GnLAArQWibunVaBx_Ol->
mc_krPFDE3HuNG9jP3UefXVXY),&(mc_k97GnLAArQWibunVaBx_Ol->
mc_kDnTh4B6n6xuca3dKua_H9),mc_FT1ypZEaF8CMby75xRi7rS->
mc__ut5UfJwzNlZ_XZC_yEgKo);mc_kI1QS_uFgalidTU1DcIW4u(&(
mc_k97GnLAArQWibunVaBx_Ol->mc_kP9WB_4RortueyfaDBlnXM),&(
mc_k97GnLAArQWibunVaBx_Ol->mc__kn7XECBqbdPimCJ8iD1Kp),
mc_FT1ypZEaF8CMby75xRi7rS->mc_Vi4Cp0qK964NYTFMGr9Ttn);
mc_FT1ypZEaF8CMby75xRi7rS->mc__ut5UfJwzNlZ_XZC_yEgKo=NULL;
mc_FT1ypZEaF8CMby75xRi7rS->mc_Vi4Cp0qK964NYTFMGr9Ttn=NULL;
mc_VZ5qqYWDqx_NaqOx3T8EeD(mc_FT1ypZEaF8CMby75xRi7rS);mc_FT1ypZEaF8CMby75xRi7rS
=NULL;return mc_k97GnLAArQWibunVaBx_Ol;}void mc__Qbr2NKiXB0XdqkBcqyU6q(
mc_FBFzHfrmEc41ji0CQOA38T*mc_k97GnLAArQWibunVaBx_Ol){PmAllocator*a=
pm_default_allocator();pm_VYooJBURCwKrVu6RXzQZ_5(mc_k97GnLAArQWibunVaBx_Ol->
mc_krPFDE3HuNG9jP3UefXVXY,a);pm_destroy_real_vector(mc_k97GnLAArQWibunVaBx_Ol
->mc_kDnTh4B6n6xuca3dKua_H9,a);pm_VYooJBURCwKrVu6RXzQZ_5(
mc_k97GnLAArQWibunVaBx_Ol->mc_kP9WB_4RortueyfaDBlnXM,a);pm_destroy_real_vector
(mc_k97GnLAArQWibunVaBx_Ol->mc__kn7XECBqbdPimCJ8iD1Kp,a);pm_destroy_int_vector
(mc_k97GnLAArQWibunVaBx_Ol->mc_FjDIs2zMLtx5We_IND4g6I,a);{void*
mc_kk06poLCQlh5i5Yv6GSh7e=(mc_k97GnLAArQWibunVaBx_Ol);if(
mc_kk06poLCQlh5i5Yv6GSh7e!=0){(a)->mFreeFcn(a,mc_kk06poLCQlh5i5Yv6GSh7e);}};}
void mc_FQDXPJI_fEdac1lJmv32Pw(const PmSparsityPattern*
mc_FNLG4N0Qc3OxdmBVwutDsy,const PmRealVector*mc_VlnhKi82gfCLgumIqeduOq,const
PmRealVector*b,const PmRealVector*x){size_t mc_kwrB3ZoKf7OufTHWaHJV7a,
mc_kyp6uAyJE40UVuAQNEYzS1;pm_rv_equals_rv(x,b);for(mc_kwrB3ZoKf7OufTHWaHJV7a=
mc_FNLG4N0Qc3OxdmBVwutDsy->mNumCol;mc_kwrB3ZoKf7OufTHWaHJV7a-->0;){(void)0;;x
->mX[mc_kwrB3ZoKf7OufTHWaHJV7a]/=mc_VlnhKi82gfCLgumIqeduOq->mX[(
mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[mc_kwrB3ZoKf7OufTHWaHJV7a+1]-1)];for(
mc_kyp6uAyJE40UVuAQNEYzS1=mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[
mc_kwrB3ZoKf7OufTHWaHJV7a];mc_kyp6uAyJE40UVuAQNEYzS1<(size_t)
mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[mc_kwrB3ZoKf7OufTHWaHJV7a+1]-1;
mc_kyp6uAyJE40UVuAQNEYzS1++){(void)0;;x->mX[mc_FNLG4N0Qc3OxdmBVwutDsy->mIr[
mc_kyp6uAyJE40UVuAQNEYzS1]]-=mc_VlnhKi82gfCLgumIqeduOq->mX[
mc_kyp6uAyJE40UVuAQNEYzS1]*x->mX[mc_kwrB3ZoKf7OufTHWaHJV7a];}}}void
mc_FHLECAsrw4SbaauHCK0H0z(const PmSparsityPattern*mc_FNLG4N0Qc3OxdmBVwutDsy,
const PmRealVector*mc_VlnhKi82gfCLgumIqeduOq,const PmRealVector*b,const
PmRealVector*x){size_t mc_kwrB3ZoKf7OufTHWaHJV7a,mc_kyp6uAyJE40UVuAQNEYzS1;
pm_rv_equals_rv(x,b);for(mc_kwrB3ZoKf7OufTHWaHJV7a=0;mc_kwrB3ZoKf7OufTHWaHJV7a
<(size_t)mc_FNLG4N0Qc3OxdmBVwutDsy->mNumCol;mc_kwrB3ZoKf7OufTHWaHJV7a++){(void
)0;;x->mX[mc_kwrB3ZoKf7OufTHWaHJV7a]/=mc_VlnhKi82gfCLgumIqeduOq->mX[
mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[mc_kwrB3ZoKf7OufTHWaHJV7a]];for(
mc_kyp6uAyJE40UVuAQNEYzS1=mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[
mc_kwrB3ZoKf7OufTHWaHJV7a]+1;mc_kyp6uAyJE40UVuAQNEYzS1<(size_t)
mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[mc_kwrB3ZoKf7OufTHWaHJV7a+1];
mc_kyp6uAyJE40UVuAQNEYzS1++){(void)0;;x->mX[mc_FNLG4N0Qc3OxdmBVwutDsy->mIr[
mc_kyp6uAyJE40UVuAQNEYzS1]]-=mc_VlnhKi82gfCLgumIqeduOq->mX[
mc_kyp6uAyJE40UVuAQNEYzS1]*x->mX[mc_kwrB3ZoKf7OufTHWaHJV7a];}}}
