#include "pm_std.h"
#include "pm_std.h"
#include "mc_std.h"
#include "mc_std.h"
#include "pm_std.h"
#include "mc_std.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(const void*mc_kDRphcAfRHSbf1ZLKEDW9k,const PmRealVector*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;const void*(*mc_FXz9GdGvpOKnh5e2dYstBe)(const McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(const void*
mc_kDRphcAfRHSbf1ZLKEDW9k,const PmIntVector*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);const void*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(const McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mc_VYGWBho6N1K_eyHOMGjDiW)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};
typedef struct mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct
McMatrixFunctionTag{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;const
PmSparsityPattern*mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(
const void*mc_kDRphcAfRHSbf1ZLKEDW9k,const PmRealVector*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK)
;const void*(*mc_FXz9GdGvpOKnh5e2dYstBe)(const McMatrixFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(McMatrixFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction*mc__Lbf28Vmk3xMWaMWf4YhQ0(
McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,PmBoolVector*
mc_VlZMmzn2z2dpZyy2834RK6,PmBoolVector*mc__d0bLF53CvGmj1ZBgVfH1i,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_kjCgkKdgjf_B_e_hraPYjI(
McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,PmBoolVector*
mc__zB_qJZo0IluZ9L_7brV_8,PmBoolVector*mc__kGOISkZ94x2fHWVVKuIS5,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_F41vm5CeApOpiPIy1rZa2m(
McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc__Lbf28Vmk3xMWaMWf4YhQ0(
McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,PmBoolVector*
mc_VlZMmzn2z2dpZyy2834RK6,PmBoolVector*mc__d0bLF53CvGmj1ZBgVfH1i,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY){McMatrixFunction*mc_F_uDt5VwzhGvjqZUKDgWv5=NULL;
mc_F_uDt5VwzhGvjqZUKDgWv5=mc_F41vm5CeApOpiPIy1rZa2m(mc_kXwHswK956KEimdoHimdrb,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc_F_uDt5VwzhGvjqZUKDgWv5=mc_kjCgkKdgjf_B_e_hraPYjI
(mc_F_uDt5VwzhGvjqZUKDgWv5,mc_VlZMmzn2z2dpZyy2834RK6,mc__d0bLF53CvGmj1ZBgVfH1i
,pm_FbYb_iLqY2hwZTVlVaiqJY);return mc_F41vm5CeApOpiPIy1rZa2m(
mc_F_uDt5VwzhGvjqZUKDgWv5,pm_FbYb_iLqY2hwZTVlVaiqJY);}
