#include "stddef.h"
#include "stdlib.h"
#include "pm_std.h"
extern double pm_math_kgx_JAsC_eOxcXPiVC1xcV(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const creal_T*pm_math_F2l4p_g4sn02huHNflQjMH,
int pm_math_k2AgNEfVSvlhZ5VkmS6QH2,int pm_math__1J0baDSh1W3jqPn9PkTOT);
#include "pm_std.h"
extern void pm_math_V4wY5inRPrGJ_q94UMd56c(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const int pm_math__jwySfHyx1SXgXJeVWoIzb,const
real_T*pm_math_F2l4p_g4sn02huHNflQjMH,const real_T*
pm_math_Vqiy96WqvuhCaXm5e_vvT0,creal_T*pm_math_kJeUz19e49pVaDwcttsZep,creal_T*
pm_math_kyfq6L_eQbdYcPuOovpRDW,creal_T*pm_math_kXii4Miq3Y_ShPn9EHS3D5,creal_T*
pm_math_FYAUa2zJy8Cah1YsdPJok5,creal_T*pm_math__Vu43oWQSkpLiuph6ye1KN,creal_T*
pm_math_VHUYV1kdST0efLHvpiBBXm,creal_T*pm_math_VRZCD_UL_ESThy75dC9J8D,creal_T*
pm_math_Fo1tUR18sIdue1E1QXuOnL,creal_T*pm_math___7SXc4Q_w8saDIIf2ecjp,real_T*
pm_math_ktFLct2wbuxD_5iTvRiZEZ,real_T*pm_math_kHM1aMQ_rJdeheUxTze_oV,int32_T*
pm_math__qLHk6daYiGnXenMNt2kR_,int8_T*pm_math_VS3xMd4pLil0i5cxPD0ErK);
#include "pm_std.h"
extern real_T pm_math_V6hUjCc3PiCAauyMwJP5nb;extern real_T
pm_math_Vco4W7EuZu4k_1cAN9SDVG;extern real_T pm_math_k9HpTo0HuFt0gDRVyg17Wc;
extern real32_T pm_math__JOzYwXJOmSsiaZ6WMnnZZ;extern real32_T
pm_math_VaGr_igKLHx0bDW9g54I6v;extern real32_T pm_math_kZu0y5Pv4G8tg1EE_V6tGP;
extern void pm_math_F3OoZ1Weno85bujDCIyv_c(void);extern boolean_T
pm_math__LIYjt5pi54rVTuNKI6I5_(real_T pm_math_kg4CyRgbu6OdeewZOel7Qx);extern
boolean_T pm_math_VK2BuaMRCmOxjLjqE4tZMh(real32_T
pm_math_kg4CyRgbu6OdeewZOel7Qx);extern boolean_T pm_math__J9snrOx2Cp4dD_e3lGtRm
(real_T pm_math_kg4CyRgbu6OdeewZOel7Qx);extern boolean_T
pm_math_kwH13YYrpKtAbDLZ9Q_8I9(real32_T pm_math_kg4CyRgbu6OdeewZOel7Qx);
#include "math.h"
double pm_math_kgx_JAsC_eOxcXPiVC1xcV(const int pm_math_FdNKyaRLqeWhg5tGqF_VYT
,const creal_T*pm_math_F2l4p_g4sn02huHNflQjMH,int
pm_math_k2AgNEfVSvlhZ5VkmS6QH2,int pm_math__1J0baDSh1W3jqPn9PkTOT){double
pm_math_Fe6copTTRcKEayCm87ABO_;double pm_math_kHfMSiCBJRSoju34wwOKOx;double
pm_math_FXbJOh5Xsz83XPYtZXgb8J;boolean_T pm_math__t5oNb8LsI4LXe3M5QMnFs;int
pm_math_kyp6uAyJE40UVuAQNEYzS1;int pm_math_kwrB3ZoKf7OufTHWaHJV7a;int
pm_math__ZyfOoZEzhGdcLL3nOK_4g;double pm_math_kpbouxpwp28acTBt_OH0SL;double
pm_math_Fb1yYR_snQd4h9eehAn_FD;double pm_math_VeS9OdBseW_5YX4KOJEPkI;
pm_math_Fe6copTTRcKEayCm87ABO_=0.0;if(pm_math_k2AgNEfVSvlhZ5VkmS6QH2<=
pm_math__1J0baDSh1W3jqPn9PkTOT){pm_math_kHfMSiCBJRSoju34wwOKOx=0.0;
pm_math_FXbJOh5Xsz83XPYtZXgb8J=0.0;pm_math__t5oNb8LsI4LXe3M5QMnFs=true;for(
pm_math_kyp6uAyJE40UVuAQNEYzS1=pm_math_k2AgNEfVSvlhZ5VkmS6QH2;
pm_math_kyp6uAyJE40UVuAQNEYzS1<=pm_math__1J0baDSh1W3jqPn9PkTOT;
pm_math_kyp6uAyJE40UVuAQNEYzS1++){pm_math_kwrB3ZoKf7OufTHWaHJV7a=
pm_math_kyp6uAyJE40UVuAQNEYzS1+1;if(pm_math__1J0baDSh1W3jqPn9PkTOT<
pm_math_kyp6uAyJE40UVuAQNEYzS1+1){pm_math_kwrB3ZoKf7OufTHWaHJV7a=
pm_math__1J0baDSh1W3jqPn9PkTOT;}for(pm_math__ZyfOoZEzhGdcLL3nOK_4g=
pm_math_k2AgNEfVSvlhZ5VkmS6QH2;pm_math__ZyfOoZEzhGdcLL3nOK_4g<=
pm_math_kwrB3ZoKf7OufTHWaHJV7a;pm_math__ZyfOoZEzhGdcLL3nOK_4g++){
pm_math_kpbouxpwp28acTBt_OH0SL=pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math__ZyfOoZEzhGdcLL3nOK_4g+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re;pm_math_Fb1yYR_snQd4h9eehAn_FD=
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math__ZyfOoZEzhGdcLL3nOK_4g+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im;if(
pm_math_kpbouxpwp28acTBt_OH0SL!=0.0){pm_math_kpbouxpwp28acTBt_OH0SL=fabs(
pm_math_kpbouxpwp28acTBt_OH0SL);if(pm_math__t5oNb8LsI4LXe3M5QMnFs){
pm_math_FXbJOh5Xsz83XPYtZXgb8J=1.0;pm_math_kHfMSiCBJRSoju34wwOKOx=
pm_math_kpbouxpwp28acTBt_OH0SL;pm_math__t5oNb8LsI4LXe3M5QMnFs=false;}else if(
pm_math_kHfMSiCBJRSoju34wwOKOx<pm_math_kpbouxpwp28acTBt_OH0SL){
pm_math_VeS9OdBseW_5YX4KOJEPkI=pm_math_kHfMSiCBJRSoju34wwOKOx/
pm_math_kpbouxpwp28acTBt_OH0SL;pm_math_FXbJOh5Xsz83XPYtZXgb8J=
pm_math_FXbJOh5Xsz83XPYtZXgb8J*pm_math_VeS9OdBseW_5YX4KOJEPkI*
pm_math_VeS9OdBseW_5YX4KOJEPkI+1.0;pm_math_kHfMSiCBJRSoju34wwOKOx=
pm_math_kpbouxpwp28acTBt_OH0SL;}else{pm_math_VeS9OdBseW_5YX4KOJEPkI=
pm_math_kpbouxpwp28acTBt_OH0SL/pm_math_kHfMSiCBJRSoju34wwOKOx;
pm_math_FXbJOh5Xsz83XPYtZXgb8J+=pm_math_VeS9OdBseW_5YX4KOJEPkI*
pm_math_VeS9OdBseW_5YX4KOJEPkI;}}if(pm_math_Fb1yYR_snQd4h9eehAn_FD!=0.0){
pm_math_kpbouxpwp28acTBt_OH0SL=fabs(pm_math_Fb1yYR_snQd4h9eehAn_FD);if(
pm_math__t5oNb8LsI4LXe3M5QMnFs){pm_math_FXbJOh5Xsz83XPYtZXgb8J=1.0;
pm_math_kHfMSiCBJRSoju34wwOKOx=pm_math_kpbouxpwp28acTBt_OH0SL;
pm_math__t5oNb8LsI4LXe3M5QMnFs=false;}else if(pm_math_kHfMSiCBJRSoju34wwOKOx<
pm_math_kpbouxpwp28acTBt_OH0SL){pm_math_VeS9OdBseW_5YX4KOJEPkI=
pm_math_kHfMSiCBJRSoju34wwOKOx/pm_math_kpbouxpwp28acTBt_OH0SL;
pm_math_FXbJOh5Xsz83XPYtZXgb8J=pm_math_FXbJOh5Xsz83XPYtZXgb8J*
pm_math_VeS9OdBseW_5YX4KOJEPkI*pm_math_VeS9OdBseW_5YX4KOJEPkI+1.0;
pm_math_kHfMSiCBJRSoju34wwOKOx=pm_math_kpbouxpwp28acTBt_OH0SL;}else{
pm_math_VeS9OdBseW_5YX4KOJEPkI=pm_math_kpbouxpwp28acTBt_OH0SL/
pm_math_kHfMSiCBJRSoju34wwOKOx;pm_math_FXbJOh5Xsz83XPYtZXgb8J+=
pm_math_VeS9OdBseW_5YX4KOJEPkI*pm_math_VeS9OdBseW_5YX4KOJEPkI;}}}}
pm_math_Fe6copTTRcKEayCm87ABO_=pm_math_kHfMSiCBJRSoju34wwOKOx*sqrt(
pm_math_FXbJOh5Xsz83XPYtZXgb8J);}return pm_math_Fe6copTTRcKEayCm87ABO_;}
