#include "stddef.h"
#include "stdlib.h"
#include "pm_std.h"
extern void pm_math_Vxt72gtEl4GOZqw9ZzSU5b(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const int pm_math__jwySfHyx1SXgXJeVWoIzb,
creal_T*pm_math_F2l4p_g4sn02huHNflQjMH,creal_T*pm_math_Vqiy96WqvuhCaXm5e_vvT0,
int*pm_math_kSEW12lLld4uY1T_UcY6kY,creal_T*pm_math_kRdbZgju4QKPcmCLNev9n2,
creal_T*pm_math__Vu43oWQSkpLiuph6ye1KN,creal_T*pm_math_kJeUz19e49pVaDwcttsZep,
creal_T*pm_math_VHUYV1kdST0efLHvpiBBXm,creal_T*pm_math_VRZCD_UL_ESThy75dC9J8D,
creal_T*pm_math_Fo1tUR18sIdue1E1QXuOnL,creal_T*pm_math___7SXc4Q_w8saDIIf2ecjp,
real_T*pm_math_ktFLct2wbuxD_5iTvRiZEZ,real_T*pm_math_kHM1aMQ_rJdeheUxTze_oV,
int32_T*pm_math__qLHk6daYiGnXenMNt2kR_,int8_T*pm_math_VS3xMd4pLil0i5cxPD0ErK);
#include "pm_std.h"
extern void pm_math_V4wY5inRPrGJ_q94UMd56c(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const int pm_math__jwySfHyx1SXgXJeVWoIzb,const
real_T*pm_math_F2l4p_g4sn02huHNflQjMH,const real_T*
pm_math_Vqiy96WqvuhCaXm5e_vvT0,creal_T*pm_math_kJeUz19e49pVaDwcttsZep,creal_T*
pm_math_kyfq6L_eQbdYcPuOovpRDW,creal_T*pm_math_kXii4Miq3Y_ShPn9EHS3D5,creal_T*
pm_math_FYAUa2zJy8Cah1YsdPJok5,creal_T*pm_math__Vu43oWQSkpLiuph6ye1KN,creal_T*
pm_math_VHUYV1kdST0efLHvpiBBXm,creal_T*pm_math_VRZCD_UL_ESThy75dC9J8D,creal_T*
pm_math_Fo1tUR18sIdue1E1QXuOnL,creal_T*pm_math___7SXc4Q_w8saDIIf2ecjp,real_T*
pm_math_ktFLct2wbuxD_5iTvRiZEZ,real_T*pm_math_kHM1aMQ_rJdeheUxTze_oV,int32_T*
pm_math__qLHk6daYiGnXenMNt2kR_,int8_T*pm_math_VS3xMd4pLil0i5cxPD0ErK);
#include "pm_std.h"
extern real_T pm_math_V6hUjCc3PiCAauyMwJP5nb;extern real_T
pm_math_Vco4W7EuZu4k_1cAN9SDVG;extern real_T pm_math_k9HpTo0HuFt0gDRVyg17Wc;
extern real32_T pm_math__JOzYwXJOmSsiaZ6WMnnZZ;extern real32_T
pm_math_VaGr_igKLHx0bDW9g54I6v;extern real32_T pm_math_kZu0y5Pv4G8tg1EE_V6tGP;
extern void pm_math_F3OoZ1Weno85bujDCIyv_c(void);extern boolean_T
pm_math__LIYjt5pi54rVTuNKI6I5_(real_T pm_math_kg4CyRgbu6OdeewZOel7Qx);extern
boolean_T pm_math_VK2BuaMRCmOxjLjqE4tZMh(real32_T
pm_math_kg4CyRgbu6OdeewZOel7Qx);extern boolean_T pm_math__J9snrOx2Cp4dD_e3lGtRm
(real_T pm_math_kg4CyRgbu6OdeewZOel7Qx);extern boolean_T
pm_math_kwH13YYrpKtAbDLZ9Q_8I9(real32_T pm_math_kg4CyRgbu6OdeewZOel7Qx);
#include "pm_std.h"
extern void pm_math__1eja2CXWF0SdXzvz5uav_(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const int pm_math__jwySfHyx1SXgXJeVWoIzb,
creal_T*pm_math_F2l4p_g4sn02huHNflQjMH,int pm_math_kMkFfPlTO4pcZ1eiIuymng,int
pm_math__NbjXUeO_bdXjLOXjp08yZ,int pm_math_Vs_1cI3F_64WcTozTr14ry,creal_T*
pm_math_VHUYV1kdST0efLHvpiBBXm,creal_T*pm_math_VRZCD_UL_ESThy75dC9J8D);
#include "pm_std.h"
extern void pm_math__G_5qfTciulGdqw2gjG38D(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,creal_T*pm_math_F2l4p_g4sn02huHNflQjMH,creal_T*
pm_math_Vqiy96WqvuhCaXm5e_vvT0,int*pm_math_k2AgNEfVSvlhZ5VkmS6QH2,int*
pm_math__1J0baDSh1W3jqPn9PkTOT,int32_T*pm_math__qLHk6daYiGnXenMNt2kR_);
#include "pm_std.h"
extern void pm_math_F9lhEtqCeltji1XW4PRkXt(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const int pm_math__jwySfHyx1SXgXJeVWoIzb,
creal_T*pm_math_F2l4p_g4sn02huHNflQjMH,creal_T*pm_math_Vqiy96WqvuhCaXm5e_vvT0,
int pm_math_k2AgNEfVSvlhZ5VkmS6QH2,int pm_math__1J0baDSh1W3jqPn9PkTOT,creal_T*
pm_math_FBuROKTP_gCWgT_XDEoCzK,int*pm_math_kSEW12lLld4uY1T_UcY6kY,creal_T*
pm_math_kRdbZgju4QKPcmCLNev9n2,creal_T*pm_math__Vu43oWQSkpLiuph6ye1KN);
#include "pm_std.h"
extern double pm_math_k7lTE2xLhk_xdP85qIVEoj(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const int pm_math__jwySfHyx1SXgXJeVWoIzb,const
creal_T*x);
#include "pm_std.h"
extern void pm_math__rpEXF0kArpajmJg_Jv0eW(const creal_T
pm_math_Fe6copTTRcKEayCm87ABO_,const creal_T pm_math_VoTkdAz8Qxd2iDKiMSyIbK,
double*pm_math_F5Olyc6xUoG7ZyDq78exBD,creal_T*pm_math_kgWQ_oIWTKdXZyfD4IYR1F);
extern void pm_math__wt7gD7RMvKZaeZRgAma6O(const creal_T
pm_math_Fe6copTTRcKEayCm87ABO_,const creal_T pm_math_VoTkdAz8Qxd2iDKiMSyIbK,
double*pm_math_F5Olyc6xUoG7ZyDq78exBD,creal_T*pm_math_kgWQ_oIWTKdXZyfD4IYR1F,
creal_T*pm_math_kUQBO1dSP8_IVqRAUx4R8G);
#include "pm_std.h"
extern void pm_math_V45aqmxcmhdvWeNEn2nMVd(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,double pm_math_kTTGGGMfHYpWd5iVnTufXw,double
pm_math_VK6lUauAkQKTjyZZbtV_P2,creal_T*pm_math_F2l4p_g4sn02huHNflQjMH);extern
void pm_math__pwzb3GtrLhhfqqwqtHnjj(const int pm_math_FdNKyaRLqeWhg5tGqF_VYT,
const int pm_math__jwySfHyx1SXgXJeVWoIzb,double pm_math_kTTGGGMfHYpWd5iVnTufXw
,double pm_math_VK6lUauAkQKTjyZZbtV_P2,creal_T*pm_math_F2l4p_g4sn02huHNflQjMH)
;
#include "pm_std.h"
extern void pm_math_VRxuc3uSEyOgbqgYyEw9PS(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const creal_T*pm_math_F2l4p_g4sn02huHNflQjMH,
const creal_T*pm_math_Vqiy96WqvuhCaXm5e_vvT0,creal_T*
pm_math_kJeUz19e49pVaDwcttsZep,creal_T*pm_math_Fo1tUR18sIdue1E1QXuOnL,creal_T*
pm_math___7SXc4Q_w8saDIIf2ecjp,real_T*pm_math_ktFLct2wbuxD_5iTvRiZEZ,real_T*
pm_math_kHM1aMQ_rJdeheUxTze_oV);
#include "math.h"
#include "pm_std.h"
void pm_math_Vxt72gtEl4GOZqw9ZzSU5b(const int pm_math_FdNKyaRLqeWhg5tGqF_VYT,
const int pm_math__jwySfHyx1SXgXJeVWoIzb,creal_T*
pm_math_F2l4p_g4sn02huHNflQjMH,creal_T*pm_math_Vqiy96WqvuhCaXm5e_vvT0,int*
pm_math_kSEW12lLld4uY1T_UcY6kY,creal_T*pm_math_kRdbZgju4QKPcmCLNev9n2,creal_T*
pm_math__Vu43oWQSkpLiuph6ye1KN,creal_T*pm_math_kJeUz19e49pVaDwcttsZep,creal_T*
pm_math_VHUYV1kdST0efLHvpiBBXm,creal_T*pm_math_VRZCD_UL_ESThy75dC9J8D,creal_T*
pm_math_Fo1tUR18sIdue1E1QXuOnL,creal_T*pm_math___7SXc4Q_w8saDIIf2ecjp,real_T*
pm_math_ktFLct2wbuxD_5iTvRiZEZ,real_T*pm_math_kHM1aMQ_rJdeheUxTze_oV,int32_T*
pm_math__qLHk6daYiGnXenMNt2kR_,int8_T*pm_math_VS3xMd4pLil0i5cxPD0ErK){int n;
int pm_math_kyWde2KZDLCkemScG8IiFy;int pm_math__0whwiO_wLpmgDjzh3qDNZ;double
pm_math__CTkJ_C1U90PiDqSlWut2a;boolean_T pm_math_F85M4pG_wzOGZqvlERykug;double
pm_math__eF5mveiczSq_qps3D6fj_;boolean_T pm_math_Fqp_Q4lfXKtYfXbj_au4kb;double
pm_math_VnpPAIEy4a0ocm1ufujJN0;double pm_math_k7U6wyp5KghiXiGknB_n6B;int
pm_math_k2AgNEfVSvlhZ5VkmS6QH2;int pm_math__1J0baDSh1W3jqPn9PkTOT;int
pm_math_kwrB3ZoKf7OufTHWaHJV7a;int pm_math__H7y_KVNFQhie13GEb_pt0;int
pm_math_kJrcOmJJ_wWYfH5M5R0Vey;creal_T pm_math_Fk2O4u6vQUpibmbv8Kjgnn;int
pm_math_kyp6uAyJE40UVuAQNEYzS1;double pm_math_V2ngbolOwr0raTlCR3nzE5;double
pm_math_kQlKTq1F3spqiixck2H6s7;double pm_math_FFZbGh27ya8eem_J_hUtAZ;boolean_T
pm_math_F81QwThDphpXjqsd6ML4yG;int pm_math_VLHhnPUiNQpve5VIL9P3O9;double
pm_math_FzyLWRgau0pMYq2XSI3ETL;double pm_math_F32Ql82vv6pW_PYIdpkFQ0;*
pm_math_kSEW12lLld4uY1T_UcY6kY=0;n=pm_math_FdNKyaRLqeWhg5tGqF_VYT;
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(
pm_math_kyWde2KZDLCkemScG8IiFy=0;pm_math_kyWde2KZDLCkemScG8IiFy<
pm_math__0whwiO_wLpmgDjzh3qDNZ;pm_math_kyWde2KZDLCkemScG8IiFy++){
pm_math_kRdbZgju4QKPcmCLNev9n2[pm_math_kyWde2KZDLCkemScG8IiFy].re=0.0;
pm_math_kRdbZgju4QKPcmCLNev9n2[pm_math_kyWde2KZDLCkemScG8IiFy].im=0.0;}
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(
pm_math_kyWde2KZDLCkemScG8IiFy=0;pm_math_kyWde2KZDLCkemScG8IiFy<
pm_math__0whwiO_wLpmgDjzh3qDNZ;pm_math_kyWde2KZDLCkemScG8IiFy++){
pm_math__Vu43oWQSkpLiuph6ye1KN[pm_math_kyWde2KZDLCkemScG8IiFy].re=0.0;
pm_math__Vu43oWQSkpLiuph6ye1KN[pm_math_kyWde2KZDLCkemScG8IiFy].im=0.0;}
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(pm_math_kyWde2KZDLCkemScG8IiFy=0;
pm_math_kyWde2KZDLCkemScG8IiFy<pm_math__0whwiO_wLpmgDjzh3qDNZ;
pm_math_kyWde2KZDLCkemScG8IiFy++){pm_math_kJeUz19e49pVaDwcttsZep[
pm_math_kyWde2KZDLCkemScG8IiFy].re=0.0;pm_math_kJeUz19e49pVaDwcttsZep[
pm_math_kyWde2KZDLCkemScG8IiFy].im=0.0;}if((pm_math_FdNKyaRLqeWhg5tGqF_VYT!=0)
&&(pm_math__jwySfHyx1SXgXJeVWoIzb!=0)){pm_math__CTkJ_C1U90PiDqSlWut2a=
pm_math_k7lTE2xLhk_xdP85qIVEoj(pm_math_FdNKyaRLqeWhg5tGqF_VYT,
pm_math__jwySfHyx1SXgXJeVWoIzb,pm_math_F2l4p_g4sn02huHNflQjMH);if(
pm_math__LIYjt5pi54rVTuNKI6I5_(pm_math__CTkJ_C1U90PiDqSlWut2a)||
pm_math__J9snrOx2Cp4dD_e3lGtRm(pm_math__CTkJ_C1U90PiDqSlWut2a)){
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(
pm_math_kyWde2KZDLCkemScG8IiFy=0;pm_math_kyWde2KZDLCkemScG8IiFy<
pm_math__0whwiO_wLpmgDjzh3qDNZ;pm_math_kyWde2KZDLCkemScG8IiFy++){
pm_math_kRdbZgju4QKPcmCLNev9n2[pm_math_kyWde2KZDLCkemScG8IiFy].re=
pm_math_k9HpTo0HuFt0gDRVyg17Wc;pm_math_kRdbZgju4QKPcmCLNev9n2[
pm_math_kyWde2KZDLCkemScG8IiFy].im=0.0;}pm_math__0whwiO_wLpmgDjzh3qDNZ=
pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(pm_math_kyWde2KZDLCkemScG8IiFy=0;
pm_math_kyWde2KZDLCkemScG8IiFy<pm_math__0whwiO_wLpmgDjzh3qDNZ;
pm_math_kyWde2KZDLCkemScG8IiFy++){pm_math__Vu43oWQSkpLiuph6ye1KN[
pm_math_kyWde2KZDLCkemScG8IiFy].re=pm_math_k9HpTo0HuFt0gDRVyg17Wc;
pm_math__Vu43oWQSkpLiuph6ye1KN[pm_math_kyWde2KZDLCkemScG8IiFy].im=0.0;}
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(pm_math_kyWde2KZDLCkemScG8IiFy=0;
pm_math_kyWde2KZDLCkemScG8IiFy<pm_math__0whwiO_wLpmgDjzh3qDNZ;
pm_math_kyWde2KZDLCkemScG8IiFy++){pm_math_kJeUz19e49pVaDwcttsZep[
pm_math_kyWde2KZDLCkemScG8IiFy].re=pm_math_k9HpTo0HuFt0gDRVyg17Wc;
pm_math_kJeUz19e49pVaDwcttsZep[pm_math_kyWde2KZDLCkemScG8IiFy].im=0.0;}}else{
pm_math_F85M4pG_wzOGZqvlERykug=false;pm_math__eF5mveiczSq_qps3D6fj_=
pm_math__CTkJ_C1U90PiDqSlWut2a;if((pm_math__CTkJ_C1U90PiDqSlWut2a>0.0)&&(
pm_math__CTkJ_C1U90PiDqSlWut2a<6.7178761075670888E-139)){
pm_math__eF5mveiczSq_qps3D6fj_=6.7178761075670888E-139;
pm_math_F85M4pG_wzOGZqvlERykug=true;pm_math__pwzb3GtrLhhfqqwqtHnjj(
pm_math_FdNKyaRLqeWhg5tGqF_VYT,pm_math__jwySfHyx1SXgXJeVWoIzb,
pm_math__CTkJ_C1U90PiDqSlWut2a,pm_math__eF5mveiczSq_qps3D6fj_,
pm_math_F2l4p_g4sn02huHNflQjMH);}else{if(pm_math__CTkJ_C1U90PiDqSlWut2a>
1.4885657073574029E+138){pm_math__eF5mveiczSq_qps3D6fj_=
1.4885657073574029E+138;pm_math_F85M4pG_wzOGZqvlERykug=true;
pm_math__pwzb3GtrLhhfqqwqtHnjj(pm_math_FdNKyaRLqeWhg5tGqF_VYT,
pm_math__jwySfHyx1SXgXJeVWoIzb,pm_math__CTkJ_C1U90PiDqSlWut2a,
pm_math__eF5mveiczSq_qps3D6fj_,pm_math_F2l4p_g4sn02huHNflQjMH);}}
pm_math_Fqp_Q4lfXKtYfXbj_au4kb=false;pm_math_VnpPAIEy4a0ocm1ufujJN0=
pm_math_k7lTE2xLhk_xdP85qIVEoj(pm_math_FdNKyaRLqeWhg5tGqF_VYT,
pm_math__jwySfHyx1SXgXJeVWoIzb,pm_math_Vqiy96WqvuhCaXm5e_vvT0);
pm_math_k7U6wyp5KghiXiGknB_n6B=pm_math_VnpPAIEy4a0ocm1ufujJN0;if((
pm_math_VnpPAIEy4a0ocm1ufujJN0>0.0)&&(pm_math_VnpPAIEy4a0ocm1ufujJN0<
6.7178761075670888E-139)){pm_math_k7U6wyp5KghiXiGknB_n6B=
6.7178761075670888E-139;pm_math_Fqp_Q4lfXKtYfXbj_au4kb=true;
pm_math__pwzb3GtrLhhfqqwqtHnjj(pm_math_FdNKyaRLqeWhg5tGqF_VYT,
pm_math__jwySfHyx1SXgXJeVWoIzb,pm_math_VnpPAIEy4a0ocm1ufujJN0,
pm_math_k7U6wyp5KghiXiGknB_n6B,pm_math_Vqiy96WqvuhCaXm5e_vvT0);}else{if(
pm_math_VnpPAIEy4a0ocm1ufujJN0>1.4885657073574029E+138){
pm_math_k7U6wyp5KghiXiGknB_n6B=1.4885657073574029E+138;
pm_math_Fqp_Q4lfXKtYfXbj_au4kb=true;pm_math__pwzb3GtrLhhfqqwqtHnjj(
pm_math_FdNKyaRLqeWhg5tGqF_VYT,pm_math__jwySfHyx1SXgXJeVWoIzb,
pm_math_VnpPAIEy4a0ocm1ufujJN0,pm_math_k7U6wyp5KghiXiGknB_n6B,
pm_math_Vqiy96WqvuhCaXm5e_vvT0);}}pm_math__G_5qfTciulGdqw2gjG38D(
pm_math_FdNKyaRLqeWhg5tGqF_VYT,pm_math_F2l4p_g4sn02huHNflQjMH,
pm_math_Vqiy96WqvuhCaXm5e_vvT0,&pm_math_k2AgNEfVSvlhZ5VkmS6QH2,&
pm_math__1J0baDSh1W3jqPn9PkTOT,pm_math__qLHk6daYiGnXenMNt2kR_);
pm_math__1eja2CXWF0SdXzvz5uav_(pm_math_FdNKyaRLqeWhg5tGqF_VYT,
pm_math__jwySfHyx1SXgXJeVWoIzb,pm_math_Vqiy96WqvuhCaXm5e_vvT0,
pm_math_k2AgNEfVSvlhZ5VkmS6QH2,pm_math__1J0baDSh1W3jqPn9PkTOT,n,
pm_math_VHUYV1kdST0efLHvpiBBXm,pm_math_VRZCD_UL_ESThy75dC9J8D);for(
pm_math_kwrB3ZoKf7OufTHWaHJV7a=pm_math_k2AgNEfVSvlhZ5VkmS6QH2-1;
pm_math_kwrB3ZoKf7OufTHWaHJV7a<pm_math__1J0baDSh1W3jqPn9PkTOT;
pm_math_kwrB3ZoKf7OufTHWaHJV7a++){pm_math__H7y_KVNFQhie13GEb_pt0=
pm_math_kwrB3ZoKf7OufTHWaHJV7a+2;pm_math__0whwiO_wLpmgDjzh3qDNZ=(
pm_math_kwrB3ZoKf7OufTHWaHJV7a-pm_math_k2AgNEfVSvlhZ5VkmS6QH2)+1;
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re=pm_math_VHUYV1kdST0efLHvpiBBXm[
pm_math__0whwiO_wLpmgDjzh3qDNZ].re;pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im= -
pm_math_VHUYV1kdST0efLHvpiBBXm[pm_math__0whwiO_wLpmgDjzh3qDNZ].im;for(
pm_math_kyp6uAyJE40UVuAQNEYzS1=pm_math_k2AgNEfVSvlhZ5VkmS6QH2;
pm_math_kyp6uAyJE40UVuAQNEYzS1<=n;pm_math_kyp6uAyJE40UVuAQNEYzS1++){
pm_math_V2ngbolOwr0raTlCR3nzE5=pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re;pm_math_kQlKTq1F3spqiixck2H6s7= -
pm_math_F2l4p_g4sn02huHNflQjMH[pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im;for(
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math__H7y_KVNFQhie13GEb_pt0;
pm_math__0whwiO_wLpmgDjzh3qDNZ<=pm_math__1J0baDSh1W3jqPn9PkTOT;
pm_math__0whwiO_wLpmgDjzh3qDNZ++){pm_math_V2ngbolOwr0raTlCR3nzE5+=
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].re+
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].im;
pm_math_kQlKTq1F3spqiixck2H6s7+=pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math__0whwiO_wLpmgDjzh3qDNZ+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math__0whwiO_wLpmgDjzh3qDNZ+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].im-pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math__0whwiO_wLpmgDjzh3qDNZ+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math__0whwiO_wLpmgDjzh3qDNZ+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].re;}pm_math_FFZbGh27ya8eem_J_hUtAZ=
pm_math_V2ngbolOwr0raTlCR3nzE5;pm_math_kQlKTq1F3spqiixck2H6s7= -
pm_math_kQlKTq1F3spqiixck2H6s7;pm_math_V2ngbolOwr0raTlCR3nzE5=
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_FFZbGh27ya8eem_J_hUtAZ-
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_kQlKTq1F3spqiixck2H6s7;
pm_math_kQlKTq1F3spqiixck2H6s7=pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_kQlKTq1F3spqiixck2H6s7+pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_FFZbGh27ya8eem_J_hUtAZ;pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re-=pm_math_V2ngbolOwr0raTlCR3nzE5;
pm_math_F2l4p_g4sn02huHNflQjMH[pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im-=
pm_math_kQlKTq1F3spqiixck2H6s7;for(pm_math__0whwiO_wLpmgDjzh3qDNZ=
pm_math__H7y_KVNFQhie13GEb_pt0;pm_math__0whwiO_wLpmgDjzh3qDNZ<=
pm_math__1J0baDSh1W3jqPn9PkTOT;pm_math__0whwiO_wLpmgDjzh3qDNZ++){
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re-=
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].re*
pm_math_V2ngbolOwr0raTlCR3nzE5-pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math__0whwiO_wLpmgDjzh3qDNZ+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].im*pm_math_kQlKTq1F3spqiixck2H6s7;
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im-=
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].re*
pm_math_kQlKTq1F3spqiixck2H6s7+pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math__0whwiO_wLpmgDjzh3qDNZ+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kwrB3ZoKf7OufTHWaHJV7a)-1].im*pm_math_V2ngbolOwr0raTlCR3nzE5;}}}
pm_math_kJrcOmJJ_wWYfH5M5R0Vey=pm_math_FdNKyaRLqeWhg5tGqF_VYT;
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(pm_math_kyWde2KZDLCkemScG8IiFy=0;
pm_math_kyWde2KZDLCkemScG8IiFy<pm_math__0whwiO_wLpmgDjzh3qDNZ;
pm_math_kyWde2KZDLCkemScG8IiFy++){pm_math_VS3xMd4pLil0i5cxPD0ErK[
pm_math_kyWde2KZDLCkemScG8IiFy]=0;}if(pm_math_FdNKyaRLqeWhg5tGqF_VYT>0){for(
pm_math__0whwiO_wLpmgDjzh3qDNZ=0;pm_math__0whwiO_wLpmgDjzh3qDNZ<
pm_math_kJrcOmJJ_wWYfH5M5R0Vey;pm_math__0whwiO_wLpmgDjzh3qDNZ++){
pm_math_VS3xMd4pLil0i5cxPD0ErK[pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math__0whwiO_wLpmgDjzh3qDNZ]=1;}}
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_FdNKyaRLqeWhg5tGqF_VYT;for(pm_math_kyWde2KZDLCkemScG8IiFy=0;
pm_math_kyWde2KZDLCkemScG8IiFy<pm_math__0whwiO_wLpmgDjzh3qDNZ;
pm_math_kyWde2KZDLCkemScG8IiFy++){pm_math_kJeUz19e49pVaDwcttsZep[
pm_math_kyWde2KZDLCkemScG8IiFy].re=pm_math_VS3xMd4pLil0i5cxPD0ErK[
pm_math_kyWde2KZDLCkemScG8IiFy];pm_math_kJeUz19e49pVaDwcttsZep[
pm_math_kyWde2KZDLCkemScG8IiFy].im=0.0;}if(pm_math_FdNKyaRLqeWhg5tGqF_VYT>1){
pm_math_F81QwThDphpXjqsd6ML4yG=((pm_math_FdNKyaRLqeWhg5tGqF_VYT!=0)&&(
pm_math__jwySfHyx1SXgXJeVWoIzb!=0));if(pm_math_F81QwThDphpXjqsd6ML4yG){for(
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_k2AgNEfVSvlhZ5VkmS6QH2;
pm_math__0whwiO_wLpmgDjzh3qDNZ<pm_math__1J0baDSh1W3jqPn9PkTOT;
pm_math__0whwiO_wLpmgDjzh3qDNZ++){pm_math__H7y_KVNFQhie13GEb_pt0=
pm_math__0whwiO_wLpmgDjzh3qDNZ+1;for(pm_math_kyWde2KZDLCkemScG8IiFy=
pm_math__H7y_KVNFQhie13GEb_pt0;pm_math_kyWde2KZDLCkemScG8IiFy<=
pm_math__1J0baDSh1W3jqPn9PkTOT;pm_math_kyWde2KZDLCkemScG8IiFy++){
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math__0whwiO_wLpmgDjzh3qDNZ-1))-1].re=0.0;
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math__0whwiO_wLpmgDjzh3qDNZ-1))-1].im=0.0;}
}}if(pm_math__1J0baDSh1W3jqPn9PkTOT>=pm_math_k2AgNEfVSvlhZ5VkmS6QH2+2){for(
pm_math__0whwiO_wLpmgDjzh3qDNZ=pm_math_k2AgNEfVSvlhZ5VkmS6QH2-1;
pm_math__0whwiO_wLpmgDjzh3qDNZ+1<pm_math__1J0baDSh1W3jqPn9PkTOT-1;
pm_math__0whwiO_wLpmgDjzh3qDNZ++){pm_math__H7y_KVNFQhie13GEb_pt0=
pm_math__0whwiO_wLpmgDjzh3qDNZ+2;for(pm_math_kyWde2KZDLCkemScG8IiFy=
pm_math__1J0baDSh1W3jqPn9PkTOT-1;pm_math_kyWde2KZDLCkemScG8IiFy+1>
pm_math__0whwiO_wLpmgDjzh3qDNZ+2;pm_math_kyWde2KZDLCkemScG8IiFy--){
pm_math__wt7gD7RMvKZaeZRgAma6O(pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ)-1],pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ],&pm_math_FFZbGh27ya8eem_J_hUtAZ,&
pm_math_Fk2O4u6vQUpibmbv8Kjgnn,&pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ)-1]);pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ].re=0.0;pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ].im=0.0;for(pm_math_kyp6uAyJE40UVuAQNEYzS1=
pm_math__H7y_KVNFQhie13GEb_pt0;pm_math_kyp6uAyJE40UVuAQNEYzS1<=
pm_math_kJrcOmJJ_wWYfH5M5R0Vey;pm_math_kyp6uAyJE40UVuAQNEYzS1++){
pm_math_V2ngbolOwr0raTlCR3nzE5=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re+(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re-pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_F2l4p_g4sn02huHNflQjMH[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im);
pm_math_kQlKTq1F3spqiixck2H6s7=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im+(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im+pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_F2l4p_g4sn02huHNflQjMH[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re);
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im;pm_math_F32Ql82vv6pW_PYIdpkFQ0=
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re;
pm_math_F2l4p_g4sn02huHNflQjMH[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re-(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re+
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im);pm_math_F2l4p_g4sn02huHNflQjMH[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_F2l4p_g4sn02huHNflQjMH[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im-(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_F32Ql82vv6pW_PYIdpkFQ0);
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re=
pm_math_V2ngbolOwr0raTlCR3nzE5;pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im=pm_math_kQlKTq1F3spqiixck2H6s7;}if(
pm_math_F81QwThDphpXjqsd6ML4yG){for(pm_math_kyp6uAyJE40UVuAQNEYzS1=
pm_math_kyWde2KZDLCkemScG8IiFy;pm_math_kyp6uAyJE40UVuAQNEYzS1<=
pm_math_kJrcOmJJ_wWYfH5M5R0Vey;pm_math_kyp6uAyJE40UVuAQNEYzS1++){
pm_math_V2ngbolOwr0raTlCR3nzE5=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re+(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re-pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im);
pm_math_kQlKTq1F3spqiixck2H6s7=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im+(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im+pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re);
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im;pm_math_F32Ql82vv6pW_PYIdpkFQ0=
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re;
pm_math_Vqiy96WqvuhCaXm5e_vvT0[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].re-(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re+
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im);pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1)].im-(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_F32Ql82vv6pW_PYIdpkFQ0);
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kyWde2KZDLCkemScG8IiFy+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].re=
pm_math_V2ngbolOwr0raTlCR3nzE5;pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyp6uAyJE40UVuAQNEYzS1-1))-1].im=pm_math_kQlKTq1F3spqiixck2H6s7;}
pm_math__wt7gD7RMvKZaeZRgAma6O(pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy],pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1)],&pm_math_FFZbGh27ya8eem_J_hUtAZ,&
pm_math_Fk2O4u6vQUpibmbv8Kjgnn,&pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy]);pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1)].re=0.0;pm_math_Vqiy96WqvuhCaXm5e_vvT0[
pm_math_kyWde2KZDLCkemScG8IiFy+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1)].im=0.0;for(pm_math_kwrB3ZoKf7OufTHWaHJV7a=1
;pm_math_kwrB3ZoKf7OufTHWaHJV7a<=pm_math_kyWde2KZDLCkemScG8IiFy;
pm_math_kwrB3ZoKf7OufTHWaHJV7a++){pm_math_V2ngbolOwr0raTlCR3nzE5=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re+(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re-
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im);pm_math_kQlKTq1F3spqiixck2H6s7=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].im+(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im+
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re);pm_math_FzyLWRgau0pMYq2XSI3ETL=
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].im;
pm_math_F32Ql82vv6pW_PYIdpkFQ0=pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re;pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re-(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re+pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].im);
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im-(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_FzyLWRgau0pMYq2XSI3ETL-pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_F32Ql82vv6pW_PYIdpkFQ0);pm_math_Vqiy96WqvuhCaXm5e_vvT0[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re=pm_math_V2ngbolOwr0raTlCR3nzE5;
pm_math_Vqiy96WqvuhCaXm5e_vvT0[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].im=
pm_math_kQlKTq1F3spqiixck2H6s7;}}else{pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re= -
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re;pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im= -
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im;}for(pm_math_kwrB3ZoKf7OufTHWaHJV7a=1;
pm_math_kwrB3ZoKf7OufTHWaHJV7a<=pm_math__1J0baDSh1W3jqPn9PkTOT;
pm_math_kwrB3ZoKf7OufTHWaHJV7a++){pm_math_V2ngbolOwr0raTlCR3nzE5=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re+(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re-
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im);pm_math_kQlKTq1F3spqiixck2H6s7=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].im+(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im+
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re);pm_math_FzyLWRgau0pMYq2XSI3ETL=
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].im;
pm_math_F32Ql82vv6pW_PYIdpkFQ0=pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re;pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re-(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re+pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].im);
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im-(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_FzyLWRgau0pMYq2XSI3ETL-pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_F32Ql82vv6pW_PYIdpkFQ0);pm_math_F2l4p_g4sn02huHNflQjMH[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re=pm_math_V2ngbolOwr0raTlCR3nzE5;
pm_math_F2l4p_g4sn02huHNflQjMH[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].im=
pm_math_kQlKTq1F3spqiixck2H6s7;}for(pm_math_kwrB3ZoKf7OufTHWaHJV7a=1;
pm_math_kwrB3ZoKf7OufTHWaHJV7a<=pm_math_kJrcOmJJ_wWYfH5M5R0Vey;
pm_math_kwrB3ZoKf7OufTHWaHJV7a++){pm_math_V2ngbolOwr0raTlCR3nzE5=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re+(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re-
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im);pm_math_kQlKTq1F3spqiixck2H6s7=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].im+(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im+
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re);pm_math_FzyLWRgau0pMYq2XSI3ETL=
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].re;
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re=
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].re-(pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].re+
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].im);pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*(
pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im=pm_math_FFZbGh27ya8eem_J_hUtAZ*
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*(pm_math_kyWde2KZDLCkemScG8IiFy-1))-1].im-(
pm_math_Fk2O4u6vQUpibmbv8Kjgnn.re*pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].im-pm_math_Fk2O4u6vQUpibmbv8Kjgnn.im*
pm_math_FzyLWRgau0pMYq2XSI3ETL);pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math_kwrB3ZoKf7OufTHWaHJV7a+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math_kyWde2KZDLCkemScG8IiFy)-1].re=pm_math_V2ngbolOwr0raTlCR3nzE5;
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyWde2KZDLCkemScG8IiFy)-1].im=
pm_math_kQlKTq1F3spqiixck2H6s7;}}}}}pm_math_F9lhEtqCeltji1XW4PRkXt(
pm_math_FdNKyaRLqeWhg5tGqF_VYT,pm_math__jwySfHyx1SXgXJeVWoIzb,
pm_math_F2l4p_g4sn02huHNflQjMH,pm_math_Vqiy96WqvuhCaXm5e_vvT0,
pm_math_k2AgNEfVSvlhZ5VkmS6QH2,pm_math__1J0baDSh1W3jqPn9PkTOT,
pm_math_kJeUz19e49pVaDwcttsZep,pm_math_kSEW12lLld4uY1T_UcY6kY,
pm_math_kRdbZgju4QKPcmCLNev9n2,pm_math__Vu43oWQSkpLiuph6ye1KN);if(*
pm_math_kSEW12lLld4uY1T_UcY6kY==0){pm_math_VRxuc3uSEyOgbqgYyEw9PS(
pm_math_FdNKyaRLqeWhg5tGqF_VYT,pm_math_F2l4p_g4sn02huHNflQjMH,
pm_math_Vqiy96WqvuhCaXm5e_vvT0,pm_math_kJeUz19e49pVaDwcttsZep,
pm_math_Fo1tUR18sIdue1E1QXuOnL,pm_math___7SXc4Q_w8saDIIf2ecjp,
pm_math_ktFLct2wbuxD_5iTvRiZEZ,pm_math_kHM1aMQ_rJdeheUxTze_oV);
pm_math_kJrcOmJJ_wWYfH5M5R0Vey=pm_math_FdNKyaRLqeWhg5tGqF_VYT;
pm_math_VLHhnPUiNQpve5VIL9P3O9=pm_math_FdNKyaRLqeWhg5tGqF_VYT-1;if(
pm_math_k2AgNEfVSvlhZ5VkmS6QH2>1){for(pm_math_kwrB3ZoKf7OufTHWaHJV7a=
pm_math_k2AgNEfVSvlhZ5VkmS6QH2-2;pm_math_kwrB3ZoKf7OufTHWaHJV7a+1>=1;
pm_math_kwrB3ZoKf7OufTHWaHJV7a--){pm_math__0whwiO_wLpmgDjzh3qDNZ=
pm_math__qLHk6daYiGnXenMNt2kR_[pm_math_kwrB3ZoKf7OufTHWaHJV7a]-1;if(
pm_math__qLHk6daYiGnXenMNt2kR_[pm_math_kwrB3ZoKf7OufTHWaHJV7a]!=
pm_math_kwrB3ZoKf7OufTHWaHJV7a+1){for(pm_math_kyp6uAyJE40UVuAQNEYzS1=0;
pm_math_kyp6uAyJE40UVuAQNEYzS1<=pm_math_VLHhnPUiNQpve5VIL9P3O9;
pm_math_kyp6uAyJE40UVuAQNEYzS1++){pm_math_Fk2O4u6vQUpibmbv8Kjgnn=
pm_math_kJeUz19e49pVaDwcttsZep[pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1];
pm_math_kJeUz19e49pVaDwcttsZep[pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1]=
pm_math_kJeUz19e49pVaDwcttsZep[pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1];
pm_math_kJeUz19e49pVaDwcttsZep[pm_math__0whwiO_wLpmgDjzh3qDNZ+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1]=
pm_math_Fk2O4u6vQUpibmbv8Kjgnn;}}}}if(pm_math__1J0baDSh1W3jqPn9PkTOT<
pm_math_kJrcOmJJ_wWYfH5M5R0Vey){pm_math_kyWde2KZDLCkemScG8IiFy=
pm_math__1J0baDSh1W3jqPn9PkTOT+1;for(pm_math_kwrB3ZoKf7OufTHWaHJV7a=
pm_math_kyWde2KZDLCkemScG8IiFy;pm_math_kwrB3ZoKf7OufTHWaHJV7a<=
pm_math_kJrcOmJJ_wWYfH5M5R0Vey;pm_math_kwrB3ZoKf7OufTHWaHJV7a++){
pm_math__H7y_KVNFQhie13GEb_pt0=pm_math__qLHk6daYiGnXenMNt2kR_[
pm_math_kwrB3ZoKf7OufTHWaHJV7a-1];if(pm_math__H7y_KVNFQhie13GEb_pt0!=
pm_math_kwrB3ZoKf7OufTHWaHJV7a){for(pm_math_kyp6uAyJE40UVuAQNEYzS1=0;
pm_math_kyp6uAyJE40UVuAQNEYzS1<=pm_math_VLHhnPUiNQpve5VIL9P3O9;
pm_math_kyp6uAyJE40UVuAQNEYzS1++){pm_math_Fk2O4u6vQUpibmbv8Kjgnn=
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1)-1];
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math_kwrB3ZoKf7OufTHWaHJV7a+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1)-1]=
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math__H7y_KVNFQhie13GEb_pt0+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1)-1];
pm_math_kJeUz19e49pVaDwcttsZep[(pm_math__H7y_KVNFQhie13GEb_pt0+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math_kyp6uAyJE40UVuAQNEYzS1)-1]=
pm_math_Fk2O4u6vQUpibmbv8Kjgnn;}}}}for(pm_math__0whwiO_wLpmgDjzh3qDNZ=0;
pm_math__0whwiO_wLpmgDjzh3qDNZ<n;pm_math__0whwiO_wLpmgDjzh3qDNZ++){
pm_math_FFZbGh27ya8eem_J_hUtAZ=fabs(pm_math_kJeUz19e49pVaDwcttsZep[
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math__0whwiO_wLpmgDjzh3qDNZ].re)+fabs(
pm_math_kJeUz19e49pVaDwcttsZep[pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ].im);if(n>1){for(pm_math__H7y_KVNFQhie13GEb_pt0
=0;pm_math__H7y_KVNFQhie13GEb_pt0<=n-2;pm_math__H7y_KVNFQhie13GEb_pt0++){
pm_math_FzyLWRgau0pMYq2XSI3ETL=fabs(pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math__H7y_KVNFQhie13GEb_pt0+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ)+1].re)+fabs(pm_math_kJeUz19e49pVaDwcttsZep[(
pm_math__H7y_KVNFQhie13GEb_pt0+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ)+1].im);if(pm_math_FzyLWRgau0pMYq2XSI3ETL>
pm_math_FFZbGh27ya8eem_J_hUtAZ){pm_math_FFZbGh27ya8eem_J_hUtAZ=
pm_math_FzyLWRgau0pMYq2XSI3ETL;}}}if(pm_math_FFZbGh27ya8eem_J_hUtAZ>=
6.7178761075670888E-139){pm_math_FFZbGh27ya8eem_J_hUtAZ=1.0/
pm_math_FFZbGh27ya8eem_J_hUtAZ;for(pm_math__H7y_KVNFQhie13GEb_pt0=0;
pm_math__H7y_KVNFQhie13GEb_pt0<n;pm_math__H7y_KVNFQhie13GEb_pt0++){
pm_math_kJeUz19e49pVaDwcttsZep[pm_math__H7y_KVNFQhie13GEb_pt0+
pm_math_FdNKyaRLqeWhg5tGqF_VYT*pm_math__0whwiO_wLpmgDjzh3qDNZ].re*=
pm_math_FFZbGh27ya8eem_J_hUtAZ;pm_math_kJeUz19e49pVaDwcttsZep[
pm_math__H7y_KVNFQhie13GEb_pt0+pm_math_FdNKyaRLqeWhg5tGqF_VYT*
pm_math__0whwiO_wLpmgDjzh3qDNZ].im*=pm_math_FFZbGh27ya8eem_J_hUtAZ;}}}if(
pm_math_F85M4pG_wzOGZqvlERykug){pm_math_V45aqmxcmhdvWeNEn2nMVd(
pm_math_FdNKyaRLqeWhg5tGqF_VYT,pm_math__eF5mveiczSq_qps3D6fj_,
pm_math__CTkJ_C1U90PiDqSlWut2a,pm_math_kRdbZgju4QKPcmCLNev9n2);}if(
pm_math_Fqp_Q4lfXKtYfXbj_au4kb){pm_math_V45aqmxcmhdvWeNEn2nMVd(
pm_math_FdNKyaRLqeWhg5tGqF_VYT,pm_math_k7U6wyp5KghiXiGknB_n6B,
pm_math_VnpPAIEy4a0ocm1ufujJN0,pm_math__Vu43oWQSkpLiuph6ye1KN);}}}}}
