#include "stddef.h"
#include "stdlib.h"
#include "pm_std.h"
extern double pm_math_V5x94lnJ1CdciLh0_Ap8Ng(double
pm_math_VRbT1WwZjwW6f5YGBCFuaD,double pm_math__d7LC10lP38OY1VXN_tFqb,double
pm_math__cyyv8HsdO_Rh9J_iGtn9V);
#include "pm_std.h"
extern void pm_math_V4wY5inRPrGJ_q94UMd56c(const int
pm_math_FdNKyaRLqeWhg5tGqF_VYT,const int pm_math__jwySfHyx1SXgXJeVWoIzb,const
real_T*pm_math_F2l4p_g4sn02huHNflQjMH,const real_T*
pm_math_Vqiy96WqvuhCaXm5e_vvT0,creal_T*pm_math_kJeUz19e49pVaDwcttsZep,creal_T*
pm_math_kyfq6L_eQbdYcPuOovpRDW,creal_T*pm_math_kXii4Miq3Y_ShPn9EHS3D5,creal_T*
pm_math_FYAUa2zJy8Cah1YsdPJok5,creal_T*pm_math__Vu43oWQSkpLiuph6ye1KN,creal_T*
pm_math_VHUYV1kdST0efLHvpiBBXm,creal_T*pm_math_VRZCD_UL_ESThy75dC9J8D,creal_T*
pm_math_Fo1tUR18sIdue1E1QXuOnL,creal_T*pm_math___7SXc4Q_w8saDIIf2ecjp,real_T*
pm_math_ktFLct2wbuxD_5iTvRiZEZ,real_T*pm_math_kHM1aMQ_rJdeheUxTze_oV,int32_T*
pm_math__qLHk6daYiGnXenMNt2kR_,int8_T*pm_math_VS3xMd4pLil0i5cxPD0ErK);
#include "pm_std.h"
extern real_T pm_math_V6hUjCc3PiCAauyMwJP5nb;extern real_T
pm_math_Vco4W7EuZu4k_1cAN9SDVG;extern real_T pm_math_k9HpTo0HuFt0gDRVyg17Wc;
extern real32_T pm_math__JOzYwXJOmSsiaZ6WMnnZZ;extern real32_T
pm_math_VaGr_igKLHx0bDW9g54I6v;extern real32_T pm_math_kZu0y5Pv4G8tg1EE_V6tGP;
extern void pm_math_F3OoZ1Weno85bujDCIyv_c(void);extern boolean_T
pm_math__LIYjt5pi54rVTuNKI6I5_(real_T pm_math_kg4CyRgbu6OdeewZOel7Qx);extern
boolean_T pm_math_VK2BuaMRCmOxjLjqE4tZMh(real32_T
pm_math_kg4CyRgbu6OdeewZOel7Qx);extern boolean_T pm_math__J9snrOx2Cp4dD_e3lGtRm
(real_T pm_math_kg4CyRgbu6OdeewZOel7Qx);extern boolean_T
pm_math_kwH13YYrpKtAbDLZ9Q_8I9(real32_T pm_math_kg4CyRgbu6OdeewZOel7Qx);
#include "math.h"
double pm_math_V5x94lnJ1CdciLh0_Ap8Ng(double pm_math_VRbT1WwZjwW6f5YGBCFuaD,
double pm_math__d7LC10lP38OY1VXN_tFqb,double pm_math__cyyv8HsdO_Rh9J_iGtn9V){
double pm_math_FzyLWRgau0pMYq2XSI3ETL;double a;double b;double
pm_math_FFZbGh27ya8eem_J_hUtAZ;a=fabs(pm_math_VRbT1WwZjwW6f5YGBCFuaD);b=fabs(
pm_math__d7LC10lP38OY1VXN_tFqb);pm_math_FFZbGh27ya8eem_J_hUtAZ=fabs(
pm_math__cyyv8HsdO_Rh9J_iGtn9V);pm_math_FzyLWRgau0pMYq2XSI3ETL=a;if(b>
pm_math_FzyLWRgau0pMYq2XSI3ETL){pm_math_FzyLWRgau0pMYq2XSI3ETL=b;}if(
pm_math_FFZbGh27ya8eem_J_hUtAZ>pm_math_FzyLWRgau0pMYq2XSI3ETL){
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_FFZbGh27ya8eem_J_hUtAZ;}if((
pm_math_FzyLWRgau0pMYq2XSI3ETL>0.0)&&(!pm_math__LIYjt5pi54rVTuNKI6I5_(
pm_math_FzyLWRgau0pMYq2XSI3ETL))){a/=pm_math_FzyLWRgau0pMYq2XSI3ETL;b/=
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math_FFZbGh27ya8eem_J_hUtAZ/=
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math_FzyLWRgau0pMYq2XSI3ETL*=sqrt((a*a+
pm_math_FFZbGh27ya8eem_J_hUtAZ*pm_math_FFZbGh27ya8eem_J_hUtAZ)+b*b);}else{
pm_math_FzyLWRgau0pMYq2XSI3ETL=(a+b)+pm_math_FFZbGh27ya8eem_J_hUtAZ;}return
pm_math_FzyLWRgau0pMYq2XSI3ETL;}
