#include "pm_std.h"
#include "string.h"
#include "math.h"
#include "pm_std.h"
real_T pm_math_Vector3_dot_ra(const real_T*pm_math__AuaKMC5koOPbXxPi_MZvt,
const real_T*pm_math_kNtPmLll5l8eiqwtk5kfJv);void pm_math_Vector3_cross_ra(
const real_T*pm_math__AuaKMC5koOPbXxPi_MZvt,const real_T*
pm_math_kNtPmLll5l8eiqwtk5kfJv,real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Vector3_compOrthogonalBasis_ra(const real_T*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T*pm_math_kwrB3ZoKf7OufTHWaHJV7a,real_T*
pm_math_kyp6uAyJE40UVuAQNEYzS1,real_T*pm_math_V2__YrimeI4E_yWnhKofpy);void
pm_math_Quaternion_compose_ra(const real_T*pm_math_FbCdebDtDIhMduMKWA8Khy,
const real_T*pm_math_krgkQdg3ZZ_0ded42Fk_8r,real_T*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Quaternion_composeInverse_ra(
const real_T*pm_math_FbCdebDtDIhMduMKWA8Khy,const real_T*
pm_math_krgkQdg3ZZ_0ded42Fk_8r,real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Quaternion_inverseCompose_ra(const real_T*
pm_math_FbCdebDtDIhMduMKWA8Khy,const real_T*pm_math_krgkQdg3ZZ_0ded42Fk_8r,
real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Quaternion_xform_ra(const
real_T*pm_math_VnD_HGFKVUOWdDAWvZhyEb,const real_T*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Quaternion_inverseXform_ra(const real_T*pm_math_VnD_HGFKVUOWdDAWvZhyEb
,const real_T*pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Quaternion_compDeriv_ra(const
real_T*pm_math_VnD_HGFKVUOWdDAWvZhyEb,const real_T*
pm_math_kvL2QWFrSblY_eznRgCz87,real_T*pm_math_FGJfoQhjnH_kdaWooDAepH);void
pm_math_Quaternion_Matrix3x3Ctor_ra(const real_T*
pm_math_FqUCZrSGGNOuePgRr82o_8,real_T*pm_math_VnD_HGFKVUOWdDAWvZhyEb);void
pm_math_Matrix3x3_compose_ra(const real_T*pm_math_Fcuud3IN0odMZi54a1R_8f,const
real_T*pm_math__09m2ugY6U_OXH9Il_a7Bj,real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);
void pm_math_Matrix3x3_composeTranspose_ra(const real_T*
pm_math_Fcuud3IN0odMZi54a1R_8f,const real_T*pm_math__09m2ugY6U_OXH9Il_a7Bj,
real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Matrix3x3_transposeCompose_ra(const real_T*
pm_math_Fcuud3IN0odMZi54a1R_8f,const real_T*pm_math__09m2ugY6U_OXH9Il_a7Bj,
real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Matrix3x3_preCross_ra(
const real_T*pm_math_F2l4p_g4sn02huHNflQjMH,const real_T*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Matrix3x3_postCross_ra(const real_T*pm_math_F2l4p_g4sn02huHNflQjMH,
const real_T*pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Matrix3x3_xform_ra(const real_T*
pm_math_F2l4p_g4sn02huHNflQjMH,const real_T*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Matrix3x3_transposeXform_ra
(const real_T*pm_math_F2l4p_g4sn02huHNflQjMH,const real_T*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Matrix3x3_minRotation_ra(const real_T*pm_math_VnD_HGFKVUOWdDAWvZhyEb,
real_T*pm_math_FqUCZrSGGNOuePgRr82o_8,int pm_math_kbzF46WM0FtKWeE0s7WR95[3]);
struct pm_math_Va7rvzSwRbpB_iIiuSF8h_{real_T x;real_T
pm_math_FzyLWRgau0pMYq2XSI3ETL;real_T pm_math_FBDi_PCg670TjHgJTNPcHr;};typedef
struct pm_math_Va7rvzSwRbpB_iIiuSF8h_ pm_math_FJDxOUSymMGic5lC7ZhrnL;struct
pm_math_VQiPk6I_S_0teiYbT1MBSN{real_T pm_math_FQferGZUKft3_i5GvYy4Oy;real_T x;
real_T pm_math_FzyLWRgau0pMYq2XSI3ETL;real_T pm_math_FBDi_PCg670TjHgJTNPcHr;};
typedef struct pm_math_VQiPk6I_S_0teiYbT1MBSN pm_math__3md8_onIiO6heiNB5D3_3;
struct pm_math_k5mHxu1pFy4YaeyeIGf5bY{real_T pm_math_V5gSkPeCSkdzZ1xMyj2v7U,
pm_math__D1iFBxPf38RWiveIR1Iip,pm_math__hPet7vW5h0Zi1uUdLa_LW;real_T
pm_math_kdB_LoVum6OHeDEkf0n58b,pm_math__tdIR85BSYdzha7Mb8qhKj,
pm_math__WnakhFnl24_bX0NhL6CLW;real_T pm_math_FnXzm1MLmt04dPIhRbN5SW,
pm_math_VgeldyT0dAtjeHo3kvxpdi,pm_math_F3LgZdApwMGziTfUlk6dzB;};typedef struct
pm_math_k5mHxu1pFy4YaeyeIGf5bY pm_math_komYPTPtib40juqhd0nJcN;struct
pm_math__sD2GKinhS_qYTF_z8BajY{pm_math__3md8_onIiO6heiNB5D3_3
pm_math_VnD_HGFKVUOWdDAWvZhyEb;pm_math_FJDxOUSymMGic5lC7ZhrnL
pm_math_F32Ql82vv6pW_PYIdpkFQ0;};typedef struct pm_math__sD2GKinhS_qYTF_z8BajY
pm_math_k4kL9Om6RgxTZqdxJRM51B;struct pm_math__CEhElfLt9_7aqLsGROeDF{
pm_math_FJDxOUSymMGic5lC7ZhrnL pm_math_FN28mzn7A2hvYLPTU_L4bt;
pm_math_FJDxOUSymMGic5lC7ZhrnL pm_math_k61dA_LqfI4EY1W2W1B1mA;};typedef struct
pm_math__CEhElfLt9_7aqLsGROeDF pm_math_kNq2SpAav5tbb5Yx_VSirx;void
pm_math_Vector3_add(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__AuaKMC5koOPbXxPi_MZvt,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_kNtPmLll5l8eiqwtk5kfJv,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_subtract(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__AuaKMC5koOPbXxPi_MZvt,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kNtPmLll5l8eiqwtk5kfJv,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Vector3_negate(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_scale(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T
pm_math_FQferGZUKft3_i5GvYy4Oy,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_divide(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T
pm_math_FQferGZUKft3_i5GvYy4Oy,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_guardedDivide(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T
pm_math_FQferGZUKft3_i5GvYy4Oy,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);real_T pm_math_Vector3_norm(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ);void
pm_math_Vector3_unit(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_guardedUnit(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4);real_T
pm_math_Vector3_dot(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__AuaKMC5koOPbXxPi_MZvt,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_kNtPmLll5l8eiqwtk5kfJv);void pm_math_Vector3_cross(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__AuaKMC5koOPbXxPi_MZvt,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kNtPmLll5l8eiqwtk5kfJv,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Vector3_compOrthogonalBasis(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_kwrB3ZoKf7OufTHWaHJV7a,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_kyp6uAyJE40UVuAQNEYzS1,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_V2__YrimeI4E_yWnhKofpy);void pm_math_Quaternion_compose(const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_FbCdebDtDIhMduMKWA8Khy,const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_krgkQdg3ZZ_0ded42Fk_8r,
pm_math__3md8_onIiO6heiNB5D3_3*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Quaternion_composeInverse(const pm_math__3md8_onIiO6heiNB5D3_3*
pm_math_FbCdebDtDIhMduMKWA8Khy,const pm_math__3md8_onIiO6heiNB5D3_3*
pm_math_krgkQdg3ZZ_0ded42Fk_8r,pm_math__3md8_onIiO6heiNB5D3_3*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Quaternion_inverseCompose(const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_FbCdebDtDIhMduMKWA8Khy,const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_krgkQdg3ZZ_0ded42Fk_8r,
pm_math__3md8_onIiO6heiNB5D3_3*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Quaternion_xform(const pm_math__3md8_onIiO6heiNB5D3_3*
pm_math_VnD_HGFKVUOWdDAWvZhyEb,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Quaternion_inverseXform(const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_VnD_HGFKVUOWdDAWvZhyEb,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Quaternion_Matrix3x3Ctor(const pm_math_komYPTPtib40juqhd0nJcN*
pm_math_FqUCZrSGGNOuePgRr82o_8,pm_math__3md8_onIiO6heiNB5D3_3*
pm_math_VnD_HGFKVUOWdDAWvZhyEb);void pm_math_Matrix3x3_compose(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_Fcuud3IN0odMZi54a1R_8f,const
pm_math_komYPTPtib40juqhd0nJcN*pm_math__09m2ugY6U_OXH9Il_a7Bj,
pm_math_komYPTPtib40juqhd0nJcN*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Matrix3x3_composeTranspose(const pm_math_komYPTPtib40juqhd0nJcN*
pm_math_Fcuud3IN0odMZi54a1R_8f,const pm_math_komYPTPtib40juqhd0nJcN*
pm_math__09m2ugY6U_OXH9Il_a7Bj,pm_math_komYPTPtib40juqhd0nJcN*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Matrix3x3_transposeCompose(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_Fcuud3IN0odMZi54a1R_8f,const
pm_math_komYPTPtib40juqhd0nJcN*pm_math__09m2ugY6U_OXH9Il_a7Bj,
pm_math_komYPTPtib40juqhd0nJcN*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Matrix3x3_preCross(const pm_math_komYPTPtib40juqhd0nJcN*
pm_math_F2l4p_g4sn02huHNflQjMH,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_komYPTPtib40juqhd0nJcN*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Matrix3x3_postCross(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_F2l4p_g4sn02huHNflQjMH,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_komYPTPtib40juqhd0nJcN*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Matrix3x3_xform(const pm_math_komYPTPtib40juqhd0nJcN*
pm_math_F2l4p_g4sn02huHNflQjMH,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Matrix3x3_transposeXform(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_F2l4p_g4sn02huHNflQjMH,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Transform3_compose(const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math__yWh8B7tCCdhiXMhhHUqbN,const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math_FGPQyC36Ly4PgaEVTyCKbe,pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Transform3_composeInverse(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__yWh8B7tCCdhiXMhhHUqbN,const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_FGPQyC36Ly4PgaEVTyCKbe,
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Transform3_inverseCompose(const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math__yWh8B7tCCdhiXMhhHUqbN,const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math_FGPQyC36Ly4PgaEVTyCKbe,pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Transform3_xformDir(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_V91rYIvDBkGRba7MvGcPUK,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kEbBObcYFIxUZ5_77V3CO_,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Transform3_inverseXformDir(const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math_V91rYIvDBkGRba7MvGcPUK,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_kEbBObcYFIxUZ5_77V3CO_,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Transform3_xformPoint(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_V91rYIvDBkGRba7MvGcPUK,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm__lqjegyKuwStj56WZLiC_e,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Transform3_inverseXformPoint(const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math_V91rYIvDBkGRba7MvGcPUK,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm__lqjegyKuwStj56WZLiC_e,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_SpatialVector_add(const
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math__AuaKMC5koOPbXxPi_MZvt,const
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math_kNtPmLll5l8eiqwtk5kfJv,
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_SpatialVector_subtract(const pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math__AuaKMC5koOPbXxPi_MZvt,const pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math_kNtPmLll5l8eiqwtk5kfJv,pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_SpatialVector_xform(const
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math_VgJW5ZqpwPpuY1inYtaofQ,const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_V91rYIvDBkGRba7MvGcPUK,
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math__1Zf2IciMRCub1vvbEr1C4);void
pm_math_SpatialVector_inverseXform(const pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math_V91rYIvDBkGRba7MvGcPUK,pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_add(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__AuaKMC5koOPbXxPi_MZvt,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kNtPmLll5l8eiqwtk5kfJv,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math__1Zf2IciMRCub1vvbEr1C4->x=pm_math__AuaKMC5koOPbXxPi_MZvt->x+
pm_math_kNtPmLll5l8eiqwtk5kfJv->x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FBDi_PCg670TjHgJTNPcHr+pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FBDi_PCg670TjHgJTNPcHr;}void pm_math_Vector3_subtract(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__AuaKMC5koOPbXxPi_MZvt,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kNtPmLll5l8eiqwtk5kfJv,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math__1Zf2IciMRCub1vvbEr1C4->x=pm_math__AuaKMC5koOPbXxPi_MZvt->x-
pm_math_kNtPmLll5l8eiqwtk5kfJv->x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FzyLWRgau0pMYq2XSI3ETL-pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FBDi_PCg670TjHgJTNPcHr;}void pm_math_Vector3_negate(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math__1Zf2IciMRCub1vvbEr1C4->x= -pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FzyLWRgau0pMYq2XSI3ETL= -
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FBDi_PCg670TjHgJTNPcHr= -
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;}void
pm_math_Vector3_scale(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T pm_math_FQferGZUKft3_i5GvYy4Oy,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math__1Zf2IciMRCub1vvbEr1C4->x=pm_math_FQferGZUKft3_i5GvYy4Oy*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_FQferGZUKft3_i5GvYy4Oy*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FBDi_PCg670TjHgJTNPcHr=
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr;}void pm_math_Vector3_divide(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T
pm_math_FQferGZUKft3_i5GvYy4Oy,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4){pm_math__1Zf2IciMRCub1vvbEr1C4->x=
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x/pm_math_FQferGZUKft3_i5GvYy4Oy;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FzyLWRgau0pMYq2XSI3ETL=
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL/
pm_math_FQferGZUKft3_i5GvYy4Oy;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr/pm_math_FQferGZUKft3_i5GvYy4Oy;}void
pm_math_Vector3_guardedDivide(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,real_T pm_math_FQferGZUKft3_i5GvYy4Oy,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){if(
pm_math_FQferGZUKft3_i5GvYy4Oy==0.0){pm_math__1Zf2IciMRCub1vvbEr1C4->x=0.0;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FzyLWRgau0pMYq2XSI3ETL=0.0;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FBDi_PCg670TjHgJTNPcHr=0.0;}else{
pm_math__1Zf2IciMRCub1vvbEr1C4->x=pm_math_VgJW5ZqpwPpuY1inYtaofQ->x/
pm_math_FQferGZUKft3_i5GvYy4Oy;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL/pm_math_FQferGZUKft3_i5GvYy4Oy;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FBDi_PCg670TjHgJTNPcHr=
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr/
pm_math_FQferGZUKft3_i5GvYy4Oy;}}real_T pm_math_Vector3_norm(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ){return sqrt(
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL+
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr);}void
pm_math_Vector3_unit(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4){pm_math_Vector3_divide(
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_Vector3_norm(
pm_math_VgJW5ZqpwPpuY1inYtaofQ),pm_math__1Zf2IciMRCub1vvbEr1C4);}void
pm_math_Vector3_guardedUnit(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4){pm_math_Vector3_guardedDivide(
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_Vector3_norm(
pm_math_VgJW5ZqpwPpuY1inYtaofQ),pm_math__1Zf2IciMRCub1vvbEr1C4);}real_T
pm_math_Vector3_dot(const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__AuaKMC5koOPbXxPi_MZvt,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_kNtPmLll5l8eiqwtk5kfJv){return pm_math__AuaKMC5koOPbXxPi_MZvt->x*
pm_math_kNtPmLll5l8eiqwtk5kfJv->x+pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FzyLWRgau0pMYq2XSI3ETL*pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FBDi_PCg670TjHgJTNPcHr;}void pm_math_Vector3_cross(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__AuaKMC5koOPbXxPi_MZvt,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kNtPmLll5l8eiqwtk5kfJv,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){const real_T x=
pm_math__AuaKMC5koOPbXxPi_MZvt->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_kNtPmLll5l8eiqwtk5kfJv->pm_math_FBDi_PCg670TjHgJTNPcHr-
pm_math__AuaKMC5koOPbXxPi_MZvt->pm_math_FBDi_PCg670TjHgJTNPcHr*
pm_math_kNtPmLll5l8eiqwtk5kfJv->pm_math_FzyLWRgau0pMYq2XSI3ETL;const real_T
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_kNtPmLll5l8eiqwtk5kfJv->x-
pm_math__AuaKMC5koOPbXxPi_MZvt->x*pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FBDi_PCg670TjHgJTNPcHr;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math__AuaKMC5koOPbXxPi_MZvt->x*
pm_math_kNtPmLll5l8eiqwtk5kfJv->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math__AuaKMC5koOPbXxPi_MZvt->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_kNtPmLll5l8eiqwtk5kfJv->x;pm_math__1Zf2IciMRCub1vvbEr1C4->x=x;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FzyLWRgau0pMYq2XSI3ETL=
pm_math_FzyLWRgau0pMYq2XSI3ETL;}void pm_math_Vector3_compOrthogonalBasis(const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kwrB3ZoKf7OufTHWaHJV7a,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kyp6uAyJE40UVuAQNEYzS1,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_V2__YrimeI4E_yWnhKofpy){
pm_math_Vector3_compOrthogonalBasis_ra(&pm_math_VgJW5ZqpwPpuY1inYtaofQ->x,&
pm_math_kwrB3ZoKf7OufTHWaHJV7a->x,&pm_math_kyp6uAyJE40UVuAQNEYzS1->x,&
pm_math_V2__YrimeI4E_yWnhKofpy->x);}void pm_math_Quaternion_compose(const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_FbCdebDtDIhMduMKWA8Khy,const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_krgkQdg3ZZ_0ded42Fk_8r,
pm_math__3md8_onIiO6heiNB5D3_3*pm_math__1Zf2IciMRCub1vvbEr1C4){(void)0;;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FQferGZUKft3_i5GvYy4Oy=
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FQferGZUKft3_i5GvYy4Oy*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FQferGZUKft3_i5GvYy4Oy-(
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x+
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FzyLWRgau0pMYq2XSI3ETL+
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FBDi_PCg670TjHgJTNPcHr*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FBDi_PCg670TjHgJTNPcHr);
pm_math__1Zf2IciMRCub1vvbEr1C4->x=pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x+
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FzyLWRgau0pMYq2XSI3ETL*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FzyLWRgau0pMYq2XSI3ETL*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x-
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->x*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->x;}void pm_math_Quaternion_composeInverse(
const pm_math__3md8_onIiO6heiNB5D3_3*pm_math_FbCdebDtDIhMduMKWA8Khy,const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_krgkQdg3ZZ_0ded42Fk_8r,
pm_math__3md8_onIiO6heiNB5D3_3*pm_math__1Zf2IciMRCub1vvbEr1C4){(void)0;;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FQferGZUKft3_i5GvYy4Oy=
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FQferGZUKft3_i5GvYy4Oy*-
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FQferGZUKft3_i5GvYy4Oy-(
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x+
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FzyLWRgau0pMYq2XSI3ETL+
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FBDi_PCg670TjHgJTNPcHr*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FBDi_PCg670TjHgJTNPcHr);
pm_math__1Zf2IciMRCub1vvbEr1C4->x=pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x-
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FzyLWRgau0pMYq2XSI3ETL*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FzyLWRgau0pMYq2XSI3ETL-pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FzyLWRgau0pMYq2XSI3ETL*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x-
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->x*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->x;}void pm_math_Quaternion_inverseCompose(
const pm_math__3md8_onIiO6heiNB5D3_3*pm_math_FbCdebDtDIhMduMKWA8Khy,const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_krgkQdg3ZZ_0ded42Fk_8r,
pm_math__3md8_onIiO6heiNB5D3_3*pm_math__1Zf2IciMRCub1vvbEr1C4){(void)0;;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FQferGZUKft3_i5GvYy4Oy= -
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FQferGZUKft3_i5GvYy4Oy*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FQferGZUKft3_i5GvYy4Oy-(
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x+
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FzyLWRgau0pMYq2XSI3ETL+
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FBDi_PCg670TjHgJTNPcHr*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FBDi_PCg670TjHgJTNPcHr);
pm_math__1Zf2IciMRCub1vvbEr1C4->x= -pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x+
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FzyLWRgau0pMYq2XSI3ETL*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL= -pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FzyLWRgau0pMYq2XSI3ETL*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->x-
pm_math_FbCdebDtDIhMduMKWA8Khy->x*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr= -pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FBDi_PCg670TjHgJTNPcHr+pm_math_FbCdebDtDIhMduMKWA8Khy->
pm_math_FBDi_PCg670TjHgJTNPcHr*pm_math_krgkQdg3ZZ_0ded42Fk_8r->
pm_math_FQferGZUKft3_i5GvYy4Oy+pm_math_FbCdebDtDIhMduMKWA8Khy->x*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_FbCdebDtDIhMduMKWA8Khy->pm_math_FzyLWRgau0pMYq2XSI3ETL*
pm_math_krgkQdg3ZZ_0ded42Fk_8r->x;}void pm_math_Quaternion_xform(const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_VnD_HGFKVUOWdDAWvZhyEb,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_FJDxOUSymMGic5lC7ZhrnL pm_math_FFhjXMhOoO8gZHlh8Hu3K3,
pm_math_FEcK0zAOzXKSZq2OQse79O;const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__98sj5nFM0hXfLt_hMZe1y=(const pm_math_FJDxOUSymMGic5lC7ZhrnL*)&
pm_math_VnD_HGFKVUOWdDAWvZhyEb->x;pm_math_Vector3_cross(
pm_math__98sj5nFM0hXfLt_hMZe1y,pm_math_VgJW5ZqpwPpuY1inYtaofQ,&
pm_math_FFhjXMhOoO8gZHlh8Hu3K3);pm_math_Vector3_cross(
pm_math__98sj5nFM0hXfLt_hMZe1y,&pm_math_FFhjXMhOoO8gZHlh8Hu3K3,&
pm_math_FEcK0zAOzXKSZq2OQse79O);pm_math__1Zf2IciMRCub1vvbEr1C4->x=
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+2.0*(pm_math_VnD_HGFKVUOWdDAWvZhyEb->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_FFhjXMhOoO8gZHlh8Hu3K3 .x+
pm_math_FEcK0zAOzXKSZq2OQse79O.x);pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL+2.0*(pm_math_VnD_HGFKVUOWdDAWvZhyEb->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_FFhjXMhOoO8gZHlh8Hu3K3 .
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_FEcK0zAOzXKSZq2OQse79O.
pm_math_FzyLWRgau0pMYq2XSI3ETL);pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr+2.0*(pm_math_VnD_HGFKVUOWdDAWvZhyEb->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_FFhjXMhOoO8gZHlh8Hu3K3 .
pm_math_FBDi_PCg670TjHgJTNPcHr+pm_math_FEcK0zAOzXKSZq2OQse79O.
pm_math_FBDi_PCg670TjHgJTNPcHr);}void pm_math_Quaternion_inverseXform(const
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_VnD_HGFKVUOWdDAWvZhyEb,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_FJDxOUSymMGic5lC7ZhrnL pm_math_FFhjXMhOoO8gZHlh8Hu3K3,
pm_math_FEcK0zAOzXKSZq2OQse79O;const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__98sj5nFM0hXfLt_hMZe1y=(const pm_math_FJDxOUSymMGic5lC7ZhrnL*)&
pm_math_VnD_HGFKVUOWdDAWvZhyEb->x;pm_math_Vector3_cross(
pm_math__98sj5nFM0hXfLt_hMZe1y,pm_math_VgJW5ZqpwPpuY1inYtaofQ,&
pm_math_FFhjXMhOoO8gZHlh8Hu3K3);pm_math_Vector3_cross(
pm_math__98sj5nFM0hXfLt_hMZe1y,&pm_math_FFhjXMhOoO8gZHlh8Hu3K3,&
pm_math_FEcK0zAOzXKSZq2OQse79O);pm_math__1Zf2IciMRCub1vvbEr1C4->x=
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+2.0*(-pm_math_VnD_HGFKVUOWdDAWvZhyEb->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_FFhjXMhOoO8gZHlh8Hu3K3 .x+
pm_math_FEcK0zAOzXKSZq2OQse79O.x);pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL+2.0*(-pm_math_VnD_HGFKVUOWdDAWvZhyEb->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_FFhjXMhOoO8gZHlh8Hu3K3 .
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_FEcK0zAOzXKSZq2OQse79O.
pm_math_FzyLWRgau0pMYq2XSI3ETL);pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr+2.0*(-pm_math_VnD_HGFKVUOWdDAWvZhyEb->
pm_math_FQferGZUKft3_i5GvYy4Oy*pm_math_FFhjXMhOoO8gZHlh8Hu3K3 .
pm_math_FBDi_PCg670TjHgJTNPcHr+pm_math_FEcK0zAOzXKSZq2OQse79O.
pm_math_FBDi_PCg670TjHgJTNPcHr);}void pm_math_Quaternion_Matrix3x3Ctor(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_FqUCZrSGGNOuePgRr82o_8,
pm_math__3md8_onIiO6heiNB5D3_3*pm_math_VnD_HGFKVUOWdDAWvZhyEb){
pm_math_Quaternion_Matrix3x3Ctor_ra(&pm_math_FqUCZrSGGNOuePgRr82o_8->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U,&pm_math_VnD_HGFKVUOWdDAWvZhyEb->
pm_math_FQferGZUKft3_i5GvYy4Oy);}void pm_math_Matrix3x3_compose(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_Fcuud3IN0odMZi54a1R_8f,const
pm_math_komYPTPtib40juqhd0nJcN*pm_math__09m2ugY6U_OXH9Il_a7Bj,
pm_math_komYPTPtib40juqhd0nJcN*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_Matrix3x3_compose_ra(&pm_math_Fcuud3IN0odMZi54a1R_8f->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U,&pm_math__09m2ugY6U_OXH9Il_a7Bj->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U);}void pm_math_Matrix3x3_composeTranspose(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_Fcuud3IN0odMZi54a1R_8f,const
pm_math_komYPTPtib40juqhd0nJcN*pm_math__09m2ugY6U_OXH9Il_a7Bj,
pm_math_komYPTPtib40juqhd0nJcN*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_Matrix3x3_composeTranspose_ra(&pm_math_Fcuud3IN0odMZi54a1R_8f->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U,&pm_math__09m2ugY6U_OXH9Il_a7Bj->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U);}void pm_math_Matrix3x3_transposeCompose(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_Fcuud3IN0odMZi54a1R_8f,const
pm_math_komYPTPtib40juqhd0nJcN*pm_math__09m2ugY6U_OXH9Il_a7Bj,
pm_math_komYPTPtib40juqhd0nJcN*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_Matrix3x3_transposeCompose_ra(&pm_math_Fcuud3IN0odMZi54a1R_8f->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U,&pm_math__09m2ugY6U_OXH9Il_a7Bj->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U);}void pm_math_Matrix3x3_preCross(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_F2l4p_g4sn02huHNflQjMH,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_komYPTPtib40juqhd0nJcN*pm_math__1Zf2IciMRCub1vvbEr1C4){(void)0;;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_V5gSkPeCSkdzZ1xMyj2v7U=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_FnXzm1MLmt04dPIhRbN5SW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_kdB_LoVum6OHeDEkf0n58b*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math__D1iFBxPf38RWiveIR1Iip=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_VgeldyT0dAtjeHo3kvxpdi*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__tdIR85BSYdzha7Mb8qhKj*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math__hPet7vW5h0Zi1uUdLa_LW=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_F3LgZdApwMGziTfUlk6dzB*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__WnakhFnl24_bX0NhL6CLW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_kdB_LoVum6OHeDEkf0n58b=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_V5gSkPeCSkdzZ1xMyj2v7U*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_FnXzm1MLmt04dPIhRbN5SW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math__tdIR85BSYdzha7Mb8qhKj=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__D1iFBxPf38RWiveIR1Iip*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math_VgeldyT0dAtjeHo3kvxpdi*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math__WnakhFnl24_bX0NhL6CLW=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__hPet7vW5h0Zi1uUdLa_LW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_F3LgZdApwMGziTfUlk6dzB*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FnXzm1MLmt04dPIhRbN5SW=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math_kdB_LoVum6OHeDEkf0n58b*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_V5gSkPeCSkdzZ1xMyj2v7U*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_VgeldyT0dAtjeHo3kvxpdi=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__tdIR85BSYdzha7Mb8qhKj*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x-pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__D1iFBxPf38RWiveIR1Iip*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_F3LgZdApwMGziTfUlk6dzB=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__WnakhFnl24_bX0NhL6CLW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__hPet7vW5h0Zi1uUdLa_LW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL;}void
pm_math_Matrix3x3_postCross(const pm_math_komYPTPtib40juqhd0nJcN*
pm_math_F2l4p_g4sn02huHNflQjMH,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_komYPTPtib40juqhd0nJcN*
pm_math__1Zf2IciMRCub1vvbEr1C4){(void)0;;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_V5gSkPeCSkdzZ1xMyj2v7U=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__D1iFBxPf38RWiveIR1Iip*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__hPet7vW5h0Zi1uUdLa_LW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math__D1iFBxPf38RWiveIR1Iip=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__hPet7vW5h0Zi1uUdLa_LW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_V5gSkPeCSkdzZ1xMyj2v7U*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math__hPet7vW5h0Zi1uUdLa_LW=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_V5gSkPeCSkdzZ1xMyj2v7U*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__D1iFBxPf38RWiveIR1Iip*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_kdB_LoVum6OHeDEkf0n58b=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__tdIR85BSYdzha7Mb8qhKj*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__WnakhFnl24_bX0NhL6CLW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math__tdIR85BSYdzha7Mb8qhKj=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__WnakhFnl24_bX0NhL6CLW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_kdB_LoVum6OHeDEkf0n58b*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math__WnakhFnl24_bX0NhL6CLW=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_kdB_LoVum6OHeDEkf0n58b*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__tdIR85BSYdzha7Mb8qhKj*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FnXzm1MLmt04dPIhRbN5SW=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math_VgeldyT0dAtjeHo3kvxpdi*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr-pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math_F3LgZdApwMGziTfUlk6dzB*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_VgeldyT0dAtjeHo3kvxpdi=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math_F3LgZdApwMGziTfUlk6dzB*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_FnXzm1MLmt04dPIhRbN5SW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_F3LgZdApwMGziTfUlk6dzB=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_FnXzm1MLmt04dPIhRbN5SW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL-
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_VgeldyT0dAtjeHo3kvxpdi*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x;}void pm_math_Matrix3x3_xform(const
pm_math_komYPTPtib40juqhd0nJcN*pm_math_F2l4p_g4sn02huHNflQjMH,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_VgJW5ZqpwPpuY1inYtaofQ,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){const real_T x=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_V5gSkPeCSkdzZ1xMyj2v7U*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__D1iFBxPf38RWiveIR1Iip*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__hPet7vW5h0Zi1uUdLa_LW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr;const real_T pm_math_FzyLWRgau0pMYq2XSI3ETL=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_kdB_LoVum6OHeDEkf0n58b*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__tdIR85BSYdzha7Mb8qhKj*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__WnakhFnl24_bX0NhL6CLW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FBDi_PCg670TjHgJTNPcHr=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math_FnXzm1MLmt04dPIhRbN5SW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_VgeldyT0dAtjeHo3kvxpdi*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL+
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_F3LgZdApwMGziTfUlk6dzB*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->x=x;pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_FzyLWRgau0pMYq2XSI3ETL;}void
pm_math_Matrix3x3_transposeXform(const pm_math_komYPTPtib40juqhd0nJcN*
pm_math_F2l4p_g4sn02huHNflQjMH,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4){const real_T x=pm_math_F2l4p_g4sn02huHNflQjMH
->pm_math_V5gSkPeCSkdzZ1xMyj2v7U*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_kdB_LoVum6OHeDEkf0n58b*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL+
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_FnXzm1MLmt04dPIhRbN5SW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;const real_T
pm_math_FzyLWRgau0pMYq2XSI3ETL=pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__D1iFBxPf38RWiveIR1Iip*pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__tdIR85BSYdzha7Mb8qhKj*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FzyLWRgau0pMYq2XSI3ETL+
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math_VgeldyT0dAtjeHo3kvxpdi*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FBDi_PCg670TjHgJTNPcHr;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FBDi_PCg670TjHgJTNPcHr=
pm_math_F2l4p_g4sn02huHNflQjMH->pm_math__hPet7vW5h0Zi1uUdLa_LW*
pm_math_VgJW5ZqpwPpuY1inYtaofQ->x+pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math__WnakhFnl24_bX0NhL6CLW*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FzyLWRgau0pMYq2XSI3ETL+pm_math_F2l4p_g4sn02huHNflQjMH->
pm_math_F3LgZdApwMGziTfUlk6dzB*pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_FBDi_PCg670TjHgJTNPcHr;pm_math__1Zf2IciMRCub1vvbEr1C4->x=x;
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FzyLWRgau0pMYq2XSI3ETL=
pm_math_FzyLWRgau0pMYq2XSI3ETL;}void pm_math_Transform3_compose(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__yWh8B7tCCdhiXMhhHUqbN,const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_FGPQyC36Ly4PgaEVTyCKbe,
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__1Zf2IciMRCub1vvbEr1C4){(void)0;;
pm_math_Quaternion_compose(&pm_math__yWh8B7tCCdhiXMhhHUqbN->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,&pm_math_FGPQyC36Ly4PgaEVTyCKbe->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_VnD_HGFKVUOWdDAWvZhyEb);pm_math_Quaternion_xform(&
pm_math__yWh8B7tCCdhiXMhhHUqbN->pm_math_VnD_HGFKVUOWdDAWvZhyEb,&
pm_math_FGPQyC36Ly4PgaEVTyCKbe->pm_math_F32Ql82vv6pW_PYIdpkFQ0,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_F32Ql82vv6pW_PYIdpkFQ0);
pm_math_Vector3_add(&pm_math__yWh8B7tCCdhiXMhhHUqbN->
pm_math_F32Ql82vv6pW_PYIdpkFQ0,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_F32Ql82vv6pW_PYIdpkFQ0,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_F32Ql82vv6pW_PYIdpkFQ0);}void pm_math_Transform3_composeInverse(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__yWh8B7tCCdhiXMhhHUqbN,const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_FGPQyC36Ly4PgaEVTyCKbe,
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__1Zf2IciMRCub1vvbEr1C4){(void)0;;
pm_math_Quaternion_composeInverse(&pm_math__yWh8B7tCCdhiXMhhHUqbN->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,&pm_math_FGPQyC36Ly4PgaEVTyCKbe->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_VnD_HGFKVUOWdDAWvZhyEb);pm_math_Quaternion_xform(&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_VnD_HGFKVUOWdDAWvZhyEb,&
pm_math_FGPQyC36Ly4PgaEVTyCKbe->pm_math_F32Ql82vv6pW_PYIdpkFQ0,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_F32Ql82vv6pW_PYIdpkFQ0);
pm_math_Vector3_subtract(&pm_math__yWh8B7tCCdhiXMhhHUqbN->
pm_math_F32Ql82vv6pW_PYIdpkFQ0,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_F32Ql82vv6pW_PYIdpkFQ0,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_F32Ql82vv6pW_PYIdpkFQ0);}void pm_math_Transform3_inverseCompose(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__yWh8B7tCCdhiXMhhHUqbN,const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_FGPQyC36Ly4PgaEVTyCKbe,
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_FJDxOUSymMGic5lC7ZhrnL pm_math_Fk2O4u6vQUpibmbv8Kjgnn;(void)0;;
pm_math_Quaternion_inverseCompose(&pm_math__yWh8B7tCCdhiXMhhHUqbN->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,&pm_math_FGPQyC36Ly4PgaEVTyCKbe->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_VnD_HGFKVUOWdDAWvZhyEb);pm_math_Vector3_subtract(&
pm_math_FGPQyC36Ly4PgaEVTyCKbe->pm_math_F32Ql82vv6pW_PYIdpkFQ0,&
pm_math__yWh8B7tCCdhiXMhhHUqbN->pm_math_F32Ql82vv6pW_PYIdpkFQ0,&
pm_math_Fk2O4u6vQUpibmbv8Kjgnn);pm_math_Quaternion_inverseXform(&
pm_math__yWh8B7tCCdhiXMhhHUqbN->pm_math_VnD_HGFKVUOWdDAWvZhyEb,&
pm_math_Fk2O4u6vQUpibmbv8Kjgnn,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_F32Ql82vv6pW_PYIdpkFQ0);}void pm_math_Transform3_xformDir(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_V91rYIvDBkGRba7MvGcPUK,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kEbBObcYFIxUZ5_77V3CO_,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_Quaternion_xform(&pm_math_V91rYIvDBkGRba7MvGcPUK->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,pm_math_kEbBObcYFIxUZ5_77V3CO_,
pm_math__1Zf2IciMRCub1vvbEr1C4);}void pm_math_Transform3_inverseXformDir(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_V91rYIvDBkGRba7MvGcPUK,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math_kEbBObcYFIxUZ5_77V3CO_,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_Quaternion_inverseXform(&pm_math_V91rYIvDBkGRba7MvGcPUK->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,pm_math_kEbBObcYFIxUZ5_77V3CO_,
pm_math__1Zf2IciMRCub1vvbEr1C4);}void pm_math_Transform3_xformPoint(const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_V91rYIvDBkGRba7MvGcPUK,const
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm__lqjegyKuwStj56WZLiC_e,
pm_math_FJDxOUSymMGic5lC7ZhrnL*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_Quaternion_xform(&pm_math_V91rYIvDBkGRba7MvGcPUK->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,pm__lqjegyKuwStj56WZLiC_e,
pm_math__1Zf2IciMRCub1vvbEr1C4);pm_math_Vector3_add(
pm_math__1Zf2IciMRCub1vvbEr1C4,&pm_math_V91rYIvDBkGRba7MvGcPUK->
pm_math_F32Ql82vv6pW_PYIdpkFQ0,pm_math__1Zf2IciMRCub1vvbEr1C4);}void
pm_math_Transform3_inverseXformPoint(const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math_V91rYIvDBkGRba7MvGcPUK,const pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm__lqjegyKuwStj56WZLiC_e,pm_math_FJDxOUSymMGic5lC7ZhrnL*
pm_math__1Zf2IciMRCub1vvbEr1C4){pm_math_Vector3_subtract(
pm__lqjegyKuwStj56WZLiC_e,&pm_math_V91rYIvDBkGRba7MvGcPUK->
pm_math_F32Ql82vv6pW_PYIdpkFQ0,pm_math__1Zf2IciMRCub1vvbEr1C4);
pm_math_Quaternion_inverseXform(&pm_math_V91rYIvDBkGRba7MvGcPUK->
pm_math_VnD_HGFKVUOWdDAWvZhyEb,pm_math__1Zf2IciMRCub1vvbEr1C4,
pm_math__1Zf2IciMRCub1vvbEr1C4);}void pm_math_SpatialVector_add(const
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math__AuaKMC5koOPbXxPi_MZvt,const
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math_kNtPmLll5l8eiqwtk5kfJv,
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_Vector3_add(&pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_FN28mzn7A2hvYLPTU_L4bt,&pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_FN28mzn7A2hvYLPTU_L4bt,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_FN28mzn7A2hvYLPTU_L4bt);pm_math_Vector3_add(&
pm_math__AuaKMC5koOPbXxPi_MZvt->pm_math_k61dA_LqfI4EY1W2W1B1mA,&
pm_math_kNtPmLll5l8eiqwtk5kfJv->pm_math_k61dA_LqfI4EY1W2W1B1mA,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_k61dA_LqfI4EY1W2W1B1mA);}void
pm_math_SpatialVector_subtract(const pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math__AuaKMC5koOPbXxPi_MZvt,const pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math_kNtPmLll5l8eiqwtk5kfJv,pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math__1Zf2IciMRCub1vvbEr1C4){pm_math_Vector3_subtract(&
pm_math__AuaKMC5koOPbXxPi_MZvt->pm_math_FN28mzn7A2hvYLPTU_L4bt,&
pm_math_kNtPmLll5l8eiqwtk5kfJv->pm_math_FN28mzn7A2hvYLPTU_L4bt,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FN28mzn7A2hvYLPTU_L4bt);
pm_math_Vector3_subtract(&pm_math__AuaKMC5koOPbXxPi_MZvt->
pm_math_k61dA_LqfI4EY1W2W1B1mA,&pm_math_kNtPmLll5l8eiqwtk5kfJv->
pm_math_k61dA_LqfI4EY1W2W1B1mA,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_k61dA_LqfI4EY1W2W1B1mA);}void pm_math_SpatialVector_xform(const
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math_VgJW5ZqpwPpuY1inYtaofQ,const
pm_math_k4kL9Om6RgxTZqdxJRM51B*pm_math_V91rYIvDBkGRba7MvGcPUK,
pm_math_kNq2SpAav5tbb5Yx_VSirx*pm_math__1Zf2IciMRCub1vvbEr1C4){
pm_math_FJDxOUSymMGic5lC7ZhrnL pm_math_FOJvFO_ZXm0Rh9pnVpfikf;
pm_math_Transform3_xformDir(pm_math_V91rYIvDBkGRba7MvGcPUK,&
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FN28mzn7A2hvYLPTU_L4bt,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FN28mzn7A2hvYLPTU_L4bt);
pm_math_Transform3_xformDir(pm_math_V91rYIvDBkGRba7MvGcPUK,&
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_k61dA_LqfI4EY1W2W1B1mA,&
pm_math_FOJvFO_ZXm0Rh9pnVpfikf);pm_math_Vector3_cross(&
pm_math_V91rYIvDBkGRba7MvGcPUK->pm_math_F32Ql82vv6pW_PYIdpkFQ0,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FN28mzn7A2hvYLPTU_L4bt,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_k61dA_LqfI4EY1W2W1B1mA);
pm_math_Vector3_add(&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_k61dA_LqfI4EY1W2W1B1mA,&pm_math_FOJvFO_ZXm0Rh9pnVpfikf,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_k61dA_LqfI4EY1W2W1B1mA);}void
pm_math_SpatialVector_inverseXform(const pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math_VgJW5ZqpwPpuY1inYtaofQ,const pm_math_k4kL9Om6RgxTZqdxJRM51B*
pm_math_V91rYIvDBkGRba7MvGcPUK,pm_math_kNq2SpAav5tbb5Yx_VSirx*
pm_math__1Zf2IciMRCub1vvbEr1C4){pm_math_FJDxOUSymMGic5lC7ZhrnL
pm_math_Fk2O4u6vQUpibmbv8Kjgnn;pm_math_Vector3_cross(&
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FN28mzn7A2hvYLPTU_L4bt,&
pm_math_V91rYIvDBkGRba7MvGcPUK->pm_math_F32Ql82vv6pW_PYIdpkFQ0,&
pm_math_Fk2O4u6vQUpibmbv8Kjgnn);pm_math_Vector3_add(&
pm_math_Fk2O4u6vQUpibmbv8Kjgnn,&pm_math_VgJW5ZqpwPpuY1inYtaofQ->
pm_math_k61dA_LqfI4EY1W2W1B1mA,&pm_math_Fk2O4u6vQUpibmbv8Kjgnn);
pm_math_Transform3_inverseXformDir(pm_math_V91rYIvDBkGRba7MvGcPUK,&
pm_math_VgJW5ZqpwPpuY1inYtaofQ->pm_math_FN28mzn7A2hvYLPTU_L4bt,&
pm_math__1Zf2IciMRCub1vvbEr1C4->pm_math_FN28mzn7A2hvYLPTU_L4bt);
pm_math_Transform3_inverseXformDir(pm_math_V91rYIvDBkGRba7MvGcPUK,&
pm_math_Fk2O4u6vQUpibmbv8Kjgnn,&pm_math__1Zf2IciMRCub1vvbEr1C4->
pm_math_k61dA_LqfI4EY1W2W1B1mA);}
