#include "pm_std.h"
struct sm_F10Fbm8pyTOM_L3tMhj4e7{size_t sm__VyGPUhHOUGr_9l0UciNgg;size_t
sm__ZBqXvglQt_BhaAcrCFP7W;real_T*sm_VELrIEUHeudCamAhgAMD2P;};typedef struct
sm_F10Fbm8pyTOM_L3tMhj4e7 sm_VoDgoJA_OIdYZyh9aOzfzC;void
sm_core_SmRealVector_create(sm_VoDgoJA_OIdYZyh9aOzfzC*
sm_VcZASgthsTt6dul8DlRWaw,size_t n,real_T pm_kpzAtHMD4_WnheH0UiioSE);void
sm_core_SmRealVector_copy(sm_VoDgoJA_OIdYZyh9aOzfzC*sm_kyVvGx32uvlKVTEMWrNekp,
const sm_VoDgoJA_OIdYZyh9aOzfzC*orig);void sm_core_SmRealVector_destroy(
sm_VoDgoJA_OIdYZyh9aOzfzC*sm_VcZASgthsTt6dul8DlRWaw);int
sm_core_SmRealVector_isEmpty(const sm_VoDgoJA_OIdYZyh9aOzfzC*
sm_VcZASgthsTt6dul8DlRWaw);size_t sm_core_SmRealVector_size(const
sm_VoDgoJA_OIdYZyh9aOzfzC*sm_VcZASgthsTt6dul8DlRWaw);size_t
sm_core_SmRealVector_capacity(const sm_VoDgoJA_OIdYZyh9aOzfzC*
sm_VcZASgthsTt6dul8DlRWaw);real_T sm_core_SmRealVector_value(const
sm_VoDgoJA_OIdYZyh9aOzfzC*sm_VcZASgthsTt6dul8DlRWaw,size_t
sm__wN5g_p_uwdVVLfRtx9szc);void sm_core_SmRealVector_setValue(
sm_VoDgoJA_OIdYZyh9aOzfzC*sm_VcZASgthsTt6dul8DlRWaw,size_t
sm__wN5g_p_uwdVVLfRtx9szc,real_T sm_kg4CyRgbu6OdeewZOel7Qx);const real_T*
sm_core_SmRealVector_values(const sm_VoDgoJA_OIdYZyh9aOzfzC*
sm_VcZASgthsTt6dul8DlRWaw);real_T*sm_core_SmRealVector_nonConstValues(
sm_VoDgoJA_OIdYZyh9aOzfzC*sm_VcZASgthsTt6dul8DlRWaw);void
sm_core_SmRealVector_reserve(sm_VoDgoJA_OIdYZyh9aOzfzC*
sm_VcZASgthsTt6dul8DlRWaw,size_t n);void sm_core_SmRealVector_clear(
sm_VoDgoJA_OIdYZyh9aOzfzC*sm_VcZASgthsTt6dul8DlRWaw);void
sm_core_SmRealVector_pushBack(sm_VoDgoJA_OIdYZyh9aOzfzC*
sm_VcZASgthsTt6dul8DlRWaw,real_T pm_kpzAtHMD4_WnheH0UiioSE);void
sm_core_SmRealVector_popBack(sm_VoDgoJA_OIdYZyh9aOzfzC*
sm_VcZASgthsTt6dul8DlRWaw);struct sm_FAe_hLKRs0t1gPCNBVVtIR{size_t
sm__VyGPUhHOUGr_9l0UciNgg;size_t sm__ZBqXvglQt_BhaAcrCFP7W;int*
sm_VELrIEUHeudCamAhgAMD2P;};typedef struct sm_FAe_hLKRs0t1gPCNBVVtIR
sm_V7xsSSeDhNGdeHRBws_2Zg;void sm_core_SmIntVector_create(
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_VcZASgthsTt6dul8DlRWaw,size_t n,int
pm_kpzAtHMD4_WnheH0UiioSE);void sm_core_SmIntVector_copy(
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_kyVvGx32uvlKVTEMWrNekp,const
sm_V7xsSSeDhNGdeHRBws_2Zg*orig);void sm_core_SmIntVector_destroy(
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_VcZASgthsTt6dul8DlRWaw);int
sm_core_SmIntVector_isEmpty(const sm_V7xsSSeDhNGdeHRBws_2Zg*
sm_VcZASgthsTt6dul8DlRWaw);size_t sm_core_SmIntVector_size(const
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_VcZASgthsTt6dul8DlRWaw);size_t
sm_core_SmIntVector_capacity(const sm_V7xsSSeDhNGdeHRBws_2Zg*
sm_VcZASgthsTt6dul8DlRWaw);int sm_core_SmIntVector_value(const
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_VcZASgthsTt6dul8DlRWaw,size_t
sm__wN5g_p_uwdVVLfRtx9szc);void sm_core_SmIntVector_setValue(
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_VcZASgthsTt6dul8DlRWaw,size_t
sm__wN5g_p_uwdVVLfRtx9szc,int sm_kg4CyRgbu6OdeewZOel7Qx);const int*
sm_core_SmIntVector_values(const sm_V7xsSSeDhNGdeHRBws_2Zg*
sm_VcZASgthsTt6dul8DlRWaw);int*sm_core_SmIntVector_nonConstValues(
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_VcZASgthsTt6dul8DlRWaw);void
sm_core_SmIntVector_reserve(sm_V7xsSSeDhNGdeHRBws_2Zg*
sm_VcZASgthsTt6dul8DlRWaw,size_t n);void sm_core_SmIntVector_clear(
sm_V7xsSSeDhNGdeHRBws_2Zg*sm_VcZASgthsTt6dul8DlRWaw);void
sm_core_SmIntVector_pushBack(sm_V7xsSSeDhNGdeHRBws_2Zg*
sm_VcZASgthsTt6dul8DlRWaw,int pm_kpzAtHMD4_WnheH0UiioSE);void
sm_core_SmIntVector_popBack(sm_V7xsSSeDhNGdeHRBws_2Zg*
sm_VcZASgthsTt6dul8DlRWaw);struct sm_F9E_QU8Zof02hyNcGyFoII{
sm_VoDgoJA_OIdYZyh9aOzfzC sm__22dqY91MyOm_mNH5FwFof;sm_V7xsSSeDhNGdeHRBws_2Zg
sm_F9HuI75SOXpdjaPQOxCSSV;};typedef struct sm_F9E_QU8Zof02hyNcGyFoII
sm__u5otWUlifChdDONlHDMsK;void sm_core_RuntimeDerivedValuesBundle_create(
sm__u5otWUlifChdDONlHDMsK*sm__wmTd2KKOKd7YPG6_QANiL,size_t
sm_FFmYCRWDbGCFbeA5GnIZ6W,size_t sm_FtDzaWOzNWO_Wyg8YnN4LE);void
sm_core_RuntimeDerivedValuesBundle_copy(const sm__u5otWUlifChdDONlHDMsK*orig,
sm__u5otWUlifChdDONlHDMsK*sm_kyVvGx32uvlKVTEMWrNekp);void
sm_core_RuntimeDerivedValuesBundle_destroy(sm__u5otWUlifChdDONlHDMsK*
sm__wmTd2KKOKd7YPG6_QANiL);void sm_core_RuntimeDerivedValuesBundle_create(
sm__u5otWUlifChdDONlHDMsK*sm__wmTd2KKOKd7YPG6_QANiL,size_t
sm_FFmYCRWDbGCFbeA5GnIZ6W,size_t sm_FtDzaWOzNWO_Wyg8YnN4LE){
sm_core_SmRealVector_create(&sm__wmTd2KKOKd7YPG6_QANiL->
sm__22dqY91MyOm_mNH5FwFof,sm_FFmYCRWDbGCFbeA5GnIZ6W,0.0);
sm_core_SmIntVector_create(&sm__wmTd2KKOKd7YPG6_QANiL->
sm_F9HuI75SOXpdjaPQOxCSSV,sm_FtDzaWOzNWO_Wyg8YnN4LE,0);}void
sm_core_RuntimeDerivedValuesBundle_copy(const sm__u5otWUlifChdDONlHDMsK*orig,
sm__u5otWUlifChdDONlHDMsK*sm_kyVvGx32uvlKVTEMWrNekp){sm_core_SmRealVector_copy
(&sm_kyVvGx32uvlKVTEMWrNekp->sm__22dqY91MyOm_mNH5FwFof,&orig->
sm__22dqY91MyOm_mNH5FwFof);sm_core_SmRealVector_reserve(&
sm_kyVvGx32uvlKVTEMWrNekp->sm__22dqY91MyOm_mNH5FwFof,
sm_core_SmRealVector_capacity(&orig->sm__22dqY91MyOm_mNH5FwFof));
sm_core_SmIntVector_copy(&sm_kyVvGx32uvlKVTEMWrNekp->sm_F9HuI75SOXpdjaPQOxCSSV
,&orig->sm_F9HuI75SOXpdjaPQOxCSSV);sm_core_SmIntVector_reserve(&
sm_kyVvGx32uvlKVTEMWrNekp->sm_F9HuI75SOXpdjaPQOxCSSV,
sm_core_SmIntVector_capacity(&orig->sm_F9HuI75SOXpdjaPQOxCSSV));}void
sm_core_RuntimeDerivedValuesBundle_destroy(sm__u5otWUlifChdDONlHDMsK*
sm__wmTd2KKOKd7YPG6_QANiL){sm_core_SmRealVector_destroy(&
sm__wmTd2KKOKd7YPG6_QANiL->sm__22dqY91MyOm_mNH5FwFof);
sm_core_SmIntVector_destroy(&sm__wmTd2KKOKd7YPG6_QANiL->
sm_F9HuI75SOXpdjaPQOxCSSV);}
