#include "pm_std.h"
#include "math.h"
#include "string.h"
#include "pm_std.h"
void pm_math_lin_alg_vectorAdd(uint32_T n,const double*
sm_kEbBObcYFIxUZ5_77V3CO_,const double*sm_VgJW5ZqpwPpuY1inYtaofQ,double*
sm_Vzz7fHz6oElvjujXUEM3YM);void pm_math_lin_alg_vectorSubtract(uint32_T n,
const double*sm_kEbBObcYFIxUZ5_77V3CO_,const double*sm_VgJW5ZqpwPpuY1inYtaofQ,
double*sm_Vo9I5RFcPal_bXJl4MT4zD);void pm_math_lin_alg_vectorScale(uint32_T n,
double sm_FQferGZUKft3_i5GvYy4Oy,const double*sm_VgJW5ZqpwPpuY1inYtaofQ,double
*sm_kMXfgG5aJNtdgeZBD1F9s7);void pm_math_lin_alg_vectorNegate(uint32_T n,const
double*sm_VgJW5ZqpwPpuY1inYtaofQ,double*sm_Vmg5DyKiTS4YVaa_KIUPx2);void
pm_math_lin_alg_matrixAssignStrided(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,
uint32_T n,uint32_T sm_FnKRRzrQB6GPWacR5qZ_N1,uint32_T
sm_VSkCOkBlf_lY_aOxP7FKDg,const double*sm__Q_i1Z0_CMGpfPqpuLrnMT,double*
sm_kyfq6L_eQbdYcPuOovpRDW);void pm_math_lin_alg_matrixTransposeAdd(uint32_T n,
const double*sm_F2l4p_g4sn02huHNflQjMH,double*sm__Q_i1Z0_CMGpfPqpuLrnMT);void
pm_math_lin_alg_matrixTransposeSubtract(uint32_T n,const double*
sm_F2l4p_g4sn02huHNflQjMH,double*sm_kyfq6L_eQbdYcPuOovpRDW);void
pm_math_lin_alg_matrixMultiply(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T
sm_V2__YrimeI4E_yWnhKofpy,uint32_T n,const double*sm_F2l4p_g4sn02huHNflQjMH,
const double*sm_Vqiy96WqvuhCaXm5e_vvT0,double*sm_FStFcQlyAJ_dVy4kGZXBPQ);void
pm_math_lin_alg_matrixMultiplyStrided(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,
uint32_T sm_V2__YrimeI4E_yWnhKofpy,uint32_T n,uint32_T
sm__8PlegfDdmpxaD3yVABBka,uint32_T sm_khoq8zTqfel4cuvza1xV8U,uint32_T
sm__Cskocqf_YOea9zRlVhiAe,const double*sm_F2l4p_g4sn02huHNflQjMH,const double*
sm_Vqiy96WqvuhCaXm5e_vvT0,double*sm_FStFcQlyAJ_dVy4kGZXBPQ);void
pm_math_lin_alg_matrixTransposeMultiply(uint32_T sm_V2__YrimeI4E_yWnhKofpy,
uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const double*
sm_F2l4p_g4sn02huHNflQjMH,const double*sm_Vqiy96WqvuhCaXm5e_vvT0,double*
sm_FStFcQlyAJ_dVy4kGZXBPQ);void pm_math_lin_alg_scaleColumns(uint32_T
sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const double*sm_F2l4p_g4sn02huHNflQjMH,
const double*sm_FQferGZUKft3_i5GvYy4Oy,double*sm_V5FB4OLCBN0eVqxcC6tIlV);void
pm_math_lin_alg_scaleRows(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const
double*sm_F2l4p_g4sn02huHNflQjMH,const double*sm_FQferGZUKft3_i5GvYy4Oy,double
*sm_knjWFknSIL0bYi3EKhrrJ4);void pm_math_lin_alg_inverseScaleColumns(uint32_T
sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const double*sm_F2l4p_g4sn02huHNflQjMH,
const double*sm_FQferGZUKft3_i5GvYy4Oy,double*sm_V5FB4OLCBN0eVqxcC6tIlV);void
pm_math_lin_alg_inverseScaleRows(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n
,const double*sm_F2l4p_g4sn02huHNflQjMH,const double*sm_FQferGZUKft3_i5GvYy4Oy
,double*sm_knjWFknSIL0bYi3EKhrrJ4);void pm_math_lin_alg_zeroMajor(uint32_T
sm_kRZY2SDSifK6ia_3EbLye7,uint32_T sm_FEXg1wwjA_S7cyqxiD_lWO,const int32_T*
sm_VU18hM_2GHSHWue20_mnXQ,double*sm_F2l4p_g4sn02huHNflQjMH);void
pm_math_lin_alg_reduceMatrix(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,
uint32_T sm_FTSHHVQYO78NWDDPfQSm12,const int32_T*sm_VLZhFoWjGJ0Q_DeI0FI6Gm,
double*sm_F2l4p_g4sn02huHNflQjMH);void pm_math_lin_alg_expandVector(uint32_T n
,uint32_T sm_kZSgglHk8kWUemlk_e6TDr,const int32_T*sm_VD0M3tgCkkSEiHjnw1wnK0,
double*sm_VgJW5ZqpwPpuY1inYtaofQ);void pm_math_lin_alg_matrixVectorMultiply(
uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const double*
sm_F2l4p_g4sn02huHNflQjMH,const double*x,double*sm_kcMuz7xytzhifPfhbjJNYL);
void pm_math_lin_alg_matrixVectorMultiplyStrided(uint32_T
sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,uint32_T sm_FxajFA_1TahGZXVH9j9Gmx,const
double*sm_F2l4p_g4sn02huHNflQjMH,const double*x,double*
sm_kcMuz7xytzhifPfhbjJNYL);void pm_math_lin_alg_matrixTransposeVectorMultiply(
uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const double*
sm_F2l4p_g4sn02huHNflQjMH,const double*x,double*sm_F9DWOuzPFtdljqhs7NoH_Y);
void pm_math_lin_alg_addMatrixVectorProduct(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9
,uint32_T n,const double*sm_F2l4p_g4sn02huHNflQjMH,const double*x,double*
sm_FzyLWRgau0pMYq2XSI3ETL);void pm_math_lin_alg_addMatrixVectorProductStrided(
uint32_T sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,uint32_T
sm_FxajFA_1TahGZXVH9j9Gmx,const double*sm_F2l4p_g4sn02huHNflQjMH,const double*
x,double*sm_FzyLWRgau0pMYq2XSI3ETL);void
pm_math_lin_alg_addMatrixTransposeVectorProduct(uint32_T
sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const double*sm_F2l4p_g4sn02huHNflQjMH,
const double*x,double*sm_FzyLWRgau0pMYq2XSI3ETL);void
pm_math_lin_alg_subtractMatrixVectorProduct(uint32_T sm_VLHhnPUiNQpve5VIL9P3O9
,uint32_T n,const double*sm_F2l4p_g4sn02huHNflQjMH,const double*x,double*
sm_FzyLWRgau0pMYq2XSI3ETL);void
pm_math_lin_alg_subtractMatrixVectorProductStrided(uint32_T
sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,uint32_T sm_FxajFA_1TahGZXVH9j9Gmx,const
double*sm_F2l4p_g4sn02huHNflQjMH,const double*x,double*
sm_FzyLWRgau0pMYq2XSI3ETL);void
pm_math_lin_alg_subtractMatrixTransposeVectorProduct(uint32_T
sm_VLHhnPUiNQpve5VIL9P3O9,uint32_T n,const double*sm_F2l4p_g4sn02huHNflQjMH,
const double*x,double*sm_FzyLWRgau0pMYq2XSI3ETL);double
pm_math_lin_alg_dotProduct(uint32_T n,const double*sm_kEbBObcYFIxUZ5_77V3CO_,
const double*sm_VgJW5ZqpwPpuY1inYtaofQ);double
pm_math_lin_alg_computeQuadraticTerm(uint32_T n,const double*
sm__EIaXP4H4ZKuZmaTyPyymE,const double*sm_kEbBObcYFIxUZ5_77V3CO_,const double*
sm_VgJW5ZqpwPpuY1inYtaofQ);void pm_math_lin_alg_geSolve2x2(const real_T
sm_F2l4p_g4sn02huHNflQjMH[4],const real_T b[2],real_T x[2]);real_T
pm_math_lin_alg_biasedSgn(real_T x);real_T pm_math_lin_alg_guardedSqrt(real_T x
);struct sm_Va7rvzSwRbpB_iIiuSF8h_{real_T x;real_T sm_FzyLWRgau0pMYq2XSI3ETL;
real_T sm_FBDi_PCg670TjHgJTNPcHr;};typedef struct sm_Va7rvzSwRbpB_iIiuSF8h_
sm_FJDxOUSymMGic5lC7ZhrnL;struct sm_VQiPk6I_S_0teiYbT1MBSN{real_T
sm_FQferGZUKft3_i5GvYy4Oy;real_T x;real_T sm_FzyLWRgau0pMYq2XSI3ETL;real_T
sm_FBDi_PCg670TjHgJTNPcHr;};typedef struct sm_VQiPk6I_S_0teiYbT1MBSN
sm__3md8_onIiO6heiNB5D3_3;struct sm_k5mHxu1pFy4YaeyeIGf5bY{real_T
sm_V5gSkPeCSkdzZ1xMyj2v7U,sm__D1iFBxPf38RWiveIR1Iip,sm__hPet7vW5h0Zi1uUdLa_LW;
real_T sm_kdB_LoVum6OHeDEkf0n58b,sm__tdIR85BSYdzha7Mb8qhKj,
sm__WnakhFnl24_bX0NhL6CLW;real_T sm_FnXzm1MLmt04dPIhRbN5SW,
sm_VgeldyT0dAtjeHo3kvxpdi,sm_F3LgZdApwMGziTfUlk6dzB;};typedef struct
sm_k5mHxu1pFy4YaeyeIGf5bY sm_komYPTPtib40juqhd0nJcN;struct
sm__sD2GKinhS_qYTF_z8BajY{sm__3md8_onIiO6heiNB5D3_3 sm_VnD_HGFKVUOWdDAWvZhyEb;
sm_FJDxOUSymMGic5lC7ZhrnL sm_F32Ql82vv6pW_PYIdpkFQ0;};typedef struct
sm__sD2GKinhS_qYTF_z8BajY sm_k4kL9Om6RgxTZqdxJRM51B;struct
sm__CEhElfLt9_7aqLsGROeDF{sm_FJDxOUSymMGic5lC7ZhrnL sm_FN28mzn7A2hvYLPTU_L4bt;
sm_FJDxOUSymMGic5lC7ZhrnL sm_k61dA_LqfI4EY1W2W1B1mA;};typedef struct
sm__CEhElfLt9_7aqLsGROeDF sm_kNq2SpAav5tbb5Yx_VSirx;void pm_math_Vector3_add(
const sm_FJDxOUSymMGic5lC7ZhrnL*sm__AuaKMC5koOPbXxPi_MZvt,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_kNtPmLll5l8eiqwtk5kfJv,sm_FJDxOUSymMGic5lC7ZhrnL*
sm__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_subtract(const
sm_FJDxOUSymMGic5lC7ZhrnL*sm__AuaKMC5koOPbXxPi_MZvt,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_kNtPmLll5l8eiqwtk5kfJv,sm_FJDxOUSymMGic5lC7ZhrnL*
sm__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_negate(const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*
sm__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_scale(const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_VgJW5ZqpwPpuY1inYtaofQ,real_T
sm_FQferGZUKft3_i5GvYy4Oy,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Vector3_divide(const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,real_T sm_FQferGZUKft3_i5GvYy4Oy,
sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4);void
pm_math_Vector3_guardedDivide(const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,real_T sm_FQferGZUKft3_i5GvYy4Oy,
sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4);real_T
pm_math_Vector3_norm(const sm_FJDxOUSymMGic5lC7ZhrnL*sm_VgJW5ZqpwPpuY1inYtaofQ
);void pm_math_Vector3_unit(const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Vector3_guardedUnit(const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;real_T pm_math_Vector3_dot(const sm_FJDxOUSymMGic5lC7ZhrnL*
sm__AuaKMC5koOPbXxPi_MZvt,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_kNtPmLll5l8eiqwtk5kfJv);void pm_math_Vector3_cross(const
sm_FJDxOUSymMGic5lC7ZhrnL*sm__AuaKMC5koOPbXxPi_MZvt,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_kNtPmLll5l8eiqwtk5kfJv,sm_FJDxOUSymMGic5lC7ZhrnL*
sm__1Zf2IciMRCub1vvbEr1C4);void pm_math_Vector3_compOrthogonalBasis(const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*
sm_kwrB3ZoKf7OufTHWaHJV7a,sm_FJDxOUSymMGic5lC7ZhrnL*sm_kyp6uAyJE40UVuAQNEYzS1,
sm_FJDxOUSymMGic5lC7ZhrnL*sm_V2__YrimeI4E_yWnhKofpy);void
pm_math_Quaternion_compose(const sm__3md8_onIiO6heiNB5D3_3*
sm_FbCdebDtDIhMduMKWA8Khy,const sm__3md8_onIiO6heiNB5D3_3*
sm_krgkQdg3ZZ_0ded42Fk_8r,sm__3md8_onIiO6heiNB5D3_3*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Quaternion_composeInverse(const sm__3md8_onIiO6heiNB5D3_3*
sm_FbCdebDtDIhMduMKWA8Khy,const sm__3md8_onIiO6heiNB5D3_3*
sm_krgkQdg3ZZ_0ded42Fk_8r,sm__3md8_onIiO6heiNB5D3_3*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Quaternion_inverseCompose(const sm__3md8_onIiO6heiNB5D3_3*
sm_FbCdebDtDIhMduMKWA8Khy,const sm__3md8_onIiO6heiNB5D3_3*
sm_krgkQdg3ZZ_0ded42Fk_8r,sm__3md8_onIiO6heiNB5D3_3*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Quaternion_xform(const sm__3md8_onIiO6heiNB5D3_3*
sm_VnD_HGFKVUOWdDAWvZhyEb,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Quaternion_inverseXform(const sm__3md8_onIiO6heiNB5D3_3*
sm_VnD_HGFKVUOWdDAWvZhyEb,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Quaternion_Matrix3x3Ctor(const sm_komYPTPtib40juqhd0nJcN*
sm_FqUCZrSGGNOuePgRr82o_8,sm__3md8_onIiO6heiNB5D3_3*sm_VnD_HGFKVUOWdDAWvZhyEb)
;void pm_math_Matrix3x3_compose(const sm_komYPTPtib40juqhd0nJcN*
sm_Fcuud3IN0odMZi54a1R_8f,const sm_komYPTPtib40juqhd0nJcN*
sm__09m2ugY6U_OXH9Il_a7Bj,sm_komYPTPtib40juqhd0nJcN*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Matrix3x3_composeTranspose(const sm_komYPTPtib40juqhd0nJcN*
sm_Fcuud3IN0odMZi54a1R_8f,const sm_komYPTPtib40juqhd0nJcN*
sm__09m2ugY6U_OXH9Il_a7Bj,sm_komYPTPtib40juqhd0nJcN*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Matrix3x3_transposeCompose(const sm_komYPTPtib40juqhd0nJcN*
sm_Fcuud3IN0odMZi54a1R_8f,const sm_komYPTPtib40juqhd0nJcN*
sm__09m2ugY6U_OXH9Il_a7Bj,sm_komYPTPtib40juqhd0nJcN*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Matrix3x3_preCross(const sm_komYPTPtib40juqhd0nJcN*
sm_F2l4p_g4sn02huHNflQjMH,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_komYPTPtib40juqhd0nJcN*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Matrix3x3_postCross(const sm_komYPTPtib40juqhd0nJcN*
sm_F2l4p_g4sn02huHNflQjMH,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_komYPTPtib40juqhd0nJcN*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Matrix3x3_xform(const sm_komYPTPtib40juqhd0nJcN*
sm_F2l4p_g4sn02huHNflQjMH,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Matrix3x3_transposeXform(const sm_komYPTPtib40juqhd0nJcN*
sm_F2l4p_g4sn02huHNflQjMH,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VgJW5ZqpwPpuY1inYtaofQ,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Transform3_compose(const sm_k4kL9Om6RgxTZqdxJRM51B*
sm__yWh8B7tCCdhiXMhhHUqbN,const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_FGPQyC36Ly4PgaEVTyCKbe,sm_k4kL9Om6RgxTZqdxJRM51B*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Transform3_composeInverse(const sm_k4kL9Om6RgxTZqdxJRM51B*
sm__yWh8B7tCCdhiXMhhHUqbN,const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_FGPQyC36Ly4PgaEVTyCKbe,sm_k4kL9Om6RgxTZqdxJRM51B*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Transform3_inverseCompose(const sm_k4kL9Om6RgxTZqdxJRM51B*
sm__yWh8B7tCCdhiXMhhHUqbN,const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_FGPQyC36Ly4PgaEVTyCKbe,sm_k4kL9Om6RgxTZqdxJRM51B*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Transform3_xformDir(const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_V91rYIvDBkGRba7MvGcPUK,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_kEbBObcYFIxUZ5_77V3CO_,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Transform3_inverseXformDir(const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_V91rYIvDBkGRba7MvGcPUK,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_kEbBObcYFIxUZ5_77V3CO_,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Transform3_xformPoint(const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_V91rYIvDBkGRba7MvGcPUK,const sm_FJDxOUSymMGic5lC7ZhrnL*
pm__lqjegyKuwStj56WZLiC_e,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_Transform3_inverseXformPoint(const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_V91rYIvDBkGRba7MvGcPUK,const sm_FJDxOUSymMGic5lC7ZhrnL*
pm__lqjegyKuwStj56WZLiC_e,sm_FJDxOUSymMGic5lC7ZhrnL*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_SpatialVector_add(const sm_kNq2SpAav5tbb5Yx_VSirx*
sm__AuaKMC5koOPbXxPi_MZvt,const sm_kNq2SpAav5tbb5Yx_VSirx*
sm_kNtPmLll5l8eiqwtk5kfJv,sm_kNq2SpAav5tbb5Yx_VSirx*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_SpatialVector_subtract(const sm_kNq2SpAav5tbb5Yx_VSirx*
sm__AuaKMC5koOPbXxPi_MZvt,const sm_kNq2SpAav5tbb5Yx_VSirx*
sm_kNtPmLll5l8eiqwtk5kfJv,sm_kNq2SpAav5tbb5Yx_VSirx*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_SpatialVector_xform(const sm_kNq2SpAav5tbb5Yx_VSirx*
sm_VgJW5ZqpwPpuY1inYtaofQ,const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_V91rYIvDBkGRba7MvGcPUK,sm_kNq2SpAav5tbb5Yx_VSirx*sm__1Zf2IciMRCub1vvbEr1C4)
;void pm_math_SpatialVector_inverseXform(const sm_kNq2SpAav5tbb5Yx_VSirx*
sm_VgJW5ZqpwPpuY1inYtaofQ,const sm_k4kL9Om6RgxTZqdxJRM51B*
sm_V91rYIvDBkGRba7MvGcPUK,sm_kNq2SpAav5tbb5Yx_VSirx*sm__1Zf2IciMRCub1vvbEr1C4)
;void sm_core_NonPlanarDrumDrumConstraint_CompScratchpad(const real_T*
sm_VH8wv9fKkdWtVmtTlQ1w0_,const real_T*sm__8MU0fhyYKhmfDGSem69VA,const real_T*
sm_FAmvwQsyk8WXXqGgOd_GxI,const real_T*sm_VZJ36E7TPNx5iDnLcZ_ynF,const real_T*
sm__9vp337pVRGgePfhu_a_Kp,const real_T*sm_VeexI_0Z9i46hD5Be4ArR9,const real_T*
sm_FVV34n_mrJ8Oa1tBlJaBnj,const real_T*sm_kDTYNj3erXleeDgn6ZWFBW,real_T
sm_V0_YXRZgCwhpfXYneT6RGZ,real_T sm_FHYCSZTG0vl9b9VGL0KGKq,real_T
sm_FDQbTuPesZpBfyxw_LpKXq,real_T sm_kGyjll4U_mtHWylXcyTxum,real_T*
sm_ksmCaTaFQ2l8_9iJm6dWPG);static const real_T sm_FwT4QK0HT1xGjuzNwSD54g=1e-6;
static const real_T sm_V6x4Z35NNaO1h11_fGDoXF=1e-12;static const int
sm_FtLqxzENgX4LWmtFTo7Ot3=10;static void sm__7F57Et7SV09hum39qNjuF(real_T a,
const sm_FJDxOUSymMGic5lC7ZhrnL*x,real_T b,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_FzyLWRgau0pMYq2XSI3ETL,sm_FJDxOUSymMGic5lC7ZhrnL*sm_VgJW5ZqpwPpuY1inYtaofQ)
{sm_FJDxOUSymMGic5lC7ZhrnL sm__v3C9B7yCxh9aavb7W88QX,sm_FMFYONCRcE4SZDLYWCSeui
;pm_math_Vector3_scale(x,a,&sm__v3C9B7yCxh9aavb7W88QX);pm_math_Vector3_scale(
sm_FzyLWRgau0pMYq2XSI3ETL,b,&sm_FMFYONCRcE4SZDLYWCSeui);pm_math_Vector3_add(&
sm__v3C9B7yCxh9aavb7W88QX,&sm_FMFYONCRcE4SZDLYWCSeui,sm_VgJW5ZqpwPpuY1inYtaofQ
);}typedef struct{real_T sm_FSqN5yp3iUpjZm5txj3JoW;real_T
sm_VDreFLQlUl4E_yFFilfD24;real_T sm__O3uFTmYxRWYjTXBq_kEwJ;real_T
sm_kA42PlQIJM_LX1evVxHVbX;real_T sm_kXfrtI4aDfSzgXAFi5PEd5;real_T
sm_FGHSLxRtu_tWeDQiFGgDgt;real_T sm_kEkio1xiQiSrZ1kpHnD9eQ;real_T
sm_FCsYpzEAMTlQgDqOM3dnCU;sm_FJDxOUSymMGic5lC7ZhrnL sm_FBGOMehyG_SZ_PQRqmYzQ7;
sm_FJDxOUSymMGic5lC7ZhrnL sm_kDpgLoAMxGhXW9JL_dY_cB;real_T
sm_kkxuw_G7_JGYe9k2sVL82A;real_T sm_Vr11O__h4iWxb97wIDFqlh;}
sm_FFpXOevUOPGXjirBED7iqn;static const size_t sm__pKSrAzBV_4sWaHQ5axB2o=16;
static boolean_T sm_VfySDTLaASG8jmBSXAitDI(const sm_FJDxOUSymMGic5lC7ZhrnL*
sm__8MU0fhyYKhmfDGSem69VA,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_FAmvwQsyk8WXXqGgOd_GxI,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm__9vp337pVRGgePfhu_a_Kp,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VeexI_0Z9i46hD5Be4ArR9,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_kDTYNj3erXleeDgn6ZWFBW,real_T sm_V0_YXRZgCwhpfXYneT6RGZ,real_T
sm_FHYCSZTG0vl9b9VGL0KGKq,real_T sm_kAi280ZU2YlqeXj1NKEZWN,real_T
sm___47bND3cEOicaVlHaDihx,sm_FFpXOevUOPGXjirBED7iqn*sm_kH7c9UGCUNOFXqT6Omambe)
{boolean_T sm_kuf6dHjZFApoZi5GOKlr5R=false;real_T sm_Fe6copTTRcKEayCm87ABO_[2]
,sm_kr54pdOF7m03iip5bybdRd[4],sm_FvI0DyR4hDK8bPlAJhG_hG[2],
sm_F3GPAXzZcy8heaeLth7Yde,sm_FGFoAVdNbKhUj1R8RTBN4s;sm_FJDxOUSymMGic5lC7ZhrnL
sm_V_u8IFmOxCGNiLVw51_AqW,sm_FwGHdfbItqWifPZ7TmpEhj;int
sm_FiyTj7UWVktw_aO3Kw8nrC;sm_kH7c9UGCUNOFXqT6Omambe->sm__O3uFTmYxRWYjTXBq_kEwJ
=sm_kAi280ZU2YlqeXj1NKEZWN;sm_kH7c9UGCUNOFXqT6Omambe->
sm_kA42PlQIJM_LX1evVxHVbX=sm___47bND3cEOicaVlHaDihx;for(
sm_FiyTj7UWVktw_aO3Kw8nrC=0;sm_FiyTj7UWVktw_aO3Kw8nrC<
sm_FtLqxzENgX4LWmtFTo7Ot3;++sm_FiyTj7UWVktw_aO3Kw8nrC){
sm_kH7c9UGCUNOFXqT6Omambe->sm_kXfrtI4aDfSzgXAFi5PEd5=cos(
sm_kH7c9UGCUNOFXqT6Omambe->sm__O3uFTmYxRWYjTXBq_kEwJ);
sm_kH7c9UGCUNOFXqT6Omambe->sm_FGHSLxRtu_tWeDQiFGgDgt=sin(
sm_kH7c9UGCUNOFXqT6Omambe->sm__O3uFTmYxRWYjTXBq_kEwJ);
sm_kH7c9UGCUNOFXqT6Omambe->sm_kEkio1xiQiSrZ1kpHnD9eQ=cos(
sm_kH7c9UGCUNOFXqT6Omambe->sm_kA42PlQIJM_LX1evVxHVbX);
sm_kH7c9UGCUNOFXqT6Omambe->sm_FCsYpzEAMTlQgDqOM3dnCU=sin(
sm_kH7c9UGCUNOFXqT6Omambe->sm_kA42PlQIJM_LX1evVxHVbX);
sm__7F57Et7SV09hum39qNjuF(sm_kH7c9UGCUNOFXqT6Omambe->sm_kXfrtI4aDfSzgXAFi5PEd5
,sm__8MU0fhyYKhmfDGSem69VA,sm_kH7c9UGCUNOFXqT6Omambe->
sm_FGHSLxRtu_tWeDQiFGgDgt,sm_FAmvwQsyk8WXXqGgOd_GxI,&sm_kH7c9UGCUNOFXqT6Omambe
->sm_FBGOMehyG_SZ_PQRqmYzQ7);sm__7F57Et7SV09hum39qNjuF(
sm_kH7c9UGCUNOFXqT6Omambe->sm_kEkio1xiQiSrZ1kpHnD9eQ,sm__9vp337pVRGgePfhu_a_Kp
,sm_kH7c9UGCUNOFXqT6Omambe->sm_FCsYpzEAMTlQgDqOM3dnCU,
sm_VeexI_0Z9i46hD5Be4ArR9,&sm_kH7c9UGCUNOFXqT6Omambe->
sm_kDpgLoAMxGhXW9JL_dY_cB);sm_kH7c9UGCUNOFXqT6Omambe->
sm_kkxuw_G7_JGYe9k2sVL82A=pm_math_Vector3_dot(&sm_kH7c9UGCUNOFXqT6Omambe->
sm_FBGOMehyG_SZ_PQRqmYzQ7,&sm_kH7c9UGCUNOFXqT6Omambe->
sm_kDpgLoAMxGhXW9JL_dY_cB);sm_Fe6copTTRcKEayCm87ABO_[0]=
sm_V0_YXRZgCwhpfXYneT6RGZ-pm_math_Vector3_dot(sm_kDTYNj3erXleeDgn6ZWFBW,&
sm_kH7c9UGCUNOFXqT6Omambe->sm_FBGOMehyG_SZ_PQRqmYzQ7)-
sm_FHYCSZTG0vl9b9VGL0KGKq*sm_kH7c9UGCUNOFXqT6Omambe->sm_kkxuw_G7_JGYe9k2sVL82A
;sm_Fe6copTTRcKEayCm87ABO_[1]=sm_FHYCSZTG0vl9b9VGL0KGKq+pm_math_Vector3_dot(
sm_kDTYNj3erXleeDgn6ZWFBW,&sm_kH7c9UGCUNOFXqT6Omambe->
sm_kDpgLoAMxGhXW9JL_dY_cB)-sm_V0_YXRZgCwhpfXYneT6RGZ*sm_kH7c9UGCUNOFXqT6Omambe
->sm_kkxuw_G7_JGYe9k2sVL82A;if(fabs(sm_Fe6copTTRcKEayCm87ABO_[0])<
sm_V6x4Z35NNaO1h11_fGDoXF&&fabs(sm_Fe6copTTRcKEayCm87ABO_[1])<
sm_V6x4Z35NNaO1h11_fGDoXF){sm_kuf6dHjZFApoZi5GOKlr5R=true;break;}
sm__7F57Et7SV09hum39qNjuF(sm_kH7c9UGCUNOFXqT6Omambe->sm_FGHSLxRtu_tWeDQiFGgDgt
,sm__8MU0fhyYKhmfDGSem69VA,-sm_kH7c9UGCUNOFXqT6Omambe->
sm_kXfrtI4aDfSzgXAFi5PEd5,sm_FAmvwQsyk8WXXqGgOd_GxI,&sm_V_u8IFmOxCGNiLVw51_AqW
);sm__7F57Et7SV09hum39qNjuF(sm_kH7c9UGCUNOFXqT6Omambe->
sm_FCsYpzEAMTlQgDqOM3dnCU,sm__9vp337pVRGgePfhu_a_Kp,-sm_kH7c9UGCUNOFXqT6Omambe
->sm_kEkio1xiQiSrZ1kpHnD9eQ,sm_VeexI_0Z9i46hD5Be4ArR9,&
sm_FwGHdfbItqWifPZ7TmpEhj);sm_F3GPAXzZcy8heaeLth7Yde=pm_math_Vector3_dot(&
sm_V_u8IFmOxCGNiLVw51_AqW,&sm_kH7c9UGCUNOFXqT6Omambe->
sm_kDpgLoAMxGhXW9JL_dY_cB);sm_FGFoAVdNbKhUj1R8RTBN4s=pm_math_Vector3_dot(&
sm_FwGHdfbItqWifPZ7TmpEhj,&sm_kH7c9UGCUNOFXqT6Omambe->
sm_FBGOMehyG_SZ_PQRqmYzQ7);sm_kr54pdOF7m03iip5bybdRd[0]=
sm_FHYCSZTG0vl9b9VGL0KGKq*sm_F3GPAXzZcy8heaeLth7Yde+pm_math_Vector3_dot(
sm_kDTYNj3erXleeDgn6ZWFBW,&sm_V_u8IFmOxCGNiLVw51_AqW);
sm_kr54pdOF7m03iip5bybdRd[1]=sm_V0_YXRZgCwhpfXYneT6RGZ*
sm_F3GPAXzZcy8heaeLth7Yde;sm_kr54pdOF7m03iip5bybdRd[2]=
sm_FHYCSZTG0vl9b9VGL0KGKq*sm_FGFoAVdNbKhUj1R8RTBN4s;sm_kr54pdOF7m03iip5bybdRd[
3]=sm_V0_YXRZgCwhpfXYneT6RGZ*sm_FGFoAVdNbKhUj1R8RTBN4s-pm_math_Vector3_dot(
sm_kDTYNj3erXleeDgn6ZWFBW,&sm_FwGHdfbItqWifPZ7TmpEhj);
pm_math_lin_alg_geSolve2x2(sm_kr54pdOF7m03iip5bybdRd,sm_Fe6copTTRcKEayCm87ABO_
,sm_FvI0DyR4hDK8bPlAJhG_hG);sm_kH7c9UGCUNOFXqT6Omambe->
sm__O3uFTmYxRWYjTXBq_kEwJ=sm_kH7c9UGCUNOFXqT6Omambe->sm__O3uFTmYxRWYjTXBq_kEwJ
-sm_FvI0DyR4hDK8bPlAJhG_hG[0];sm_kH7c9UGCUNOFXqT6Omambe->
sm_kA42PlQIJM_LX1evVxHVbX=sm_kH7c9UGCUNOFXqT6Omambe->sm_kA42PlQIJM_LX1evVxHVbX
-sm_FvI0DyR4hDK8bPlAJhG_hG[1];}return sm_kuf6dHjZFApoZi5GOKlr5R;}static
boolean_T sm__nLdu5kx9qp8_ewQ6HLrUN(const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_VZJ36E7TPNx5iDnLcZ_ynF,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_FVV34n_mrJ8Oa1tBlJaBnj,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_kDTYNj3erXleeDgn6ZWFBW,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_FBGOMehyG_SZ_PQRqmYzQ7,const sm_FJDxOUSymMGic5lC7ZhrnL*
sm_kDpgLoAMxGhXW9JL_dY_cB,real_T sm_V0_YXRZgCwhpfXYneT6RGZ,real_T
sm_FHYCSZTG0vl9b9VGL0KGKq,real_T sm_FDQbTuPesZpBfyxw_LpKXq,real_T
sm_kGyjll4U_mtHWylXcyTxum){sm_FJDxOUSymMGic5lC7ZhrnL sm_FhKeQqHqnYOQYyZHsZ_eoq
,sm__yb7J4Oovj_KfPVCP_cEM_,sm__H_cAaflHupXaTwDxrD0cg,sm__yx1IrzJaJGZZqrYF_Xeao
;sm_FJDxOUSymMGic5lC7ZhrnL sm_FxAE6VkmlYWm_XIXB2bO9o,sm_Fp37C3Z8fEpnf1g2PMBU6D
;real_T sm_kcix5xDZ9CGojHSplpnPll,sm_k7GlFaHfV9xYYi1TdlykRp;
pm_math_Vector3_scale(sm_FBGOMehyG_SZ_PQRqmYzQ7,sm_V0_YXRZgCwhpfXYneT6RGZ,&
sm_FhKeQqHqnYOQYyZHsZ_eoq);pm_math_Vector3_scale(sm_kDpgLoAMxGhXW9JL_dY_cB,
sm_FHYCSZTG0vl9b9VGL0KGKq,&sm__yb7J4Oovj_KfPVCP_cEM_);
pm_math_lin_alg_vectorNegate(3,&sm_kDTYNj3erXleeDgn6ZWFBW->x,&
sm__H_cAaflHupXaTwDxrD0cg.x);pm_math_Vector3_subtract(&
sm__H_cAaflHupXaTwDxrD0cg,&sm__yb7J4Oovj_KfPVCP_cEM_,&
sm__H_cAaflHupXaTwDxrD0cg);pm_math_Vector3_subtract(sm_kDTYNj3erXleeDgn6ZWFBW,
&sm_FhKeQqHqnYOQYyZHsZ_eoq,&sm__yx1IrzJaJGZZqrYF_Xeao);pm_math_Vector3_cross(&
sm_FhKeQqHqnYOQYyZHsZ_eoq,&sm__H_cAaflHupXaTwDxrD0cg,&
sm_FxAE6VkmlYWm_XIXB2bO9o);pm_math_Vector3_cross(&sm__yb7J4Oovj_KfPVCP_cEM_,&
sm__yx1IrzJaJGZZqrYF_Xeao,&sm_Fp37C3Z8fEpnf1g2PMBU6D);
sm_kcix5xDZ9CGojHSplpnPll=pm_math_Vector3_dot(&sm_FxAE6VkmlYWm_XIXB2bO9o,
sm_VZJ36E7TPNx5iDnLcZ_ynF);sm_k7GlFaHfV9xYYi1TdlykRp=pm_math_Vector3_dot(&
sm_Fp37C3Z8fEpnf1g2PMBU6D,sm_FVV34n_mrJ8Oa1tBlJaBnj);return
pm_math_lin_alg_biasedSgn(sm_kcix5xDZ9CGojHSplpnPll)==
sm_FDQbTuPesZpBfyxw_LpKXq&&pm_math_lin_alg_biasedSgn(sm_k7GlFaHfV9xYYi1TdlykRp
)==sm_kGyjll4U_mtHWylXcyTxum;}static void sm__bvz_0oiS24AVLEwuGqJP7(const
sm_FJDxOUSymMGic5lC7ZhrnL*sm__8MU0fhyYKhmfDGSem69VA,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_FAmvwQsyk8WXXqGgOd_GxI,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_VZJ36E7TPNx5iDnLcZ_ynF,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm__9vp337pVRGgePfhu_a_Kp,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_VeexI_0Z9i46hD5Be4ArR9,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_FVV34n_mrJ8Oa1tBlJaBnj,const
sm_FJDxOUSymMGic5lC7ZhrnL*sm_kDTYNj3erXleeDgn6ZWFBW,real_T
sm_V0_YXRZgCwhpfXYneT6RGZ,real_T sm_FHYCSZTG0vl9b9VGL0KGKq,real_T
sm_FDQbTuPesZpBfyxw_LpKXq,real_T sm_kGyjll4U_mtHWylXcyTxum,real_T
sm_VglsO0uaWU8NiH2EnV6sMa,real_T sm_kAi280ZU2YlqeXj1NKEZWN,real_T
sm___47bND3cEOicaVlHaDihx,sm_FFpXOevUOPGXjirBED7iqn*sm_kH7c9UGCUNOFXqT6Omambe)
{boolean_T sm_F_fCM87QwGd3hyImTZXDwI=false;const boolean_T
sm_VdW27ghWRd_PYH9jnCCH9E=sm_VfySDTLaASG8jmBSXAitDI(sm__8MU0fhyYKhmfDGSem69VA,
sm_FAmvwQsyk8WXXqGgOd_GxI,sm__9vp337pVRGgePfhu_a_Kp,sm_VeexI_0Z9i46hD5Be4ArR9,
sm_kDTYNj3erXleeDgn6ZWFBW,sm_V0_YXRZgCwhpfXYneT6RGZ,sm_FHYCSZTG0vl9b9VGL0KGKq,
sm_kAi280ZU2YlqeXj1NKEZWN,sm___47bND3cEOicaVlHaDihx,sm_kH7c9UGCUNOFXqT6Omambe)
;if(sm_VdW27ghWRd_PYH9jnCCH9E){const boolean_T sm_FWPJQK9KgJ_i_XPi1IE7IQ=
sm__nLdu5kx9qp8_ewQ6HLrUN(sm_VZJ36E7TPNx5iDnLcZ_ynF,sm_FVV34n_mrJ8Oa1tBlJaBnj,
sm_kDTYNj3erXleeDgn6ZWFBW,&sm_kH7c9UGCUNOFXqT6Omambe->
sm_FBGOMehyG_SZ_PQRqmYzQ7,&sm_kH7c9UGCUNOFXqT6Omambe->
sm_kDpgLoAMxGhXW9JL_dY_cB,sm_V0_YXRZgCwhpfXYneT6RGZ,sm_FHYCSZTG0vl9b9VGL0KGKq,
sm_FDQbTuPesZpBfyxw_LpKXq,sm_kGyjll4U_mtHWylXcyTxum);if(
sm_FWPJQK9KgJ_i_XPi1IE7IQ){sm_kH7c9UGCUNOFXqT6Omambe->
sm_FSqN5yp3iUpjZm5txj3JoW=sm_VglsO0uaWU8NiH2EnV6sMa-(sm_V0_YXRZgCwhpfXYneT6RGZ
*sm_V0_YXRZgCwhpfXYneT6RGZ+sm_FHYCSZTG0vl9b9VGL0KGKq*sm_FHYCSZTG0vl9b9VGL0KGKq
)+2.0*sm_V0_YXRZgCwhpfXYneT6RGZ*sm_FHYCSZTG0vl9b9VGL0KGKq*
sm_kH7c9UGCUNOFXqT6Omambe->sm_kkxuw_G7_JGYe9k2sVL82A;sm_kH7c9UGCUNOFXqT6Omambe
->sm_VDreFLQlUl4E_yFFilfD24=pm_math_lin_alg_guardedSqrt(
sm_kH7c9UGCUNOFXqT6Omambe->sm_FSqN5yp3iUpjZm5txj3JoW);
sm_F_fCM87QwGd3hyImTZXDwI=(sm_kH7c9UGCUNOFXqT6Omambe->
sm_FSqN5yp3iUpjZm5txj3JoW>sm_FwT4QK0HT1xGjuzNwSD54g);}}
sm_kH7c9UGCUNOFXqT6Omambe->sm_Vr11O__h4iWxb97wIDFqlh=sm_F_fCM87QwGd3hyImTZXDwI
?1.0:0.0;}void sm_core_NonPlanarDrumDrumConstraint_CompScratchpad(const real_T
*sm_VH8wv9fKkdWtVmtTlQ1w0_,const real_T*sm_ko_fPDD56bp6bHWA_VE99h,const real_T
*sm__FhXb4kNaXpueDfP5mwQNI,const real_T*sm__cKJf5bHoGx3ZTiC_PXa6B,const real_T
*sm_VQumgL5Ai1tDaPlcJFBYcR,const real_T*sm__yjzU9jt9cxbdeVJmvB081,const real_T
*sm_VCJhonSgbFpDcuQH1zkFJ5,const real_T*sm_V1845ADg2IlNceOlbG_chj,real_T
sm_V0_YXRZgCwhpfXYneT6RGZ,real_T sm_FHYCSZTG0vl9b9VGL0KGKq,real_T
sm_FDQbTuPesZpBfyxw_LpKXq,real_T sm_kGyjll4U_mtHWylXcyTxum,real_T*
sm_ksmCaTaFQ2l8_9iJm6dWPG){const sm_FJDxOUSymMGic5lC7ZhrnL*
sm__8MU0fhyYKhmfDGSem69VA=(const sm_FJDxOUSymMGic5lC7ZhrnL*)
sm_ko_fPDD56bp6bHWA_VE99h,*sm_FAmvwQsyk8WXXqGgOd_GxI=(const
sm_FJDxOUSymMGic5lC7ZhrnL*)sm__FhXb4kNaXpueDfP5mwQNI,*
sm_VZJ36E7TPNx5iDnLcZ_ynF=(const sm_FJDxOUSymMGic5lC7ZhrnL*)
sm__cKJf5bHoGx3ZTiC_PXa6B,*sm__9vp337pVRGgePfhu_a_Kp=(const
sm_FJDxOUSymMGic5lC7ZhrnL*)sm_VQumgL5Ai1tDaPlcJFBYcR,*
sm_VeexI_0Z9i46hD5Be4ArR9=(const sm_FJDxOUSymMGic5lC7ZhrnL*)
sm__yjzU9jt9cxbdeVJmvB081,*sm_FVV34n_mrJ8Oa1tBlJaBnj=(const
sm_FJDxOUSymMGic5lC7ZhrnL*)sm_VCJhonSgbFpDcuQH1zkFJ5,*
sm_kDTYNj3erXleeDgn6ZWFBW=(const sm_FJDxOUSymMGic5lC7ZhrnL*)
sm_V1845ADg2IlNceOlbG_chj;sm_FFpXOevUOPGXjirBED7iqn*sm_kH7c9UGCUNOFXqT6Omambe=
(sm_FFpXOevUOPGXjirBED7iqn*)sm_ksmCaTaFQ2l8_9iJm6dWPG;const real_T
sm_VglsO0uaWU8NiH2EnV6sMa=pm_math_Vector3_dot(sm_kDTYNj3erXleeDgn6ZWFBW,
sm_kDTYNj3erXleeDgn6ZWFBW);sm_kH7c9UGCUNOFXqT6Omambe->
sm_Vr11O__h4iWxb97wIDFqlh=0.0;if(sm_VH8wv9fKkdWtVmtTlQ1w0_!=NULL){
sm__bvz_0oiS24AVLEwuGqJP7(sm__8MU0fhyYKhmfDGSem69VA,sm_FAmvwQsyk8WXXqGgOd_GxI,
sm_VZJ36E7TPNx5iDnLcZ_ynF,sm__9vp337pVRGgePfhu_a_Kp,sm_VeexI_0Z9i46hD5Be4ArR9,
sm_FVV34n_mrJ8Oa1tBlJaBnj,sm_kDTYNj3erXleeDgn6ZWFBW,sm_V0_YXRZgCwhpfXYneT6RGZ,
sm_FHYCSZTG0vl9b9VGL0KGKq,sm_FDQbTuPesZpBfyxw_LpKXq,sm_kGyjll4U_mtHWylXcyTxum,
sm_VglsO0uaWU8NiH2EnV6sMa,*sm_VH8wv9fKkdWtVmtTlQ1w0_,*(
sm_VH8wv9fKkdWtVmtTlQ1w0_+1),sm_kH7c9UGCUNOFXqT6Omambe);}if(
sm_kH7c9UGCUNOFXqT6Omambe->sm_Vr11O__h4iWxb97wIDFqlh==0.0){int
sm_kwrB3ZoKf7OufTHWaHJV7a,sm_kyp6uAyJE40UVuAQNEYzS1;const int
sm_FqkViIhWVsxbeqRE9PhzgF=4;const real_T sm_FAgKZ8DJk6pig9GuHdUp8H=pmf_get_pi(
);const real_T sm__jP7F4Fk5ExlWmUH2CnO0p=2.0*sm_FAgKZ8DJk6pig9GuHdUp8H/
sm_FqkViIhWVsxbeqRE9PhzgF;sm_FFpXOevUOPGXjirBED7iqn sm_kM2T2UV5j_lvZaDBnKmoj0;
sm_kH7c9UGCUNOFXqT6Omambe->sm_VDreFLQlUl4E_yFFilfD24=0.0;for(
sm_kwrB3ZoKf7OufTHWaHJV7a=0;sm_kwrB3ZoKf7OufTHWaHJV7a<
sm_FqkViIhWVsxbeqRE9PhzgF;++sm_kwrB3ZoKf7OufTHWaHJV7a){const real_T
sm_k8r3_pBpy_SOVDSsNbUp57= -sm_FAgKZ8DJk6pig9GuHdUp8H+(0.5+
sm_kwrB3ZoKf7OufTHWaHJV7a)*sm__jP7F4Fk5ExlWmUH2CnO0p;for(
sm_kyp6uAyJE40UVuAQNEYzS1=0;sm_kyp6uAyJE40UVuAQNEYzS1<
sm_FqkViIhWVsxbeqRE9PhzgF;++sm_kyp6uAyJE40UVuAQNEYzS1){const real_T
sm__A8dOkVl1BlhhaLAtbMLi2= -sm_FAgKZ8DJk6pig9GuHdUp8H+(0.5+
sm_kyp6uAyJE40UVuAQNEYzS1)*sm__jP7F4Fk5ExlWmUH2CnO0p;sm__bvz_0oiS24AVLEwuGqJP7
(sm__8MU0fhyYKhmfDGSem69VA,sm_FAmvwQsyk8WXXqGgOd_GxI,sm_VZJ36E7TPNx5iDnLcZ_ynF
,sm__9vp337pVRGgePfhu_a_Kp,sm_VeexI_0Z9i46hD5Be4ArR9,sm_FVV34n_mrJ8Oa1tBlJaBnj
,sm_kDTYNj3erXleeDgn6ZWFBW,sm_V0_YXRZgCwhpfXYneT6RGZ,sm_FHYCSZTG0vl9b9VGL0KGKq
,sm_FDQbTuPesZpBfyxw_LpKXq,sm_kGyjll4U_mtHWylXcyTxum,sm_VglsO0uaWU8NiH2EnV6sMa
,sm_k8r3_pBpy_SOVDSsNbUp57,sm__A8dOkVl1BlhhaLAtbMLi2,&
sm_kM2T2UV5j_lvZaDBnKmoj0);if(sm_kM2T2UV5j_lvZaDBnKmoj0 .
sm_Vr11O__h4iWxb97wIDFqlh==1.0&&sm_kM2T2UV5j_lvZaDBnKmoj0 .
sm_VDreFLQlUl4E_yFFilfD24>sm_kH7c9UGCUNOFXqT6Omambe->sm_VDreFLQlUl4E_yFFilfD24
)memcpy(sm_ksmCaTaFQ2l8_9iJm6dWPG,&sm_kM2T2UV5j_lvZaDBnKmoj0,
sm__pKSrAzBV_4sWaHQ5axB2o*sizeof(real_T));}}}}
