#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
void pm_rv_equals_rv(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void pm_kpDvbw1GUlp4c5YdnW7V_w(const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
pm_V2SLaBJy5WtXim9Lma9hfD(const PmCharVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmCharVector*pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(
const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm__P4MWKrtjzGPcercL4W7Fn(const
PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*
pm__YmIqNX3g5Sub1vKK1hZQF);int_T pm_create_real_vector_fields(PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmRealVector*pm_create_real_vector(size_t pm__c6Ltywqrrtqii4hsDTKgz,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_V_q_QnwoVVl6fHS_0pLvYo(
const PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(const
PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(const PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_VH4is_vKxDpFiupATTqV_4(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(PmCharVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_FaBQ30lWObWMi1zpzQ_EZG(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*pm_FZch3YyGWrOM_PQNdo7b2c(
size_t pm__c6Ltywqrrtqii4hsDTKgz,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FJsPJplguVOI_1EYyUUvfK(const PmSizeVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmSizeVector*pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(
const PmSizeVector*pm__hARyx1bZBxVj1boVQqdtV,const PmSizeVector*
pm__YmIqNX3g5Sub1vKK1hZQF);size_t sm_ssci_kSxkhEQn_3p1XqGFTbb4JW(const
PmBoolVector*mc_VgJW5ZqpwPpuY1inYtaofQ);PmSparsityPattern*
sm_ssci_FBBKU9WNd4dqbDUe6lkrL_(const PmBoolVector*mc_FVG9mW_iV00Sd5jvvtdbAo,
size_t mc_VLHhnPUiNQpve5VIL9P3O9,size_t n);int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);PmSparsityPattern*pm_create_sparsity_pattern(size_t
pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*pm__56dBn4vKXWjZ1nclFRYZB,const
PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);boolean_T
pm__ZRI70SuGwhmamUtcsoyxS(const PmSparsityPattern*pm__56dBn4vKXWjZ1nclFRYZB,
const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);PmSparsityPattern*
pm_FQMLyYzCQ5CtgHjze1nNJP(const PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_FvcKvutPfxG9Xe1kjs7gg0(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(PmSparsityPattern*
pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t pm_FW8nEXbTFjdJhTIKepsgFT,
size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t pm_FW8nEXbTFjdJhTIKepsgFT,
size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t pm__lqjegyKuwStj56WZLiC_e,
size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
size_t sm_ssci_kSxkhEQn_3p1XqGFTbb4JW(const PmBoolVector*
mc_VgJW5ZqpwPpuY1inYtaofQ){size_t sm_ssci__BwCbGCDlrx2gDK5rof3H8=0;const
boolean_T*sm_ssci_FL1llpmubk_sXeD10Sbe3f=mc_VgJW5ZqpwPpuY1inYtaofQ->mX;const
boolean_T*mc_Vs6xonQX17Krc5vXv8T_zq=sm_ssci_FL1llpmubk_sXeD10Sbe3f+
mc_VgJW5ZqpwPpuY1inYtaofQ->mN;while(sm_ssci_FL1llpmubk_sXeD10Sbe3f<
mc_Vs6xonQX17Krc5vXv8T_zq)if(*sm_ssci_FL1llpmubk_sXeD10Sbe3f++)++
sm_ssci__BwCbGCDlrx2gDK5rof3H8;return sm_ssci__BwCbGCDlrx2gDK5rof3H8;}
PmSparsityPattern*sm_ssci_FBBKU9WNd4dqbDUe6lkrL_(const PmBoolVector*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_VLHhnPUiNQpve5VIL9P3O9,size_t n){const
size_t sm_ssci_FXIklBX4xG_xbD1ZfXa97h=sm_ssci_kSxkhEQn_3p1XqGFTbb4JW(
mc_FVG9mW_iV00Sd5jvvtdbAo);PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ=
pm_create_sparsity_pattern(sm_ssci_FXIklBX4xG_xbD1ZfXa97h,
mc_VLHhnPUiNQpve5VIL9P3O9,n,pm_default_allocator());int32_T*
sm_ssci_kXeDcvuOSpSqamcA4a5jc_=mc__srK5LmyWw42ZyPnbOWDWJ->mJc;int32_T*
sm_ssci_VEXzFHKjFN87iiOtLrddNz=mc__srK5LmyWw42ZyPnbOWDWJ->mIr;const int32_T*
const sm_ssci_VdX9ARnkpb4zci_etvBPWR=sm_ssci_VEXzFHKjFN87iiOtLrddNz;const
boolean_T*sm_ssci_FL1llpmubk_sXeD10Sbe3f=mc_FVG9mW_iV00Sd5jvvtdbAo->mX;size_t
mc_kwrB3ZoKf7OufTHWaHJV7a,mc_kyp6uAyJE40UVuAQNEYzS1;for(
mc_kyp6uAyJE40UVuAQNEYzS1=0;mc_kyp6uAyJE40UVuAQNEYzS1<n;++
mc_kyp6uAyJE40UVuAQNEYzS1){*sm_ssci_kXeDcvuOSpSqamcA4a5jc_++=((int32_T)(
sm_ssci_VEXzFHKjFN87iiOtLrddNz-sm_ssci_VdX9ARnkpb4zci_etvBPWR));for(
mc_kwrB3ZoKf7OufTHWaHJV7a=0;mc_kwrB3ZoKf7OufTHWaHJV7a<
mc_VLHhnPUiNQpve5VIL9P3O9;++mc_kwrB3ZoKf7OufTHWaHJV7a)if(*
sm_ssci_FL1llpmubk_sXeD10Sbe3f++)*sm_ssci_VEXzFHKjFN87iiOtLrddNz++=((int32_T)(
mc_kwrB3ZoKf7OufTHWaHJV7a));}*sm_ssci_kXeDcvuOSpSqamcA4a5jc_=((int32_T)(
sm_ssci_VEXzFHKjFN87iiOtLrddNz-sm_ssci_VdX9ARnkpb4zci_etvBPWR));return
mc__srK5LmyWw42ZyPnbOWDWJ;}
