#include "pm_std.h"
#include "string.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_V9ruOSVbJAWZjuCR6XC_ZQ NeDae;typedef struct
ssc_core_FA8XEJR378pZY90nzcNDHK ssc_core_FUa6G82CLwKVie8oX5VDDu;typedef struct
ssc_core_kn2fkwOG390ucqMrkmBlTh ssc_core__vkZ3rfXeilTgHxrnS_l_7;
#include "pm_std.h"
typedef struct ssc_core_FKc4tYGyO_p9beWwzb0Juo ssc_core_VDysZoxgYghwhXU1UYlmqx
;typedef struct ssc_core_Vfl7BS81ZAhV_5X2IQkzLW ssc_core_FNHwFizq1kxdVitsK9pEgv
;typedef enum{ssc_core_kMjk_uBRCutvWLcqcDYpL9= -1,
ssc_core_F7EYiSWVXlWmiu8kF9ezb_,ssc_core_k_4kEXoVHrtgcq_OGAKG2o,
ssc_core_F_OzpLs2M_pd_yHKAnv0fa}ssc_core__f_yrOvY5jpMci6b_XXvT0;
#include "pm_std.h"
#include "stdarg.h"
typedef ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E;
typedef struct ssc_core__0atO_17n_Ci_qYhoCxFUV ssc_core_F04yXT_zz14zgHdLildPgK
;struct ssc_core_Vfl7BS81ZAhV_5X2IQkzLW{ssc_core_F04yXT_zz14zgHdLildPgK*
mPrivateData;ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E(*ssc_core_VESUSzIzeRWSV1xYVr5zH5)
(const ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z);void(*
ssc_core__RtuwtEn2c_yh1OySiqODN)(const ssc_core_FNHwFizq1kxdVitsK9pEgv*
ssc_core_kPInN_8SRA_iYeTvYVKl3z,ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E
ssc_core_k3bA0_SocS_baqMdimEffE,ssc_core__f_yrOvY5jpMci6b_XXvT0
ssc_core_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId ssc_core__C0ajRzPQzOpeHB7hy4YXo,
va_list args);void(*ssc_core__YxE_N42_idoWyreGeTz9t)(const
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z,
ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E ssc_core_k3bA0_SocS_baqMdimEffE,
ssc_core__f_yrOvY5jpMci6b_XXvT0 ssc_core_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId
ssc_core__C0ajRzPQzOpeHB7hy4YXo,va_list args);void(*
ssc_core_kAPwXpB5miCGVLsko_7ONE)(const ssc_core_FNHwFizq1kxdVitsK9pEgv*
ssc_core_kPInN_8SRA_iYeTvYVKl3z,ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E
ssc_core_k3bA0_SocS_baqMdimEffE);void(*ssc_core__u9riBfE3RK3ZXQpAXjZW_)(const
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_FgQH451kC4lOZ5A2coatZe,const
ssc_core_FNHwFizq1kxdVitsK9pEgv*src);const ssc_core_VDysZoxgYghwhXU1UYlmqx*(*
ssc_core_kqsZroyTBbpjb1za_BT1dv)(const ssc_core_FNHwFizq1kxdVitsK9pEgv*
ssc_core_kPInN_8SRA_iYeTvYVKl3z);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z);};
PmfMessageId ssc_core_Fj4pG1CbqChThqCdYV3xux(const
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z,
ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E ssc_core_k3bA0_SocS_baqMdimEffE,
ssc_core__f_yrOvY5jpMci6b_XXvT0 ssc_core_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId
ssc_core__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
ssc_core_FqMmOIGGjkpTZ58Esd_XuA(const ssc_core_FNHwFizq1kxdVitsK9pEgv*
ssc_core_kPInN_8SRA_iYeTvYVKl3z,ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E
ssc_core_k3bA0_SocS_baqMdimEffE,ssc_core__f_yrOvY5jpMci6b_XXvT0
ssc_core_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId ssc_core__C0ajRzPQzOpeHB7hy4YXo,
...);PmfMessageId ssc_core_F5XP0Is_HAWucugpsjE8XK(const
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z,
ssc_core__f_yrOvY5jpMci6b_XXvT0 ssc_core_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId
ssc_core__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
ssc_core__w8As0Yf6B8Ji9iMi5WOGi(const ssc_core_FNHwFizq1kxdVitsK9pEgv*
ssc_core_kPInN_8SRA_iYeTvYVKl3z,ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E
ssc_core_k3bA0_SocS_baqMdimEffE,ssc_core__f_yrOvY5jpMci6b_XXvT0
ssc_core_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId ssc_core__C0ajRzPQzOpeHB7hy4YXo,
const char*ssc_core_kvsOBKjJwlx5dTxrw7qAwS);PmfMessageId
ssc_core__xrkslL_b0pOemBxsxBQx0(const ssc_core_FNHwFizq1kxdVitsK9pEgv*
ssc_core_kPInN_8SRA_iYeTvYVKl3z,ssc_core__f_yrOvY5jpMci6b_XXvT0
ssc_core_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId ssc_core__C0ajRzPQzOpeHB7hy4YXo,
const char*ssc_core_kvsOBKjJwlx5dTxrw7qAwS);ssc_core_FNHwFizq1kxdVitsK9pEgv*
neu_create_diagnostic_manager(PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);
PmfMessageId sm_ssci_recordRunTimeError(const char*
sm_ssci__6PNG7iUAXGmY91nGTNFtQ,const char*sm_ssci_FVy2C0leR8CCWimfFH365w,
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z);PmfMessageId
sm_ssci_recordRunTimeErrorSegmented(const char*sm_ssci__6PNG7iUAXGmY91nGTNFtQ,
size_t sm_ssci_k6i4tM17fjO4VqWxmqsjvB,const char*
sm_ssci__90mx8UQZ4lwWqq7cSpNXf[],char*sm_ssci_VQIQoS0DPsWjYmsmry0HQy,
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z);PmfMessageId
sm_ssci_recordRunTimeError(const char*sm_ssci__6PNG7iUAXGmY91nGTNFtQ,const char
*sm_ssci_FVy2C0leR8CCWimfFH365w,ssc_core_FNHwFizq1kxdVitsK9pEgv*
ssc_core_kPInN_8SRA_iYeTvYVKl3z){ssc_core_FjUEd5ZQJA0Ej1IosTlZ5E
ssc_core_k3bA0_SocS_baqMdimEffE=ssc_core_kPInN_8SRA_iYeTvYVKl3z->
ssc_core_VESUSzIzeRWSV1xYVr5zH5(ssc_core_kPInN_8SRA_iYeTvYVKl3z);return
ssc_core__w8As0Yf6B8Ji9iMi5WOGi(ssc_core_kPInN_8SRA_iYeTvYVKl3z,
ssc_core_k3bA0_SocS_baqMdimEffE,ssc_core_F7EYiSWVXlWmiu8kF9ezb_,
sm_ssci__6PNG7iUAXGmY91nGTNFtQ,sm_ssci_FVy2C0leR8CCWimfFH365w);}PmfMessageId
sm_ssci_recordRunTimeErrorSegmented(const char*sm_ssci__6PNG7iUAXGmY91nGTNFtQ,
size_t sm_ssci_k6i4tM17fjO4VqWxmqsjvB,const char*
sm_ssci__90mx8UQZ4lwWqq7cSpNXf[],char*sm_ssci_VQIQoS0DPsWjYmsmry0HQy,
ssc_core_FNHwFizq1kxdVitsK9pEgv*ssc_core_kPInN_8SRA_iYeTvYVKl3z){char*dst=
sm_ssci_VQIQoS0DPsWjYmsmry0HQy;size_t mc_kwrB3ZoKf7OufTHWaHJV7a;for(
mc_kwrB3ZoKf7OufTHWaHJV7a=0;mc_kwrB3ZoKf7OufTHWaHJV7a<
sm_ssci_k6i4tM17fjO4VqWxmqsjvB;++mc_kwrB3ZoKf7OufTHWaHJV7a){const size_t n=
strlen(sm_ssci__90mx8UQZ4lwWqq7cSpNXf[mc_kwrB3ZoKf7OufTHWaHJV7a]);memcpy(dst,
sm_ssci__90mx8UQZ4lwWqq7cSpNXf[mc_kwrB3ZoKf7OufTHWaHJV7a],n*sizeof(char));dst
+=n;}*dst='\0';return sm_ssci_recordRunTimeError(
sm_ssci__6PNG7iUAXGmY91nGTNFtQ,sm_ssci_VQIQoS0DPsWjYmsmry0HQy,
ssc_core_kPInN_8SRA_iYeTvYVKl3z);}
