#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core__bteFQO43Ht2gakrVoFUPq ssc_core__nRfEu8wcLpUiqE48gJSbq
;typedef struct ssc_core_V4aVbpgWpnGA_5_dCTJqKT ssc_core_FvQEWJt2H98AZmdqY_iazS
;struct ssc_core__bteFQO43Ht2gakrVoFUPq{size_t ssc_core_VOAPNvYIRPGzhDXn1iCcKS
;size_t ssc_core_kAKxIvM1NQGM_TY96YysC5;};struct
ssc_core_V4aVbpgWpnGA_5_dCTJqKT{double*ssc_core_VOMV27LEztpmd59gF8yJO0;int32_T
*ssc_core_F85sNEuWe1GIjmiT6vHSvn;ssc_core__nRfEu8wcLpUiqE48gJSbq mSizes;
ssc_core_FvQEWJt2H98AZmdqY_iazS*ssc_core__HGpmB64in_eWHsZP7Cb0h;};
ssc_core__nRfEu8wcLpUiqE48gJSbq ssc_core_kvaTUFehmelwWDNafwUyA0(void);
ssc_core_FvQEWJt2H98AZmdqY_iazS*ssc_core_VFzWBz_s8FW9_qamuHujnl(
ssc_core__nRfEu8wcLpUiqE48gJSbq ne_kCK4VKKlkwtEXP7Ya6eu5y);
ssc_core_FvQEWJt2H98AZmdqY_iazS*ssc_core__uWFHemgRS83bDIJli34aR(void);void
ssc_core_F3T_whDHVzdLcyptoeVcUU(ssc_core_FvQEWJt2H98AZmdqY_iazS*
ssc_core_FQj37QqwZMSgjLC3bhgfpn);
#include "pm_std.h"
ssc_core__nRfEu8wcLpUiqE48gJSbq ssc_core_kvaTUFehmelwWDNafwUyA0(void){
ssc_core__nRfEu8wcLpUiqE48gJSbq ssc_core__0REJ38_cKO_bunM1JCRT_;
ssc_core__0REJ38_cKO_bunM1JCRT_.ssc_core_VOAPNvYIRPGzhDXn1iCcKS=0;
ssc_core__0REJ38_cKO_bunM1JCRT_.ssc_core_kAKxIvM1NQGM_TY96YysC5=0;return
ssc_core__0REJ38_cKO_bunM1JCRT_;}ssc_core_FvQEWJt2H98AZmdqY_iazS*
ssc_core_VFzWBz_s8FW9_qamuHujnl(ssc_core__nRfEu8wcLpUiqE48gJSbq
ne_kCK4VKKlkwtEXP7Ya6eu5y){ssc_core_FvQEWJt2H98AZmdqY_iazS*
ssc_core_FQj37QqwZMSgjLC3bhgfpn=(ssc_core_FvQEWJt2H98AZmdqY_iazS*)pmf_malloc(
sizeof(ssc_core_FvQEWJt2H98AZmdqY_iazS));ssc_core_FQj37QqwZMSgjLC3bhgfpn->
mSizes=ne_kCK4VKKlkwtEXP7Ya6eu5y;ssc_core_FQj37QqwZMSgjLC3bhgfpn->
ssc_core_VOMV27LEztpmd59gF8yJO0=(double*)pmf_calloc(ne_kCK4VKKlkwtEXP7Ya6eu5y.
ssc_core_VOAPNvYIRPGzhDXn1iCcKS,sizeof(double));
ssc_core_FQj37QqwZMSgjLC3bhgfpn->ssc_core_F85sNEuWe1GIjmiT6vHSvn=(int32_T*)
pmf_calloc(ne_kCK4VKKlkwtEXP7Ya6eu5y.ssc_core_kAKxIvM1NQGM_TY96YysC5,sizeof(
int32_T));ssc_core_FQj37QqwZMSgjLC3bhgfpn->ssc_core__HGpmB64in_eWHsZP7Cb0h=
NULL;return ssc_core_FQj37QqwZMSgjLC3bhgfpn;}ssc_core_FvQEWJt2H98AZmdqY_iazS*
ssc_core__uWFHemgRS83bDIJli34aR(void){return ssc_core_VFzWBz_s8FW9_qamuHujnl(
ssc_core_kvaTUFehmelwWDNafwUyA0());}void ssc_core_F3T_whDHVzdLcyptoeVcUU(
ssc_core_FvQEWJt2H98AZmdqY_iazS*ssc_core_FQj37QqwZMSgjLC3bhgfpn){if(
ssc_core_FQj37QqwZMSgjLC3bhgfpn->ssc_core__HGpmB64in_eWHsZP7Cb0h!=NULL){
ssc_core_F3T_whDHVzdLcyptoeVcUU(ssc_core_FQj37QqwZMSgjLC3bhgfpn->
ssc_core__HGpmB64in_eWHsZP7Cb0h);}pmf_free(ssc_core_FQj37QqwZMSgjLC3bhgfpn->
ssc_core_VOMV27LEztpmd59gF8yJO0);pmf_free(ssc_core_FQj37QqwZMSgjLC3bhgfpn->
ssc_core_F85sNEuWe1GIjmiT6vHSvn);pmf_free(ssc_core_FQj37QqwZMSgjLC3bhgfpn);}
