#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_FKc4tYGyO_p9beWwzb0Juo ssc_core_VDysZoxgYghwhXU1UYlmqx
;typedef struct ssc_core_Vfl7BS81ZAhV_5X2IQkzLW ssc_core_FNHwFizq1kxdVitsK9pEgv
;typedef enum{ssc_core_kMjk_uBRCutvWLcqcDYpL9= -1,
ssc_core_F7EYiSWVXlWmiu8kF9ezb_,ssc_core_k_4kEXoVHrtgcq_OGAKG2o,
ssc_core_F_OzpLs2M_pd_yHKAnv0fa}ssc_core__f_yrOvY5jpMci6b_XXvT0;const char*
ssc_core_FklPsIWdcv4ra9YnF_YSgF(const ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ);const char*ssc_core__2lqkvRfia4Meqpodds2S6(
const ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core_kBj0wT0jErl0hDNP9N5QnJ);
ssc_core__f_yrOvY5jpMci6b_XXvT0 ssc_core__6mDXRaqmlWxceo9irjPSa(const
ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core_kBj0wT0jErl0hDNP9N5QnJ);size_t
ssc_core__lBbVf0HSftzcLnQ_Z0qa_(const ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ);const ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core__FHcTUUP4s_rbu4n0hd0z2(const ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ,size_t ssc_core_V2__YrimeI4E_yWnhKofpy);
typedef struct ssc_core_kemRd3LD2_pPVaAsNA5YDG ssc_core_VVipzh2oIBtKZ5hNqD2z_1
;typedef struct ssc_core_VAZekvvzo5CUcm0GE7lD8S ssc_core_FdhjQ_x6uEtWf5NrhiXPkC
;struct ssc_core_kemRd3LD2_pPVaAsNA5YDG{ssc_core_FdhjQ_x6uEtWf5NrhiXPkC*
mPrivateData;void(*mc_kt9hW2swhpxchivzz5BlCP)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv,ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ);ssc_core_VDysZoxgYghwhXU1UYlmqx*(*
ssc_core__ncbpuIDzMOrgqwrOKx4qs)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv);ssc_core_VDysZoxgYghwhXU1UYlmqx*(*
ssc_core_kQPAw1xwSVSbhTWPocMRHj)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv);ssc_core_VDysZoxgYghwhXU1UYlmqx*(*
ssc_core_FWUr7cMI27_XXuAo82pt8h)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv,size_t n);size_t(*
ssc_core_FRrT3ZKfnZCQ_TCtuEK5hH)(ssc_core_VVipzh2oIBtKZ5hNqD2z_1*
ssc_core__pLwoU6jmvWSV9dXhEIoIv);void(*mc_VYGWBho6N1K_eyHOMGjDiW)(
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*ssc_core__pLwoU6jmvWSV9dXhEIoIv);};
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*ssc_core_F__qZQpW_J4sVP_0nua696(PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z);typedef struct ssc_core_k6o6k1o1WGOpW1HJRvtMhF
ssc_core_V4o7rdTSXidje1ttVgvQFh;struct ssc_core_FKc4tYGyO_p9beWwzb0Juo{
ssc_core_V4o7rdTSXidje1ttVgvQFh*mPrivateData;char*
ssc_core_Vbr5eqH3ENhKgPrE0rHGwZ;char*ssc_core_VxRF0QCkLKh5auXYJTdv_i;
ssc_core__f_yrOvY5jpMci6b_XXvT0 ssc_core_kDBpxZEtSdlEii_qqd1dc7;
ssc_core_VVipzh2oIBtKZ5hNqD2z_1*ssc_core__VHqlgYzFJWCfL7_k_NRZF;void(*
mc_VYGWBho6N1K_eyHOMGjDiW)(ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ);};ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_FTcUm46bdDhggms5nJSPNZ(PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);const
char*ssc_core_FklPsIWdcv4ra9YnF_YSgF(const ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ){return ssc_core_kBj0wT0jErl0hDNP9N5QnJ->
ssc_core_Vbr5eqH3ENhKgPrE0rHGwZ;}const char*ssc_core__2lqkvRfia4Meqpodds2S6(
const ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core_kBj0wT0jErl0hDNP9N5QnJ){return
ssc_core_kBj0wT0jErl0hDNP9N5QnJ->ssc_core_VxRF0QCkLKh5auXYJTdv_i;}
ssc_core__f_yrOvY5jpMci6b_XXvT0 ssc_core__6mDXRaqmlWxceo9irjPSa(const
ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core_kBj0wT0jErl0hDNP9N5QnJ){return
ssc_core_kBj0wT0jErl0hDNP9N5QnJ->ssc_core_kDBpxZEtSdlEii_qqd1dc7;}size_t
ssc_core__lBbVf0HSftzcLnQ_Z0qa_(const ssc_core_VDysZoxgYghwhXU1UYlmqx*
ssc_core_kBj0wT0jErl0hDNP9N5QnJ){return(ssc_core_kBj0wT0jErl0hDNP9N5QnJ->
ssc_core__VHqlgYzFJWCfL7_k_NRZF)->ssc_core_FRrT3ZKfnZCQ_TCtuEK5hH((
ssc_core_kBj0wT0jErl0hDNP9N5QnJ->ssc_core__VHqlgYzFJWCfL7_k_NRZF));}const
ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core__FHcTUUP4s_rbu4n0hd0z2(const
ssc_core_VDysZoxgYghwhXU1UYlmqx*ssc_core_kBj0wT0jErl0hDNP9N5QnJ,size_t
ssc_core_V2__YrimeI4E_yWnhKofpy){return(ssc_core_kBj0wT0jErl0hDNP9N5QnJ->
ssc_core__VHqlgYzFJWCfL7_k_NRZF)->ssc_core_FWUr7cMI27_XXuAo82pt8h((
ssc_core_kBj0wT0jErl0hDNP9N5QnJ->ssc_core__VHqlgYzFJWCfL7_k_NRZF),(
ssc_core_V2__YrimeI4E_yWnhKofpy));}
